/*---- アカサタナハマヤラワ
     ポケモン名インデックス ----*/

#ifndef __ZKN_AKSTNHMYRW_HEADER__
#define __ZKN_AKSTNHMYRW_HEADER__


#define ZKN_AKSTNHMYRW_IDX_A  (0)
#define ZKN_AKSTNHMYRW_IDX_K  (55)
#define ZKN_AKSTNHMYRW_IDX_S  (139)
#define ZKN_AKSTNHMYRW_IDX_T  (185)
#define ZKN_AKSTNHMYRW_IDX_N  (242)
#define ZKN_AKSTNHMYRW_IDX_H  (271)
#define ZKN_AKSTNHMYRW_IDX_M  (378)
#define ZKN_AKSTNHMYRW_IDX_Y  (428)
#define ZKN_AKSTNHMYRW_IDX_R  (447)
#define ZKN_AKSTNHMYRW_IDX_W  (489)
#define ZKN_AKSTNHMYRW_IDX_END  (493)



#endif // __ZKN_AKSTNHMYRW_HEADER__
