NITROFS_FILES := files/data/UTF16.dat \
                 files/data/area00light.txt \
                 files/data/area01light.txt \
                 files/data/area02light.txt \
                 files/data/battle_win.NSCR \
                 files/data/btower_canm.resdat \
                 files/data/btower_celact.cldat \
                 files/data/btower_cell.resdat \
                 files/data/btower_chr.resdat \
                 files/data/btower_pal.resdat \
                 files/data/cell0.NCGR \
                 files/data/cell0.NCLR \
                 files/data/clact_default.NANR \
                 files/data/crystal.nsbmd \
                 files/data/demo_climax.narc \
                 files/data/dp_areawindow.NCGR \
                 files/data/dp_areawindow.NCLR \
                 files/data/dt_test_celact.txt \
                 files/data/dt_test_res_cell.txt \
                 files/data/dt_test_res_cellanm.txt \
                 files/data/dt_test_res_char.txt \
                 files/data/dt_test_res_multi.txt \
                 files/data/dt_test_res_multianm.txt \
                 files/data/dt_test_res_pltt.txt \
                 files/data/dun_sea.nsbtx \
                 files/data/eoo.dat \
                 files/data/exdata.dat \
                 files/data/field_cutin.narc \
                 files/data/fld_anime0.bin \
                 files/data/fld_anime1.bin \
                 files/data/fld_anime10.bin \
                 files/data/fld_anime2.bin \
                 files/data/fld_anime3.bin \
                 files/data/fld_anime4.bin \
                 files/data/fld_anime5.bin \
                 files/data/fld_anime6.bin \
                 files/data/fld_anime7.bin \
                 files/data/fld_anime8.bin \
                 files/data/fld_anime9.bin \
                 files/data/fs_kanban.nsbca \
                 files/data/ground0.NCGR \
                 files/data/ground0.NCLR \
                 files/data/ground0.NSCR \
                 files/data/kemu_itpconv.dat \
                 files/data/lake_anim.nsbtx \
                 files/data/miniasahamabe.nsbtx \
                 files/data/miniasasea.nsbtx \
                 files/data/minihamabe.nsbtx \
                 files/data/minimum.nsbtx \
                 files/data/minirhana.nsbtx \
                 files/data/namein.narc \
                 files/data/nfont.NCGR \
                 files/data/nfont.NCLR \
                 files/data/pc.nsbca \
                 files/data/plist_canm.resdat \
                 files/data/plist_cell.resdat \
                 files/data/plist_chr.resdat \
                 files/data/plist_h.cldat \
                 files/data/plist_pal.resdat \
                 files/data/porucase_canm.resdat \
                 files/data/porucase_celact.cldat \
                 files/data/porucase_cell.resdat \
                 files/data/porucase_chr.resdat \
                 files/data/porucase_pal.resdat \
                 files/data/pst_canm.resdat \
                 files/data/pst_cell.resdat \
                 files/data/pst_chr.resdat \
                 files/data/pst_h.cldat \
                 files/data/pst_pal.resdat \
                 files/data/shop_canm.resdat \
                 files/data/shop_cell.resdat \
                 files/data/shop_chr.resdat \
                 files/data/shop_h.cldat \
                 files/data/shop_pal.resdat \
                 files/data/slot.narc \
                 files/data/smptm_koori.NANR \
                 files/data/smptm_koori.NCER \
                 files/data/smptm_koori.NCGR \
                 files/data/smptm_koori.NCLR \
                 files/data/smptm_nemuri.NANR \
                 files/data/smptm_nemuri.NCER \
                 files/data/smptm_nemuri.NCGR \
                 files/data/smptm_nemuri.NCLR \
                 files/data/t3_fl_b.nsbtx \
                 files/data/t3_fl_p.nsbtx \
                 files/data/t3_fl_r.nsbtx \
                 files/data/t3_fl_y.nsbtx \
                 files/data/test.atr \
                 files/data/tmap_block.dat \
                 files/data/tmap_flags.dat \
                 files/data/tmapn_canm.resdat \
                 files/data/tmapn_celact.cldat \
                 files/data/tmapn_celact.txt \
                 files/data/tmapn_cell.resdat \
                 files/data/tmapn_chr.resdat \
                 files/data/tmapn_pal.resdat \
                 files/data/tmapn_res_canm.txt \
                 files/data/tmapn_res_cell.txt \
                 files/data/tmapn_res_chr.txt \
                 files/data/tmapn_res_pal.txt \
                 files/data/tradelist.narc \
                 files/data/trapmark.narc \
                 files/data/ug_anim.narc \
                 files/data/ug_base_cur.nsbmd \
                 files/data/ug_boygirl.NCGR \
                 files/data/ug_boygirl.NCLR \
                 files/data/ug_fossil.narc \
                 files/data/ug_hero.NANR \
                 files/data/ug_hero.NCER \
                 files/data/ug_hole.NANR \
                 files/data/ug_hole.NCER \
                 files/data/ug_hole.NCGR \
                 files/data/ug_parts.narc \
                 files/data/ug_radar.narc \
                 files/data/ug_trap.narc \
                 files/data/ugeffect_obj_graphic.narc \
                 files/data/uground_cell.resdat \
                 files/data/uground_cellanm.resdat \
                 files/data/uground_char.resdat \
                 files/data/uground_char2.resdat \
                 files/data/uground_clact.cldat \
                 files/data/uground_pltt.resdat \
                 files/data/uground_pltt2.resdat \
                 files/data/underg_radar.narc \
                 files/data/utility.bin \
                 files/data/weather_sys.narc \
                 files/data/wifi.ncgr \
                 files/data/wifinote.narc \
                 files/data/wifip2pmatch.narc \
                 files/data/wm.ncgr \
                 files/data/wm.nclr \
                 files/data/sound/sound_data.sdat \
                 files/msgdata/msg.narc \
                 files/msgdata/scenario/scr_msg.narc \
                 files/poketool/pokegra/height.narc \
                 files/poketool/pokegra/height_o.narc \
                 files/poketool/pokegra/otherpoke.narc \
                 files/poketool/pokegra/poke_shadow.narc \
                 files/poketool/pokegra/poke_shadow_ofx.narc \
                 files/poketool/pokegra/poke_yofs.narc \
                 files/poketool/pokegra/pokegra.narc \
                 files/poketool/trgra/trbgra.narc \
                 files/poketool/trgra/trfgra.narc \
                 files/poketool/personal/personal.narc \
                 files/poketool/personal/evo.narc \
                 files/poketool/personal/growtbl.narc \
                 files/poketool/personal/pms.narc \
                 files/poketool/personal/wotbl.narc \
                 files/poketool/trainer/trdata.narc \
                 files/poketool/trainer/trpoke.narc \
                 files/poketool/trmsg/trtbl.narc \
                 files/poketool/trmsg/trtblofs.narc \
                 files/battle/graphic/b_bag_gra.narc \
                 files/battle/graphic/b_plist_gra.narc \
                 files/battle/graphic/batt_bg.narc \
                 files/battle/graphic/batt_obj.narc \
                 files/battle/graphic/vs_demo_gra.narc \
                 files/wazaeffect/we.arc \
                 files/wazaeffect/we_sub.narc \
                 files/battle/skill/be_seq.narc \
                 files/battle/skill/sub_seq.narc \
                 files/battle/skill/waza_seq.narc \
                 files/wazaeffect/effectclact/wecell.narc \
                 files/wazaeffect/effectclact/wecellanm.narc \
                 files/wazaeffect/effectclact/wechar.narc \
                 files/wazaeffect/effectclact/wepltt.narc \
                 files/poketool/waza/waza_tbl.narc \
                 files/fielddata/script/scr_seq_release.narc \
                 files/graphic/bag_gra.narc \
                 files/graphic/box.narc \
                 files/graphic/btower.narc \
                 files/graphic/config_gra.narc \
                 files/graphic/demo_trade.narc \
                 files/graphic/dendou_demo.narc \
                 files/graphic/dendou_pc.narc \
                 files/graphic/ending.narc \
                 files/graphic/ev_pokeselect.narc \
                 files/graphic/f_note_gra.narc \
                 files/graphic/field_board.narc \
                 files/graphic/field_encounteffect.narc \
                 files/graphic/fld_comact.narc \
                 files/graphic/font.narc \
                 files/graphic/fontoam.narc \
                 files/graphic/hiden_effect.narc \
                 files/graphic/imageclip.narc \
                 files/graphic/mail_gra.narc \
                 files/graphic/menu_gra.narc \
                 files/graphic/mysign.narc \
                 files/graphic/mystery.narc \
                 files/graphic/ntag_gra.narc \
                 files/graphic/nutmixer.narc \
                 files/graphic/oekaki.narc \
                 files/graphic/opening.narc \
                 files/graphic/plist_gra.narc \
                 files/graphic/pmsi.narc \
                 files/graphic/poketch.narc \
                 files/graphic/poru_gra.narc \
                 files/graphic/poruact.narc \
                 files/graphic/porudemo.narc \
                 files/graphic/pst_gra.narc \
                 files/graphic/ranking.narc \
                 files/graphic/record.narc \
                 files/graphic/shop_gra.narc \
                 files/graphic/tmap_gra.narc \
                 files/graphic/touch_subwindow.narc \
                 files/graphic/trainer_case.narc \
                 files/graphic/unionroom.narc \
                 files/graphic/waza_oshie_gra.narc \
                 files/graphic/winframe.narc \
                 files/graphic/worldtrade.narc \
                 files/itemtool/itemdata/item_data.narc \
                 files/itemtool/itemdata/item_icon.narc \
                 files/itemtool/itemdata/nuts_data.narc \
                 files/poketool/icongra/poke_icon.narc \
                 files/poketool/pokefoot/pokefoot.narc \
                 files/data/mmodel/mmodel.narc \
                 files/data/mmodel/fldeff.narc \
                 files/wazaeffect/effectdata/ball_particle.narc \
                 files/wazaeffect/effectdata/waza_particle.narc \
                 files/wazaeffect/pt_debug/debug_particle.narc \
                 files/fielddata/eventdata/zone_event_release.narc \
                 files/fielddata/encountdata/d_enc_data.narc \
                 files/fielddata/encountdata/p_enc_data.narc \
                 files/fielddata/build_model/build_model.narc \
                 files/fielddata/build_model/build_model_matshp.dat \
                 files/fielddata/mapmatrix/map_matrix.narc \
                 files/fielddata/areadata/area_data.narc \
                 files/fielddata/areadata/area_build_model/area_build.narc \
                 files/fielddata/areadata/area_build_model/areabm_texset.narc \
                 files/fielddata/areadata/area_map_tex/map_tex_set.narc \
                 files/fielddata/areadata/area_move_model/move_model_list.narc \
                 files/fielddata/land_data/land_data_release.narc \
                 files/contest/graphic/contest_bg.narc \
                 files/contest/graphic/contest_obj.narc \
                 files/contest/data/contest_data.narc \
                 files/particledata/particledata.narc \
                 files/application/zukanlist/zkn_data/zukan_data.narc \
                 files/application/wifi_earth/wifi_earth.narc \
                 files/application/wifi_earth/wifi_earth_place.narc \
                 files/demo/title/titledemo.narc \
                 files/application/custom_ball/data/cb_data.narc \
                 files/demo/egg/data/egg_data.narc \
                 files/demo/egg/data/particle/egg_demo_particle.narc \
                 files/fielddata/mm_list/move_model_list.narc \
                 files/pokeanime/poke_anm.narc \
                 files/battle/tr_ai/tr_ai_seq.narc \
                 files/arc/bm_anime.narc \
                 files/arc/bm_anime_list.narc \
                 files/arc/encdata_ex.narc \
                 files/arc/ppark.narc \
                 files/arc/ship_demo.narc \
                 files/arc/tv.narc \
                 files/fielddata/maptable/mapname.bin \
                 files/poketool/pokezukan.narc \
                 files/poketool/shinzukan.narc \
                 files/poketool/pokeanm/pokeanm.narc \
                 files/fielddata/pokemon_trade/fld_trade.narc \
                 files/demo/shinka/data/particle/shinka_demo_particle.narc \
                 files/demo/intro/intro.narc \
                 files/demo/intro/intro_tv.narc \
                 files/demo/title/op_demo.narc \
                 files/demo/syoujyou/syoujyou.narc \
                 files/battle/b_tower/btdpm.narc \
                 files/battle/b_tower/btdtr.narc \
                 files/application/zukanlist/zkn_data/zukan_enc_diamond.narc \
                 files/application/zukanlist/zkn_data/zukan_enc_pearl.narc \
                 files/resource/eng/trial/trial.narc \
                 files/resource/eng/zukan/zukan.narc \
                 files/dwc/utility.bin

ifeq ($(GAME_VERSION),PEARL)
NITROFS_FILES = $(NITROFS_FILES:poketool/personal/personal.narc=poketool/personal_pearl/personal.narc)
endif
