#ifndef POKEDIAMOND_CONSTANTS_BADGE_H
#define POKEDIAMOND_CONSTANTS_BADGE_H

#define BADGE_COAL   0
#define BADGE_FOREST 1
#define BADGE_COBBLE 2
#define BADGE_FEN    3
#define BADGE_RELIC  4
#define BADGE_MINE   5
#define BADGE_ICICLE 6
#define BADGE_BEACON 7

#endif // POKEDIAMOND_CONSTANTS_BADGE_H
