#ifndef POKEDIAMOND_CONSTANTS_CHARCODE_H
#define POKEDIAMOND_CONSTANTS_CHARCODE_H

#define CHAR_NUL                                0
#define CHAR_JP_SPACE                           1

#define CHAR_JP_HIRA_A_SMALL                    2
#define CHAR_JP_HIRA_A                          3
#define CHAR_JP_HIRA_I_SMALL                    4
#define CHAR_JP_HIRA_I                          5
#define CHAR_JP_HIRA_U_SMALL                    6
#define CHAR_JP_HIRA_U                          7
#define CHAR_JP_HIRA_E_SMALL                    8
#define CHAR_JP_HIRA_E                          9
#define CHAR_JP_HIRA_O_SMALL                   10
#define CHAR_JP_HIRA_O                         11
#define CHAR_JP_HIRA_KA                        12
#define CHAR_JP_HIRA_GA                        13
#define CHAR_JP_HIRA_KI                        14
#define CHAR_JP_HIRA_GI                        15
#define CHAR_JP_HIRA_KU                        16
#define CHAR_JP_HIRA_GU                        17
#define CHAR_JP_HIRA_KE                        18
#define CHAR_JP_HIRA_GE                        19
#define CHAR_JP_HIRA_KO                        20
#define CHAR_JP_HIRA_GO                        21
#define CHAR_JP_HIRA_SA                        22
#define CHAR_JP_HIRA_ZA                        23
#define CHAR_JP_HIRA_SI                        24
#define CHAR_JP_HIRA_ZI                        25
#define CHAR_JP_HIRA_SU                        26
#define CHAR_JP_HIRA_ZU                        27
#define CHAR_JP_HIRA_SE                        28
#define CHAR_JP_HIRA_ZE                        29
#define CHAR_JP_HIRA_SO                        30
#define CHAR_JP_HIRA_ZO                        31
#define CHAR_JP_HIRA_TA                        32
#define CHAR_JP_HIRA_DA                        33
#define CHAR_JP_HIRA_TI                        34
#define CHAR_JP_HIRA_DI                        35
#define CHAR_JP_HIRA_TU_SMALL                  36
#define CHAR_JP_HIRA_TU                        37
#define CHAR_JP_HIRA_DU                        38
#define CHAR_JP_HIRA_TE                        39
#define CHAR_JP_HIRA_DE                        40
#define CHAR_JP_HIRA_TO                        41
#define CHAR_JP_HIRA_DO                        42
#define CHAR_JP_HIRA_NA                        43
#define CHAR_JP_HIRA_NI                        44
#define CHAR_JP_HIRA_NU                        45
#define CHAR_JP_HIRA_NE                        46
#define CHAR_JP_HIRA_NO                        47
#define CHAR_JP_HIRA_HA                        48
#define CHAR_JP_HIRA_BA                        49
#define CHAR_JP_HIRA_PA                        50
#define CHAR_JP_HIRA_HI                        51
#define CHAR_JP_HIRA_BI                        52
#define CHAR_JP_HIRA_PI                        53
#define CHAR_JP_HIRA_HU                        54
#define CHAR_JP_HIRA_BU                        55
#define CHAR_JP_HIRA_PU                        56
#define CHAR_JP_HIRA_HE                        57
#define CHAR_JP_HIRA_BE                        58
#define CHAR_JP_HIRA_PE                        59
#define CHAR_JP_HIRA_HO                        60
#define CHAR_JP_HIRA_BO                        61
#define CHAR_JP_HIRA_PO                        62
#define CHAR_JP_HIRA_MA                        63
#define CHAR_JP_HIRA_MI                        64
#define CHAR_JP_HIRA_MU                        65
#define CHAR_JP_HIRA_ME                        66
#define CHAR_JP_HIRA_MO                        67
#define CHAR_JP_HIRA_YA_SMALL                  68
#define CHAR_JP_HIRA_YA                        69
#define CHAR_JP_HIRA_YU_SMALL                  70
#define CHAR_JP_HIRA_YU                        71
#define CHAR_JP_HIRA_YO_SMALL                  72
#define CHAR_JP_HIRA_YO                        73
#define CHAR_JP_HIRA_RA                        74
#define CHAR_JP_HIRA_RI                        75
#define CHAR_JP_HIRA_RU                        76
#define CHAR_JP_HIRA_RE                        77
#define CHAR_JP_HIRA_RO                        78
#define CHAR_JP_HIRA_WA                        79
#define CHAR_JP_HIRA_WO                        80
#define CHAR_JP_HIRA_N_                        81

#define CHAR_JP_KATA_A_SMALL                   82
#define CHAR_JP_KATA_A                         83
#define CHAR_JP_KATA_I_SMALL                   84
#define CHAR_JP_KATA_I                         85
#define CHAR_JP_KATA_U_SMALL                   86
#define CHAR_JP_KATA_U                         87
#define CHAR_JP_KATA_E_SMALL                   88
#define CHAR_JP_KATA_E                         89
#define CHAR_JP_KATA_O_SMALL                   90
#define CHAR_JP_KATA_O                         91
#define CHAR_JP_KATA_KA                        92
#define CHAR_JP_KATA_GA                        93
#define CHAR_JP_KATA_KI                        94
#define CHAR_JP_KATA_GI                        95
#define CHAR_JP_KATA_KU                        96
#define CHAR_JP_KATA_GU                        97
#define CHAR_JP_KATA_KE                        98
#define CHAR_JP_KATA_GE                        99
#define CHAR_JP_KATA_KO                       100
#define CHAR_JP_KATA_GO                       101
#define CHAR_JP_KATA_SA                       102
#define CHAR_JP_KATA_ZA                       103
#define CHAR_JP_KATA_SI                       104
#define CHAR_JP_KATA_ZI                       105
#define CHAR_JP_KATA_SU                       106
#define CHAR_JP_KATA_ZU                       107
#define CHAR_JP_KATA_SE                       108
#define CHAR_JP_KATA_ZE                       109
#define CHAR_JP_KATA_SO                       110
#define CHAR_JP_KATA_ZO                       111
#define CHAR_JP_KATA_TA                       112
#define CHAR_JP_KATA_DA                       113
#define CHAR_JP_KATA_TI                       114
#define CHAR_JP_KATA_DI                       115
#define CHAR_JP_KATA_TU_SMALL                 116
#define CHAR_JP_KATA_TU                       117
#define CHAR_JP_KATA_DU                       118
#define CHAR_JP_KATA_TE                       119
#define CHAR_JP_KATA_DE                       120
#define CHAR_JP_KATA_TO                       121
#define CHAR_JP_KATA_DO                       122
#define CHAR_JP_KATA_NA                       123
#define CHAR_JP_KATA_NI                       124
#define CHAR_JP_KATA_NU                       125
#define CHAR_JP_KATA_NE                       126
#define CHAR_JP_KATA_NO                       127
#define CHAR_JP_KATA_HA                       128
#define CHAR_JP_KATA_BA                       129
#define CHAR_JP_KATA_PA                       130
#define CHAR_JP_KATA_HI                       131
#define CHAR_JP_KATA_BI                       132
#define CHAR_JP_KATA_PI                       133
#define CHAR_JP_KATA_HU                       134
#define CHAR_JP_KATA_BU                       135
#define CHAR_JP_KATA_PU                       136
#define CHAR_JP_KATA_HE                       137
#define CHAR_JP_KATA_BE                       138
#define CHAR_JP_KATA_PE                       139
#define CHAR_JP_KATA_HO                       140
#define CHAR_JP_KATA_BO                       141
#define CHAR_JP_KATA_PO                       142
#define CHAR_JP_KATA_MA                       143
#define CHAR_JP_KATA_MI                       144
#define CHAR_JP_KATA_MU                       145
#define CHAR_JP_KATA_ME                       146
#define CHAR_JP_KATA_MO                       147
#define CHAR_JP_KATA_YA_SMALL                 148
#define CHAR_JP_KATA_YA                       149
#define CHAR_JP_KATA_YU_SMALL                 150
#define CHAR_JP_KATA_YU                       151
#define CHAR_JP_KATA_YO_SMALL                 152
#define CHAR_JP_KATA_YO                       153
#define CHAR_JP_KATA_RA                       154
#define CHAR_JP_KATA_RI                       155
#define CHAR_JP_KATA_RU                       156
#define CHAR_JP_KATA_RE                       157
#define CHAR_JP_KATA_RO                       158
#define CHAR_JP_KATA_WA                       159
#define CHAR_JP_KATA_WO                       160
#define CHAR_JP_KATA_N_                       161

#define CHAR_JP_0                             162
#define CHAR_JP_1                             163
#define CHAR_JP_2                             164
#define CHAR_JP_3                             165
#define CHAR_JP_4                             166
#define CHAR_JP_5                             167
#define CHAR_JP_6                             168
#define CHAR_JP_7                             169
#define CHAR_JP_8                             170
#define CHAR_JP_9                             171
#define CHAR_JP_A                             172
#define CHAR_JP_B                             173
#define CHAR_JP_C                             174
#define CHAR_JP_D                             175
#define CHAR_JP_E                             176
#define CHAR_JP_F                             177

#define CHAR_JP_QUESTION_MARK                 226

#define CHAR_JP_HYPHEN                        241

#define CHAR_0                                289
#define CHAR_1                                290
#define CHAR_2                                291
#define CHAR_3                                292
#define CHAR_4                                293
#define CHAR_5                                294
#define CHAR_6                                295
#define CHAR_7                                296
#define CHAR_8                                297
#define CHAR_9                                298
#define CHAR_A                                299
#define CHAR_B                                300
#define CHAR_C                                301
#define CHAR_D                                302
#define CHAR_E                                303
#define CHAR_F                                304
#define CHAR_G                                305
#define CHAR_H                                306
#define CHAR_I                                307
#define CHAR_J                                308
#define CHAR_K                                309
#define CHAR_L                                310
#define CHAR_M                                311
#define CHAR_N                                312
#define CHAR_O                                313
#define CHAR_P                                314
#define CHAR_Q                                315
#define CHAR_R                                316
#define CHAR_S                                317
#define CHAR_T                                318
#define CHAR_U                                319
#define CHAR_V                                320
#define CHAR_W                                321
#define CHAR_X                                322
#define CHAR_Y                                323
#define CHAR_Z                                324
#define CHAR_a                                325
#define CHAR_b                                326
#define CHAR_c                                327
#define CHAR_d                                328
#define CHAR_e                                329
#define CHAR_f                                330
#define CHAR_g                                331
#define CHAR_h                                332
#define CHAR_i                                333
#define CHAR_j                                334
#define CHAR_k                                335
#define CHAR_l                                336
#define CHAR_m                                337
#define CHAR_n                                338
#define CHAR_o                                339
#define CHAR_p                                340
#define CHAR_q                                341
#define CHAR_r                                342
#define CHAR_s                                343
#define CHAR_t                                344
#define CHAR_u                                345
#define CHAR_v                                346
#define CHAR_w                                347
#define CHAR_x                                348
#define CHAR_y                                349
#define CHAR_z                                350

#define CHAR_ELLIPSIS                         431

#define CHAR_HYPHEN                           446

#define CHAR_SPACE                            478

#define CHAR_NARROW_SPACE                     482

#define CHAR_ONE_DOT                          491
#define CHAR_TWO_DOTS                         492

#define CHAR_LF           0xE000
#define TRNAMECODE        0xF100
#define EXT_CTRL_CODE_BEGIN 0xFFFE
#define EOS               0xFFFF   // _EOM
#define TRNAME_MASK       0x1FF
#define EOS_TRNAME        0x1FF

#endif //POKEDIAMOND_CONSTANTS_CHARCODE_H