#ifndef POKEDIAMOND_CONSTANTS_CHARCODE_H
#define POKEDIAMOND_CONSTANTS_CHARCODE_H

#define CHAR_NONE                     0
#define CHAR_JP_SPACE                 1
#define CHAR_JP_HIRA_A_SMALL          2
#define CHAR_JP_HIRA_A                3
#define CHAR_JP_HIRA_I_SMALL          4
#define CHAR_JP_HIRA_I                5
#define CHAR_JP_HIRA_U_SMALL          6
#define CHAR_JP_HIRA_U                7
#define CHAR_JP_HIRA_E_SMALL          8
#define CHAR_JP_HIRA_E                9
#define CHAR_JP_HIRA_O_SMALL          10
#define CHAR_JP_HIRA_O                11
#define CHAR_JP_HIRA_KA               12
#define CHAR_JP_HIRA_GA               13
#define CHAR_JP_HIRA_KI               14
#define CHAR_JP_HIRA_GI               15
#define CHAR_JP_HIRA_KU               16
#define CHAR_JP_HIRA_GU               17
#define CHAR_JP_HIRA_KE               18
#define CHAR_JP_HIRA_GE               19
#define CHAR_JP_HIRA_KO               20
#define CHAR_JP_HIRA_GO               21
#define CHAR_JP_HIRA_SA               22
#define CHAR_JP_HIRA_ZA               23
#define CHAR_JP_HIRA_SHI              24
#define CHAR_JP_HIRA_JI               25
#define CHAR_JP_HIRA_SU               26
#define CHAR_JP_HIRA_ZU               27
#define CHAR_JP_HIRA_SE               28
#define CHAR_JP_HIRA_ZE               29
#define CHAR_JP_HIRA_SO               30
#define CHAR_JP_HIRA_ZO               31
#define CHAR_JP_HIRA_TA               32
#define CHAR_JP_HIRA_DA               33
#define CHAR_JP_HIRA_CHI              34
#define CHAR_JP_HIRA_DJI              35
#define CHAR_JP_HIRA_SOKUON           36
#define CHAR_JP_HIRA_TSU              37
#define CHAR_JP_HIRA_DZU              38
#define CHAR_JP_HIRA_TE               39
#define CHAR_JP_HIRA_DE               40
#define CHAR_JP_HIRA_TO               41
#define CHAR_JP_HIRA_DO               42
#define CHAR_JP_HIRA_NA               43
#define CHAR_JP_HIRA_NI               44
#define CHAR_JP_HIRA_NU               45
#define CHAR_JP_HIRA_NE               46
#define CHAR_JP_HIRA_NO               47
#define CHAR_JP_HIRA_HA               48
#define CHAR_JP_HIRA_BA               49
#define CHAR_JP_HIRA_PA               50
#define CHAR_JP_HIRA_HI               51
#define CHAR_JP_HIRA_BI               52
#define CHAR_JP_HIRA_PI               53
#define CHAR_JP_HIRA_FU               54
#define CHAR_JP_HIRA_BU               55
#define CHAR_JP_HIRA_PU               56
#define CHAR_JP_HIRA_HE               57
#define CHAR_JP_HIRA_BE               58
#define CHAR_JP_HIRA_PE               59
#define CHAR_JP_HIRA_HO               60
#define CHAR_JP_HIRA_BO               61
#define CHAR_JP_HIRA_PO               62
#define CHAR_JP_HIRA_MA               63
#define CHAR_JP_HIRA_MI               64
#define CHAR_JP_HIRA_MU               65
#define CHAR_JP_HIRA_ME               66
#define CHAR_JP_HIRA_MO               67
#define CHAR_JP_HIRA_YA_SMALL         68
#define CHAR_JP_HIRA_YA               69
#define CHAR_JP_HIRA_YU_SMALL         70
#define CHAR_JP_HIRA_YU               71
#define CHAR_JP_HIRA_YO_SMALL         72
#define CHAR_JP_HIRA_YO               73
#define CHAR_JP_HIRA_RA               74
#define CHAR_JP_HIRA_RI               75
#define CHAR_JP_HIRA_RU               76
#define CHAR_JP_HIRA_RE               77
#define CHAR_JP_HIRA_RO               78
#define CHAR_JP_HIRA_WA               79
#define CHAR_JP_HIRA_WO               80
#define CHAR_JP_HIRA_N                81
#define CHAR_JP_KATA_A_SMALL          82
#define CHAR_JP_KATA_A                83
#define CHAR_JP_KATA_I_SMALL          84
#define CHAR_JP_KATA_I                85
#define CHAR_JP_KATA_U_SMALL          86
#define CHAR_JP_KATA_U                87
#define CHAR_JP_KATA_E_SMALL          88
#define CHAR_JP_KATA_E                89
#define CHAR_JP_KATA_O_SMALL          90
#define CHAR_JP_KATA_O                91
#define CHAR_JP_KATA_KA               92
#define CHAR_JP_KATA_GA               93
#define CHAR_JP_KATA_KI               94
#define CHAR_JP_KATA_GI               95
#define CHAR_JP_KATA_KU               96
#define CHAR_JP_KATA_GU               97
#define CHAR_JP_KATA_KE               98
#define CHAR_JP_KATA_GE               99
#define CHAR_JP_KATA_KO               100
#define CHAR_JP_KATA_GO               101
#define CHAR_JP_KATA_SA               102
#define CHAR_JP_KATA_ZA               103
#define CHAR_JP_KATA_SHI              104
#define CHAR_JP_KATA_JI               105
#define CHAR_JP_KATA_SU               106
#define CHAR_JP_KATA_ZU               107
#define CHAR_JP_KATA_SE               108
#define CHAR_JP_KATA_ZE               109
#define CHAR_JP_KATA_SO               110
#define CHAR_JP_KATA_ZO               111
#define CHAR_JP_KATA_TA               112
#define CHAR_JP_KATA_DA               113
#define CHAR_JP_KATA_CHI              114
#define CHAR_JP_KATA_DJI              115
#define CHAR_JP_KATA_SOKUON           116
#define CHAR_JP_KATA_TSU              117
#define CHAR_JP_KATA_DZU              118
#define CHAR_JP_KATA_TE               119
#define CHAR_JP_KATA_DE               120
#define CHAR_JP_KATA_TO               121
#define CHAR_JP_KATA_DO               122
#define CHAR_JP_KATA_NA               123
#define CHAR_JP_KATA_NI               124
#define CHAR_JP_KATA_NU               125
#define CHAR_JP_KATA_NE               126
#define CHAR_JP_KATA_NO               127
#define CHAR_JP_KATA_HA               128
#define CHAR_JP_KATA_BA               129
#define CHAR_JP_KATA_PA               130
#define CHAR_JP_KATA_HI               131
#define CHAR_JP_KATA_BI               132
#define CHAR_JP_KATA_PI               133
#define CHAR_JP_KATA_FU               134
#define CHAR_JP_KATA_BU               135
#define CHAR_JP_KATA_PU               136
#define CHAR_JP_KATA_HE               137
#define CHAR_JP_KATA_BE               138
#define CHAR_JP_KATA_PE               139
#define CHAR_JP_KATA_HO               140
#define CHAR_JP_KATA_BO               141
#define CHAR_JP_KATA_PO               142
#define CHAR_JP_KATA_MA               143
#define CHAR_JP_KATA_MI               144
#define CHAR_JP_KATA_MU               145
#define CHAR_JP_KATA_ME               146
#define CHAR_JP_KATA_MO               147
#define CHAR_JP_KATA_YA_SMALL         148
#define CHAR_JP_KATA_YA               149
#define CHAR_JP_KATA_YU_SMALL         150
#define CHAR_JP_KATA_YU               151
#define CHAR_JP_KATA_YO_SMALL         152
#define CHAR_JP_KATA_YO               153
#define CHAR_JP_KATA_RA               154
#define CHAR_JP_KATA_RI               155
#define CHAR_JP_KATA_RU               156
#define CHAR_JP_KATA_RE               157
#define CHAR_JP_KATA_RO               158
#define CHAR_JP_KATA_WA               159
#define CHAR_JP_KATA_WO               160
#define CHAR_JP_KATA_N                161
#define CHAR_JP_0                     162
#define CHAR_JP_1                     163
#define CHAR_JP_2                     164
#define CHAR_JP_3                     165
#define CHAR_JP_4                     166
#define CHAR_JP_5                     167
#define CHAR_JP_6                     168
#define CHAR_JP_7                     169
#define CHAR_JP_8                     170
#define CHAR_JP_9                     171
#define CHAR_JP_A                     172
#define CHAR_JP_B                     173
#define CHAR_JP_C                     174
#define CHAR_JP_D                     175
#define CHAR_JP_E                     176
#define CHAR_JP_F                     177
#define CHAR_JP_G                     178
#define CHAR_JP_H                     179
#define CHAR_JP_I                     180
#define CHAR_JP_J                     181
#define CHAR_JP_K                     182
#define CHAR_JP_L                     183
#define CHAR_JP_M                     184
#define CHAR_JP_N                     185
#define CHAR_JP_O                     186
#define CHAR_JP_P                     187
#define CHAR_JP_Q                     188
#define CHAR_JP_R                     189
#define CHAR_JP_S                     190
#define CHAR_JP_T                     191
#define CHAR_JP_U                     192
#define CHAR_JP_V                     193
#define CHAR_JP_W                     194
#define CHAR_JP_X                     195
#define CHAR_JP_Y                     196
#define CHAR_JP_Z                     197
#define CHAR_JP_a                     198
#define CHAR_JP_b                     199
#define CHAR_JP_c                     200
#define CHAR_JP_d                     201
#define CHAR_JP_e                     202
#define CHAR_JP_f                     203
#define CHAR_JP_g                     204
#define CHAR_JP_h                     205
#define CHAR_JP_i                     206
#define CHAR_JP_j                     207
#define CHAR_JP_k                     208
#define CHAR_JP_l                     209
#define CHAR_JP_m                     210
#define CHAR_JP_n                     211
#define CHAR_JP_o                     212
#define CHAR_JP_p                     213
#define CHAR_JP_q                     214
#define CHAR_JP_r                     215
#define CHAR_JP_s                     216
#define CHAR_JP_t                     217
#define CHAR_JP_u                     218
#define CHAR_JP_v                     219
#define CHAR_JP_w                     220
#define CHAR_JP_x                     221
#define CHAR_JP_y                     222
#define CHAR_JP_z                     223
#define CHAR_JP_TRANSPARENT           224
#define CHAR_JP_EMARK                 225
#define CHAR_JP_QMARK                 226
#define CHAR_JP_COMMA                 227
#define CHAR_JP_FULL_STOP             228
#define CHAR_JP_ELLIPSIS              229
#define CHAR_JP_DOT                   230
#define CHAR_JP_SLASH                 231
#define CHAR_JP_SINGLE_QUOTE_OPEN     232
#define CHAR_JP_SINGLE_QUOTE_CLOSE    233
#define CHAR_JP_DOUBLE_QUOTE_OPEN     234
#define CHAR_JP_DOUBLE_QUOTE_CLOSE    235
#define CHAR_JP_PARENTHESES_OPEN      236
#define CHAR_JP_PARENTHESES_CLOSE     237
#define CHAR_JP_MALE                  238
#define CHAR_JP_FEMALE                239
#define CHAR_JP_PLUS                  240
#define CHAR_JP_MINUS                 241
#define CHAR_JP_MULTIPLY              242
#define CHAR_JP_DIVIDE                243
#define CHAR_JP_EQUALS                244
#define CHAR_JP_TILDE                 245
#define CHAR_JP_HW_COLON              246
#define CHAR_JP_HW_SEMICOLON          247
#define CHAR_JP_HW_PERIOD             248
#define CHAR_JP_HW_COMMA              249
#define CHAR_JP_SPADE_SUIT            250
#define CHAR_JP_CLUB_SUIT             251
#define CHAR_JP_HEART_SUIT            252
#define CHAR_JP_DIAMOND_SUIT          253
#define CHAR_JP_STAR                  254
#define CHAR_JP_DOUBLE_CIRCLE         255
#define CHAR_JP_CIRCLE                256
#define CHAR_JP_SQUARE                257
#define CHAR_JP_TRIANGLE              258
#define CHAR_JP_DIAMOND               259
#define CHAR_JP_AT_SIGN               260
#define CHAR_JP_MUSIC_NOTE            261
#define CHAR_JP_PERCENT               262
#define CHAR_JP_SUN                   263
#define CHAR_JP_CLOUD                 264
#define CHAR_JP_UMBRELLA              265
#define CHAR_JP_SNOWMAN               266
#define CHAR_JP_EMOTE_SMILE           267
#define CHAR_JP_EMOTE_LAUGH           268
#define CHAR_JP_EMOTE_UPSET           269
#define CHAR_JP_EMOTE_FROWN           270
#define CHAR_JP_ARROW_CURVE_UP        271
#define CHAR_JP_ARROW_CURVE_DOWN      272
#define CHAR_JP_ZZZ                   273
#define CHAR_JP_CURRENCY              274
#define CHAR_POCKET_ICON_ITEMS        275
#define CHAR_POCKET_ICON_KEY_ITEMS    276
#define CHAR_POCKET_ICON_TMS_HMS      277
#define CHAR_POCKET_ICON_MAIL         278
#define CHAR_POCKET_ICON_MEDICINE     279
#define CHAR_POCKET_ICON_BERRIES      280
#define CHAR_POCKET_ICON_POKE_BALLS   281
#define CHAR_POCKET_ICON_BATTLE_ITEMS 282
#define CHAR_ARROW_LEFT               283
#define CHAR_ARROW_UP                 284
#define CHAR_ARROW_DOWN               285
#define CHAR_ARROW_RIGHT              286
#define CHAR_ARROW_MENU               287
#define CHAR_JP_AMPERSAND             288
#define CHAR_0                        289
#define CHAR_1                        290
#define CHAR_2                        291
#define CHAR_3                        292
#define CHAR_4                        293
#define CHAR_5                        294
#define CHAR_6                        295
#define CHAR_7                        296
#define CHAR_8                        297
#define CHAR_9                        298
#define CHAR_A                        299
#define CHAR_B                        300
#define CHAR_C                        301
#define CHAR_D                        302
#define CHAR_E                        303
#define CHAR_F                        304
#define CHAR_G                        305
#define CHAR_H                        306
#define CHAR_I                        307
#define CHAR_J                        308
#define CHAR_K                        309
#define CHAR_L                        310
#define CHAR_M                        311
#define CHAR_N                        312
#define CHAR_O                        313
#define CHAR_P                        314
#define CHAR_Q                        315
#define CHAR_R                        316
#define CHAR_S                        317
#define CHAR_T                        318
#define CHAR_U                        319
#define CHAR_V                        320
#define CHAR_W                        321
#define CHAR_X                        322
#define CHAR_Y                        323
#define CHAR_Z                        324
#define CHAR_a                        325
#define CHAR_b                        326
#define CHAR_c                        327
#define CHAR_d                        328
#define CHAR_e                        329
#define CHAR_f                        330
#define CHAR_g                        331
#define CHAR_h                        332
#define CHAR_i                        333
#define CHAR_j                        334
#define CHAR_k                        335
#define CHAR_l                        336
#define CHAR_m                        337
#define CHAR_n                        338
#define CHAR_o                        339
#define CHAR_p                        340
#define CHAR_q                        341
#define CHAR_r                        342
#define CHAR_s                        343
#define CHAR_t                        344
#define CHAR_u                        345
#define CHAR_v                        346
#define CHAR_w                        347
#define CHAR_x                        348
#define CHAR_y                        349
#define CHAR_z                        350
#define CHAR_A_GRAVE                  351
#define CHAR_A_ACUTE                  352
#define CHAR_A_CIRCUMFLEX             353
#define CHAR_A_TILDE                  354
#define CHAR_A_DIERESIS               355
#define CHAR_A_OVERDOT                356
#define CHAR_AE                       357
#define CHAR_C_CEDILLA                358
#define CHAR_E_GRAVE                  359
#define CHAR_E_ACUTE                  360
#define CHAR_E_CIRCUMFLEX             361
#define CHAR_E_DIERESIS               362
#define CHAR_I_GRAVE                  363
#define CHAR_I_ACUTE                  364
#define CHAR_I_CIRCUMFLEX             365
#define CHAR_I_DIERESIS               366
#define CHAR_ETH                      367
#define CHAR_N_TILDE                  368
#define CHAR_O_GRAVE                  369
#define CHAR_O_ACUTE                  370
#define CHAR_O_CIRCUMFLEX             371
#define CHAR_O_TILDE                  372
#define CHAR_O_DIERESIS               373
#define CHAR_MULTIPLY                 374
#define CHAR_O_SLASH                  375
#define CHAR_U_GRAVE                  376
#define CHAR_U_ACUTE                  377
#define CHAR_U_CIRCUMFLEX             378
#define CHAR_U_DIERESIS               379
#define CHAR_Y_ACUTE                  380
#define CHAR_THORN                    381
#define CHAR_ESZETT                   382
#define CHAR_a_GRAVE                  383
#define CHAR_a_ACUTE                  384
#define CHAR_a_CIRCUMFLEX             385
#define CHAR_a_TILDE                  386
#define CHAR_a_DIERESIS               387
#define CHAR_a_OVERDOT                388
#define CHAR_ae                       389
#define CHAR_c_CEDILLA                390
#define CHAR_e_GRAVE                  391
#define CHAR_e_ACUTE                  392
#define CHAR_e_CIRCUMFLEX             393
#define CHAR_e_DIERESIS               394
#define CHAR_i_GRAVE                  395
#define CHAR_i_ACUTE                  396
#define CHAR_i_CIRCUMFLEX             397
#define CHAR_i_DIERESIS               398
#define CHAR_eth                      399
#define CHAR_n_TILDE                  400
#define CHAR_o_GRAVE                  401
#define CHAR_o_ACUTE                  402
#define CHAR_o_CIRCUMFLEX             403
#define CHAR_o_TILDE                  404
#define CHAR_o_DIERESIS               405
#define CHAR_DIVIDE                   406
#define CHAR_o_SLASH                  407
#define CHAR_u_GRAVE                  408
#define CHAR_u_ACUTE                  409
#define CHAR_u_CIRCUMFLEX             410
#define CHAR_u_DIERESIS               411
#define CHAR_y_ACUTE                  412
#define CHAR_thorn                    413
#define CHAR_y_DIERESIS               414
#define CHAR_OE                       415
#define CHAR_oe                       416
#define CHAR_S_CEDILLA                417
#define CHAR_s_CEDILLA                418
#define CHAR_a_SUPER                  419
#define CHAR_o_SUPER                  420
#define CHAR_er_SUPER                 421
#define CHAR_re_SUPER                 422
#define CHAR_r_SUPER                  423
#define CHAR_CURRENCY                 424 // "Poké Dollar" symbol in international versions
#define CHAR_EMARK_INVERTED           425
#define CHAR_QMARK_INVERTED           426
#define CHAR_EMARK                    427
#define CHAR_QMARK                    428
#define CHAR_COMMA                    429
#define CHAR_PERIOD                   430
#define CHAR_ELLIPSIS                 431
#define CHAR_DOT                      432
#define CHAR_SLASH                    433
#define CHAR_SINGLE_QUOTE_OPEN        434 // left single quote
#define CHAR_SINGLE_QUOTE_CLOSE       435 // right single quote (apostrophe)
#define CHAR_DOUBLE_QUOTE_OPEN        436 // left double quote
#define CHAR_DOUBLE_QUOTE_CLOSE       437 // right double quote
#define CHAR_DOUBLE_QUOTE_CLOSE_LOW   438
#define CHAR_ANGLE_QUOTE_OPEN         439
#define CHAR_ANGLE_QUOTE_CLOSE        440
#define CHAR_PARENTHESES_OPEN         441
#define CHAR_PARENTHESES_CLOSE        442
#define CHAR_MALE                     443
#define CHAR_FEMALE                   444
#define CHAR_PLUS                     445
#define CHAR_MINUS                    446
#define CHAR_ASTERISK                 447
#define CHAR_HASH                     448
#define CHAR_EQUALS                   449
#define CHAR_AMPERSAND                450
#define CHAR_TILDE                    451
#define CHAR_COLON                    452
#define CHAR_SEMICOLON                453
#define CHAR_SPADE_SUIT               454
#define CHAR_CLUB_SUIT                455
#define CHAR_HEART_SUIT               456
#define CHAR_DIAMOND_SUIT             457
#define CHAR_STAR                     458
#define CHAR_DOUBLE_CIRCLE            459
#define CHAR_CIRCLE                   460
#define CHAR_SQUARE                   461
#define CHAR_TRIANGLE                 462
#define CHAR_DIAMOND                  463
#define CHAR_AT_SIGN                  464
#define CHAR_MUSIC_NOTE               465
#define CHAR_PERCENT                  466
#define CHAR_SUN                      467
#define CHAR_CLOUD                    468
#define CHAR_UMBRELLA                 469
#define CHAR_SNOWMAN                  470
#define CHAR_EMOTE_SMILE              471
#define CHAR_EMOTE_LAUGH              472
#define CHAR_EMOTE_UPSET              473
#define CHAR_EMOTE_FROWN              474
#define CHAR_ARROW_CURVE_UP           475
#define CHAR_ARROW_CURVE_DOWN         476
#define CHAR_ZZZ                      477
#define CHAR_SPACE                    478
#define CHAR_e_SUPER                  479
#define CHAR_PK                       480
#define CHAR_MN                       481
#define CHAR_NUM_SPACE                482
#define CHAR_FILL_1PX                 483
#define CHAR_FILL_2PX                 484
#define CHAR_FILL_4PX                 485
#define CHAR_FILL_8PX                 486
#define CHAR_FILL_16PX                487
#define CHAR_DEGREE                   488
#define CHAR_UNDERSCORE               489
#define CHAR_UNDERSCORE_WIDE          490
#define CHAR_ONE_DOT                  491
#define CHAR_TWO_DOTS                 492
#define CHAR_LINE_BREAK               0xE000
#define CHAR_COMPRESSED_MARK          0xF100
#define CHAR_CONTROL_CODE_ARG         0xFFFE
#define CHAR_EOS                      0xFFFF // _EOM
#define TRNAME_MASK                   0x1FF
#define EOS_TRNAME                    0x1FF

#endif // POKEDIAMOND_CONSTANTS_CHARCODE_H
