#ifndef POKEDIAMOND_DECORATIONS_H
#define POKEDIAMOND_DECORATIONS_H

#define DECORATION_NONE                      0
#define DECORATION_DUMMY_1                   1
#define DECORATION_DUMMY_2                   2
#define DECORATION_DUMMY_3                   3
#define DECORATION_DUMMY_4                   4
#define DECORATION_DUMMY_5                   5
#define DECORATION_BIG_BOULDER               6
#define DECORATION_YELLOW_CUSHION            7
#define DECORATION_BLUE_CUSHION              8
#define DECORATION_WOODEN_CHAIR              9
#define DECORATION_BIG_TABLE                10
#define DECORATION_PLAIN_TABLE              11
#define DECORATION_SMALL_TABLE              12
#define DECORATION_LONG_TABLE               13
#define DECORATION_WIDE_TABLE               14
#define DECORATION_POKE_TABLE               15
#define DECORATION_BIG_BOOKSHELF            16
#define DECORATION_SMALL_BOOKSHELF          17
#define DECORATION_RESEARCH_SHELF           18
#define DECORATION_BIKE_RACK                19
#define DECORATION_SHOP_SHELF               20
#define DECORATION_DISPLAY_SHELF            21
#define DECORATION_CUPBOARD                 22
#define DECORATION_WOOD_DRESSER             23
#define DECORATION_PINK_DRESSER             24
#define DECORATION_TV                       25
#define DECORATION_REFRIGERATOR             26
#define DECORATION_PRETTY_SINK              27
#define DECORATION_FEATHERY_BED             28
#define DECORATION_TRASH_CAN                29
#define DECORATION_CARDBOARD_BOX            30
#define DECORATION_CRATE                    31
#define DECORATION_CONTAINER                32
#define DECORATION_OIL_DRUM                 33
#define DECORATION_BIG_OIL_DRUM             34
#define DECORATION_IRON_BEAM                35
#define DECORATION_POTTED_PLANT             36
#define DECORATION_POKE_FLOWER              37
#define DECORATION_HEALING_MACHINE          38
#define DECORATION_LAB_MACHINE              39
#define DECORATION_TEST_MACHINE             40
#define DECORATION_GAME_SYSTEM              41
#define DECORATION_VENDING_MACHINE          42
#define DECORATION_RED_BIKE                 43
#define DECORATION_GREEN_BIKE               44
#define DECORATION_BINOCULARS               45
#define DECORATION_GLOBE                    46
#define DECORATION_GYM_STATUE               47
#define DECORATION_RED_TENT                 48
#define DECORATION_BLUE_TENT                49
#define DECORATION_CLEAR_TENT               50
#define DECORATION_MAZE_BLOCK_1             51
#define DECORATION_MAZE_BLOCK_2             52
#define DECORATION_MAZE_BLOCK_3             53
#define DECORATION_MAZE_BLOCK_4             54
#define DECORATION_MAZE_BLOCK_5             55
#define DECORATION_HOLE_TOOL                56
#define DECORATION_PIT_TOOL                 57
#define DECORATION_SMOKE_TOOL               58
#define DECORATION_BIG_SMOKE_TOOL           59
#define DECORATION_ROCK_TOOL                60
#define DECORATION_ROCKFALL_TOOL            61
#define DECORATION_FOAM_TOOL                62
#define DECORATION_BUBBLE_TOOL              63
#define DECORATION_ALERT_TOOL_1             64
#define DECORATION_ALERT_TOOL_2             65
#define DECORATION_ALERT_TOOL_3             66
#define DECORATION_ALERT_TOOL_4             67
#define DECORATION_LEAF_TOOL                68
#define DECORATION_FLOWER_TOOL              69
#define DECORATION_EMBER_TOOL               70
#define DECORATION_FIRE_TOOL                71
#define DECORATION_CUTE_CUP                 72
#define DECORATION_COOL_CUP                 73
#define DECORATION_BEAUTY_CUP               74
#define DECORATION_TOUGH_CUP                75
#define DECORATION_CLEVER_CUP               76
#define DECORATION_BLUE_CRYSTAL             77
#define DECORATION_PINK_CRYSTAL             78
#define DECORATION_RED_CRYSTAL              79
#define DECORATION_YELLOW_CRYSTAL           80
#define DECORATION_PRETTY_GEM               81
#define DECORATION_SHINY_GEM                82
#define DECORATION_MYSTIC_GEM               83
#define DECORATION_GLITTER_GEM              84
#define DECORATION_BRONZE_TROPHY            85
#define DECORATION_SILVER_TROPHY            86
#define DECORATION_GOLD_TROPHY              87
#define DECORATION_GREAT_TROPHY             88
#define DECORATION_BALL_ORNAMENT            89
#define DECORATION_ROUND_ORNAMENT           90
#define DECORATION_CLEAR_ORNAMENT           91
#define DECORATION_CHARMANDER_DOLL          92
#define DECORATION_BULBASAUR_DOLL           93
#define DECORATION_SQUIRTLE_DOLL            94
#define DECORATION_CYNDAQUIL_DOLL           95
#define DECORATION_CHIKORITA_DOLL           96
#define DECORATION_TOTODILE_DOLL            97
#define DECORATION_TORCHIC_DOLL             98
#define DECORATION_TREECKO_DOLL             99
#define DECORATION_MUDKIP_DOLL             100
#define DECORATION_CHIMCHAR_DOLL           101
#define DECORATION_TURTWIG_DOLL            102
#define DECORATION_PIPLUP_DOLL             103
#define DECORATION_PIKACHU_DOLL            104
#define DECORATION_PLUSLE_DOLL             105
#define DECORATION_MINUN_DOLL              106
#define DECORATION_CLEFAIRY_DOLL           107
#define DECORATION_JIGGLYPUFF_DOLL         108
#define DECORATION_WOBBUFFET_DOLL          109
#define DECORATION_MEOWTH_DOLL             110
#define DECORATION_SKITTY_DOLL             111
#define DECORATION_GLAMEOW_DOLL            112
#define DECORATION_BUNEARY_DOLL            113
#define DECORATION_WEAVILE_DOLL            114
#define DECORATION_MUNCHLAX_DOLL           115
#define DECORATION_BONSLY_DOLL             116
#define DECORATION_MIME_JR__DOLL           117
#define DECORATION_LUCARIO_DOLL            118
#define DECORATION_MANTYKE_DOLL            119
#define DECORATION_BUIZEL_DOLL             120
#define DECORATION_CHATOT_DOLL             121
#define DECORATION_MANAPHY_DOLL            122
#define DECORATION_SNORLAX_DOLL            123
#define DECORATION_WAILORD_DOLL            124
#define DECORATION_MAGNEZONE_DOLL          125
#define DECORATION_DRIFLOON_DOLL           126
#define DECORATION_HAPPINY_DOLL            127
#define DECORATION_PACHIRISU_DOLL          128
#define DECORATION_129                     129
#define DECORATION_130                     130
#define DECORATION_131                     131
#define DECORATION_132                     132
#define DECORATION_WIDE_SOFA               133
#define DECORATION_BONSAI                  134
#define DECORATION_DAINTY_FLOWERS          135
#define DECORATION_LOVELY_FLOWERS          136
#define DECORATION_PRETTY_FLOWERS          137
#define DECORATION_LAVISH_FLOWERS          138

#endif //POKEDIAMOND_DECORATIONS_H
