#ifndef POKEDIAMOND_CONSTANTS_FIELD_MOVE_RESPONSE_H
#define POKEDIAMOND_CONSTANTS_FIELD_MOVE_RESPONSE_H

#define FIELD_MOVE_RESPONSE_OK              0
#define FIELD_MOVE_RESPONSE_NOT_HERE        1
#define FIELD_MOVE_RESPONSE_NEED_BADGE      2
#define FIELD_MOVE_RESPONSE_HAVE_FOLLOWER   3
#define FIELD_MOVE_RESPONSE_ALREADY_SURFING 4
#define FIELD_MOVE_RESPONSE_NOT_NOW         5

#endif // POKEDIAMOND_CONSTANTS_FIELD_MOVE_RESPONSE_H
