#ifndef POKEDIAMOND_CONSTANTS_FLAGS_H
#define POKEDIAMOND_CONSTANTS_FLAGS_H

#define FLAG_SYS_SAFARI 0x967

#define NUM_FLAGS 2912

#define NUM_TEMP_FLAGS 64
#define TEMP_FLAG_BASE 0x4000

#endif // POKEDIAMOND_CONSTANTS_FLAGS_H
