#ifndef POKEDIAMOND_CONSTANTS_GAME_STATS_H
#define POKEDIAMOND_CONSTANTS_GAME_STATS_H

#define GAME_STAT_UNK7             7
#define GAME_STAT_UNK21           21

#endif //POKEDIAMOND_CONSTANTS_GAME_STATS_H