#ifndef POKEDIAMOND_CONSTANTS_GAME_STATS_H
#define POKEDIAMOND_CONSTANTS_GAME_STATS_H

#define GAME_STAT_UNK7  7
#define GAME_STAT_UNK8  8
#define GAME_STAT_UNK9  9
#define GAME_STAT_UNK10 10
#define GAME_STAT_UNK11 11
#define GAME_STAT_UNK21 21

#endif // POKEDIAMOND_CONSTANTS_GAME_STATS_H
