#ifndef POKEDIAMOND_CONSTANTS_GLOBAL_H
#define POKEDIAMOND_CONSTANTS_GLOBAL_H

#include "constants/charcode.h"

#define POKEMON_NAME_LENGTH      10
#define PLAYER_NAME_LENGTH       7

#endif //POKEDIAMOND_CONSTANTS_GLOBAL_H
