#ifndef POKEDIAMOND_CONSTANTS_GLOBAL_FIELDMAP_H
#define POKEDIAMOND_CONSTANTS_GLOBAL_FIELDMAP_H

// Facing direction
#define DIR_NORTH        0
#define DIR_SOUTH        1
#define DIR_WEST         2
#define DIR_EAST         3

#endif //POKEDIAMOND_CONSTANTS_GLOBAL_FIELDMAP_H
