#ifndef POKEDIAMOND_CONSTANTS_GLOBAL_FIELDMAP_H
#define POKEDIAMOND_CONSTANTS_GLOBAL_FIELDMAP_H

// Facing direction
#define DIR_NORTH 0
#define DIR_SOUTH 1
#define DIR_WEST  2
#define DIR_EAST  3

// Player avatar state
#define PLAYER_STATE_WALKING 0
#define PLAYER_STATE_CYCLING 1
#define PLAYER_STATE_SURFING 2
#define PLAYER_STATE_UNK_SP  3

// Player transition bits
#define PLAYER_TRANSITION_WALKING 1 << 0
#define PLAYER_TRANSITION_CYCLING 1 << 1
#define PLAYER_TRANSITION_SURFING 1 << 2

#endif // POKEDIAMOND_CONSTANTS_GLOBAL_FIELDMAP_H
