#ifndef POKEDIAMOND_CONSTANTS_GLOBAL_FIELDMAP_H
#define POKEDIAMOND_CONSTANTS_GLOBAL_FIELDMAP_H

// Facing direction
#define DIR_NORTH 0
#define DIR_SOUTH 1
#define DIR_WEST  2
#define DIR_EAST  3

// Player avatar state
#define PLAYER_STATE_WALKING  0
#define PLAYER_STATE_CYCLING  1
#define PLAYER_STATE_SURFING  2
#define PLAYER_STATE_USE_HM   3
#define PLAYER_STATE_WATERING 4
#define PLAYER_STATE_CONTEST  5
#define PLAYER_STATE_FISHING  6
#define PLAYER_STATE_POKETCH  7
#define PLAYER_STATE_SAVING   8
#define PLAYER_STATE_HEAL     9

// Player transition bits
#define PLAYER_TRANSITION_WALKING  1 << 0
#define PLAYER_TRANSITION_CYCLING  1 << 1
#define PLAYER_TRANSITION_SURFING  1 << 2
#define PLAYER_TRANSITION_x0008    1 << 3
#define PLAYER_TRANSITION_WATERING 1 << 4
#define PLAYER_TRANSITION_FISHING  1 << 5
#define PLAYER_TRANSITION_POKETCH  1 << 6
#define PLAYER_TRANSITION_SAVING   1 << 7
#define PLAYER_TRANSITION_HEAL     1 << 8

#endif // POKEDIAMOND_CONSTANTS_GLOBAL_FIELDMAP_H
