#ifndef POKEDIAMOND_CONSTANTS_RIBBONS_H
#define POKEDIAMOND_CONSTANTS_RIBBONS_H

#define RIBBON_HOENN_CHAMPION      0
#define RIBBON_HOENN_COOL          1
#define RIBBON_HOENN_COOL_SUPER    2
#define RIBBON_HOENN_COOL_HYPER    3
#define RIBBON_HOENN_COOL_MASTER   4
#define RIBBON_HOENN_BEAUTY        5
#define RIBBON_HOENN_BEAUTY_SUPER  6
#define RIBBON_HOENN_BEAUTY_HYPER  7
#define RIBBON_HOENN_BEAUTY_MASTER 8
#define RIBBON_HOENN_CUTE          9
#define RIBBON_HOENN_CUTE_SUPER    10
#define RIBBON_HOENN_CUTE_HYPER    11
#define RIBBON_HOENN_CUTE_MASTER   12
#define RIBBON_HOENN_SMART         13
#define RIBBON_HOENN_SMART_SUPER   14
#define RIBBON_HOENN_SMART_HYPER   15
#define RIBBON_HOENN_SMART_MASTER  16
#define RIBBON_HOENN_TOUGH         17
#define RIBBON_HOENN_TOUGH_SUPER   18
#define RIBBON_HOENN_TOUGH_HYPER   19
#define RIBBON_HOENN_TOUGH_MASTER  20
#define RIBBON_HOENN_WINNING       21
#define RIBBON_HOENN_VICTORY       22
#define RIBBON_HOENN_ARTIST        23
#define RIBBON_HOENN_EFFORT        24
#define RIBBON_HOENN_MARINE        25
#define RIBBON_HOENN_LAND          26
#define RIBBON_HOENN_SKY           27
#define RIBBON_HOENN_COUNTRY       28
#define RIBBON_HOENN_NATIONAL      29
#define RIBBON_HOENN_EARTH         30
#define RIBBON_HOENN_WORLD         31
#define RIBBON_SINNOH_CHAMP        32
#define RIBBON_COOL                33
#define RIBBON_COOL_GREAT          34
#define RIBBON_COOL_ULTRA          35
#define RIBBON_COOL_MASTER         36
#define RIBBON_BEAUTY              37
#define RIBBON_BEAUTY_GREAT        38
#define RIBBON_BEAUTY_ULTRA        39
#define RIBBON_BEAUTY_MASTER       40
#define RIBBON_CUTE                41
#define RIBBON_CUTE_GREAT          42
#define RIBBON_CUTE_ULTRA          43
#define RIBBON_CUTE_MASTER         44
#define RIBBON_SMART               45
#define RIBBON_SMART_GREAT         46
#define RIBBON_SMART_ULTRA         47
#define RIBBON_SMART_MASTER        48
#define RIBBON_TOUGH               49
#define RIBBON_TOUGH_GREAT         50
#define RIBBON_TOUGH_ULTRA         51
#define RIBBON_TOUGH_MASTER        52
#define RIBBON_ABILITY             53
#define RIBBON_GREAT_ABILITY       54
#define RIBBON_DOUBLE_ABILITY      55
#define RIBBON_MULTI_ABILITY       56
#define RIBBON_PAIR_ABILITY        57
#define RIBBON_WORLD_ABILITY       58
#define RIBBON_ALERT               59
#define RIBBON_SHOCK               60
#define RIBBON_DOWNCAST            61
#define RIBBON_CARELESS            62
#define RIBBON_RELAX               63
#define RIBBON_SNOOZE              64
#define RIBBON_SMILE               65
#define RIBBON_GORGEOUS            66
#define RIBBON_ROYAL               67
#define RIBBON_GORGEOUS_ROYAL      68
#define RIBBON_FOOTPRINT           69
#define RIBBON_RECORD              70
#define RIBBON_HISTORY             71
#define RIBBON_LEGEND              72
#define RIBBON_RED                 73
#define RIBBON_GREEN               74
#define RIBBON_BLUE                75
#define RIBBON_FESTIVAL            76
#define RIBBON_CARNIVAL            77
#define RIBBON_CLASSIC             78
#define RIBBON_PREMIER             79

#endif // POKEDIAMOND_CONSTATNS_RIBBONS_H
