#ifndef POKEDIAMOND_SCRIPT_POKEMON_UTIL_H
#define POKEDIAMOND_SCRIPT_POKEMON_UTIL_H

#define FLDPSN_NONE  0
#define FLDPSN_PSN   1
#define FLDPSN_HEAL  2

#endif //POKEDIAMOND_SCRIPT_POKEMON_UTIL_H
