#ifndef POKEDIAMOND_CONSTANTS_SEAL_CONSTANTS_H
#define POKEDIAMOND_CONSTANTS_SEAL_CONSTANTS_H

// The different kinds of seals you can have
#define SEAL_NONE              0
#define SEAL_HEART_A           1
#define SEAL_HEART_B           2
#define SEAL_HEART_C           3
#define SEAL_HEART_D           4
#define SEAL_HEART_E           5
#define SEAL_HEART_F           6
#define SEAL_STAR_A            7
#define SEAL_STAR_B            8
#define SEAL_STAR_C            9
#define SEAL_STAR_D           10
#define SEAL_STAR_E           11
#define SEAL_STAR_F           12
#define SEAL_LINE_A           13
#define SEAL_LINE_B           14
#define SEAL_LINE_C           15
#define SEAL_SMOKE_A          16
#define SEAL_SMOKE_B          17
#define SEAL_SMOKE_C          18
#define SEAL_SMOKE_D          19
#define SEAL_ELE_A            20
#define SEAL_ELE_B            21
#define SEAL_ELE_C            22
#define SEAL_ELE_D            23
#define SEAL_FOAMY_A          24
#define SEAL_FOAMY_B          25
#define SEAL_FOAMY_C          26
#define SEAL_FOAMY_D          27
#define SEAL_FIRE_A           28
#define SEAL_FIRE_B           29
#define SEAL_FIRE_C           30
#define SEAL_FIRE_D           31
#define SEAL_PARTY_A          32
#define SEAL_PARTY_B          33
#define SEAL_PARTY_C          34
#define SEAL_PARTY_D          35
#define SEAL_FLORA_A          36
#define SEAL_FLORA_B          37
#define SEAL_FLORA_C          38
#define SEAL_FLORA_D          39
#define SEAL_FLORA_E          40
#define SEAL_FLORA_F          41
#define SEAL_SONG_A           42
#define SEAL_SONG_B           43
#define SEAL_SONG_C           44
#define SEAL_SONG_D           45
#define SEAL_SONG_E           46
#define SEAL_SONG_F           47
#define SEAL_SONG_G           48
#define SEAL_A                49
#define SEAL_B                50
#define SEAL_C                51
#define SEAL_D                52
#define SEAL_E                53
#define SEAL_F                54
#define SEAL_G                55
#define SEAL_H                56
#define SEAL_I                57
#define SEAL_J                58
#define SEAL_K                59
#define SEAL_L                60
#define SEAL_M                61
#define SEAL_N                62
#define SEAL_O                63
#define SEAL_P                64
#define SEAL_Q                65
#define SEAL_R                66
#define SEAL_S                67
#define SEAL_T                68
#define SEAL_U                69
#define SEAL_V                70
#define SEAL_W                71
#define SEAL_X                72
#define SEAL_Y                73
#define SEAL_Z                74
#define SEAL_SHOCK            75
#define SEAL_MYSTERY          76
#define SEAL_LINE_D           77
#define SEAL_LIQUID           78
#define SEAL_BURST            79
#define SEAL_TWINKLE          80

#endif //POKEDIAMOND_CONSTANTS_SEAL_CONSTANTS_H
