#ifndef POKEDIAMOND_CONSTANTS_SPRITES_H
#define POKEDIAMOND_CONSTANTS_SPRITES_H

#define SPRITE_ROCK      84
#define SPRITE_BREAKROCK 85
#define SPRITE_TREE      86

#define SPRITE_CAMERA_FOCUS 8192

#endif // POKEDIAMOND_CONSTANTS_SPRITES_H
