#ifndef POKEDIAMOND_CONSTANTS_TRAINERS_H
#define POKEDIAMOND_CONSTANTS_TRAINERS_H

#define TRAINER_YOUNGSTER_TRISTAN              1
#define TRAINER_YOUNGSTER_LOGAN                2
#define TRAINER_LASS_NATALIE                   3
#define TRAINER_YOUNGSTER_MICHAEL              4
#define TRAINER_CAMPER_MICKEY                  5
#define TRAINER_CAMPER_MICKEY_2                6
#define TRAINER_PICNICKER_ANGELICA             7
#define TRAINER_PICNICKER_ANGELICA_2           8
#define TRAINER_YOUNGSTER_MICKEY               9
#define TRAINER_YOUNGSTER_TYLER                10
#define TRAINER_LASS_SAMANTHA                  11
#define TRAINER_LASS_SARAH                     12
#define TRAINER_BUG_CATCHER_BRANDON            13
#define TRAINER_AROMA_LADY_TAYLOR              14
#define TRAINER_TWINS_LIV_LIZ                  15
#define TRAINER_CAMPER_JACOB                   16
#define TRAINER_PICNICKER_SIENA                17
#define TRAINER_HIKER_DANIEL                   18
#define TRAINER_HIKER_NICHOLAS                 19
#define TRAINER_BATTLE_GIRL_KELSEY             20
#define TRAINER_AROMA_LADY_ELIZABETH           21
#define TRAINER_FISHERMAN_ANDREW               22
#define TRAINER_FISHERMAN_JOSEPH               23
#define TRAINER_FISHERMAN_ZACHARY              24
#define TRAINER_CYCLIST_M_AXEL                 25
#define TRAINER_CYCLIST_M_JAMES                26
#define TRAINER_CYCLIST_M_JOHN                 27
#define TRAINER_CYCLIST_M_RYAN                 28
#define TRAINER_CYCLIST_F_MEGAN                29
#define TRAINER_CYCLIST_F_NICOLE               30
#define TRAINER_CYCLIST_F_KAYLA                31
#define TRAINER_CYCLIST_F_RACHEL               32
#define TRAINER_YOUNGSTER_AUSTIN               33
#define TRAINER_CAMPER_ANTHONY                 34
#define TRAINER_PICNICKER_LAUREN               35
#define TRAINER_HIKER_KEVIN                    36
#define TRAINER_HIKER_JUSTIN                   37
#define TRAINER_BATTLE_GIRL_HELEN              38
#define TRAINER_HIKER_ROBERT                   39
#define TRAINER_HIKER_ALEXANDER                40
#define TRAINER_HIKER_JONATHAN                 41
#define TRAINER_BLACK_BELT_KYLE                42
#define TRAINER_FISHERMAN_CODY                 43
#define TRAINER_AROMA_LADY_HANNAH              44
#define TRAINER_ARTIST_WILLIAM                 45
#define TRAINER_PKMN_BREEDER_M_ALBERT          46
#define TRAINER_PKMN_BREEDER_F_JENNIFER        47
#define TRAINER_COWGIRL_SHELLEY                48
#define TRAINER_JOGGER_RICHARD                 49
#define TRAINER_POKEFAN_M_MICKEY               50
#define TRAINER_POKEFAN_F_ANGELICA             51
#define TRAINER_YOUNGSTER_MICKEY_2             52
#define TRAINER_POKE_KID_DANIELLE              53
#define TRAINER_FISHERMAN_MICKEY               54
#define TRAINER_YOUNG_COUPLE_TY_SUE            55
#define TRAINER_PKMN_BREEDER_M_KAHLIL          56
#define TRAINER_PKMN_BREEDER_F_AMBER           57
#define TRAINER_COWGIRL_ANGELICA               58
#define TRAINER_JOGGER_MICKEY                  59
#define TRAINER_POKEFAN_M_MICKEY_2             60
#define TRAINER_POKEFAN_F_ANGELICA_2           61
#define TRAINER_ACE_TRAINER_M_MICKEY           62
#define TRAINER_ACE_TRAINER_F_ANGELICA         63
#define TRAINER_WAITRESS_ANGELICA              64
#define TRAINER_TWINS_TERI_TIA                 65
#define TRAINER_ACE_TRAINER_M_ERNEST           66
#define TRAINER_ACE_TRAINER_F_ALYSSA           67
#define TRAINER_VETERAN_BRIAN                  68
#define TRAINER_BLACK_BELT_ADAM                69
#define TRAINER_NINJA_BOY_JOEL                 70
#define TRAINER_NINJA_BOY_NATHAN               71
#define TRAINER_NINJA_BOY_DAVIDO               72
#define TRAINER_DRAGON_TAMER_PATRICK           73
#define TRAINER_BIRD_KEEPER_BRIANNA            74
#define TRAINER_DOUBLE_TEAM_ZAC_JEN            75
#define TRAINER_BIRD_KEEPER_ALEXANDRA          76
#define TRAINER_BATTLE_GIRL_ANGELICA           77
#define TRAINER_NINJA_BOY_ZACH                 78
#define TRAINER_BLACK_BELT_SEAN                79
#define TRAINER_NINJA_BOY_NICK                 80
#define TRAINER_BIRD_KEEPER_KATHERINE          81
#define TRAINER_RICH_BOY_JASON                 82
#define TRAINER_LADY_MELISSA                   83
#define TRAINER_GENTLEMAN_JEREMY               84
#define TRAINER_SOCIALITE_REINA                85
#define TRAINER_BEAUTY_ANGELICA                86
#define TRAINER_COLLECTOR_MICKEY               87
#define TRAINER_POLICEMAN_BOBBY                88
#define TRAINER_POLICEMAN_ALEX                 89
#define TRAINER_POLICEMAN_DYLAN                90
#define TRAINER_FISHERMAN_JUAN                 91
#define TRAINER_FISHERMAN_CAMERON              92
#define TRAINER_FISHERMAN_TRAVIS               93
#define TRAINER_PKMN_RANGER_M_TAYLOR           94
#define TRAINER_PKMN_RANGER_M_JEFFREY          95
#define TRAINER_PKMN_RANGER_F_ALLISON          96
#define TRAINER_PKMN_RANGER_F_ANGELICA         97
#define TRAINER_SCIENTIST_MICKEY               98
#define TRAINER_SCIENTIST_STEFANO              99
#define TRAINER_YOUNGSTER_MICKEY_3             100
#define TRAINER_YOUNGSTER_MICKEY_4             101
#define TRAINER_POLICEMAN_CALEB                102
#define TRAINER_SWIMMER_M_SHELTIN              103
#define TRAINER_SWIMMER_M_EVAN                 104
#define TRAINER_SWIMMER_F_HALEY                105
#define TRAINER_SWIMMER_F_MARY                 106
#define TRAINER_TUBER_M_JARED                  107
#define TRAINER_TUBER_F_CHELSEA                108
#define TRAINER_BATTLE_GIRL_ANGELICA_2         109
#define TRAINER_SAILOR_PAUL                    110
#define TRAINER_FISHERMAN_KENNETH              111
#define TRAINER_SIS_AND_BRO_TARA_TIM           112
#define TRAINER_RUIN_MANIAC_BRYAN              113
#define TRAINER_RUIN_MANIAC_HUNTER             114
#define TRAINER_HIKER_MICKEY                   115
#define TRAINER_VETERAN_MICKEY                 116
#define TRAINER_CAMPER_MICKEY_3                117
#define TRAINER_PICNICKER_ANGELICA_3           118
#define TRAINER_PSYCHIC_M_MITCHELL             119
#define TRAINER_PSYCHIC_F_ABIGAIL              120
#define TRAINER_PI_CARLOS                      121
#define TRAINER_GUITARIST_MICKEY               122
#define TRAINER_PI_MICKEY                      123
#define TRAINER_BEAUTY_ANGELICA_2              124
#define TRAINER_BEAUTY_ANGELICA_3              125
#define TRAINER_BLACK_BELT_MICKEY              126
#define TRAINER_BLACK_BELT_GREGORY             127
#define TRAINER_BLACK_BELT_DEREK               128
#define TRAINER_BLACK_BELT_NATHANIEL           129
#define TRAINER_JOGGER_SCOTT                   130
#define TRAINER_BIRD_KEEPER_ANGELICA           131
#define TRAINER_ACE_TRAINER_SNOW_M_BLAKE       132
#define TRAINER_ACE_TRAINER_SNOW_M_GARRETT     133
#define TRAINER_ACE_TRAINER_SNOW_F_LAURA       134
#define TRAINER_ACE_TRAINER_SNOW_F_MARIA       135
#define TRAINER_SKIER_M_BRADLEY                136
#define TRAINER_SKIER_M_EDWARD                 137
#define TRAINER_SKIER_F_KAITLYN                138
#define TRAINER_SKIER_F_ANDREA                 139
#define TRAINER_ACE_TRAINER_SNOW_M_DALTON      140
#define TRAINER_ACE_TRAINER_SNOW_F_OLIVIA      141
#define TRAINER_SKIER_M_SHAWN                  142
#define TRAINER_SKIER_M_BJORN                  143
#define TRAINER_SKIER_F_LEXIE                  144
#define TRAINER_SKIER_F_MADISON                145
#define TRAINER_NINJA_BOY_ANTONIO              146
#define TRAINER_NINJA_BOY_ETHAN                147
#define TRAINER_BLACK_BELT_LUKE                148
#define TRAINER_SWIMMER_M_MICKEY               149
#define TRAINER_SWIMMER_M_MICKEY_2             150
#define TRAINER_SWIMMER_F_ANGELICA             151
#define TRAINER_SWIMMER_F_ANGELICA_2           152
#define TRAINER_FISHERMAN_MIGUEL               153
#define TRAINER_FISHERMAN_LUC                  154
#define TRAINER_SIS_AND_BRO_TARA_TIM_2         155
#define TRAINER_SWIMMER_M_MICKEY_3             156
#define TRAINER_SWIMMER_M_MICKEY_4             157
#define TRAINER_SWIMMER_F_ANGELICA_3           158
#define TRAINER_SWIMMER_M_ADRIAN               159
#define TRAINER_SWIMMER_M_ERIK                 160
#define TRAINER_SWIMMER_M_VINCENT              161
#define TRAINER_SWIMMER_F_JESSICA              162
#define TRAINER_SWIMMER_F_ERICA                163
#define TRAINER_SWIMMER_F_KATELYN              164
#define TRAINER_SIS_AND_BRO_TARA_TIM_3         165
#define TRAINER_SWIMMER_M_DILLON               166
#define TRAINER_SWIMMER_F_VANESSA              167
#define TRAINER_FISHERMAN_CORY                 168
#define TRAINER_RUIN_MANIAC_MICKEY             169
#define TRAINER_ACE_TRAINER_M_JAKE             170
#define TRAINER_ACE_TRAINER_F_SHANNON          171
#define TRAINER_FISHERMAN_BRETT                172
#define TRAINER_FISHERMAN_ALEC                 173
#define TRAINER_FISHERMAN_GEORGE               174
#define TRAINER_FISHERMAN_COLE                 175
#define TRAINER_ROUGHNECK_MICKEY               176
#define TRAINER_ROUGHNECK_MICKEY_2             177
#define TRAINER_GUITARIST_MICKEY_2             178
#define TRAINER_CLOWN_MICKEY                   179
#define TRAINER_SAILOR_LUTHER                  180
#define TRAINER_ARTIST_MICKEY                  181
#define TRAINER_YOUNG_COUPLE_TARA_TIM          182
#define TRAINER_SWIMMER_M_WESLEY               183
#define TRAINER_SWIMMER_M_RICARDO              184
#define TRAINER_SWIMMER_M_FRANCISCO            185
#define TRAINER_SWIMMER_M_COLTON               186
#define TRAINER_SWIMMER_M_TROY                 187
#define TRAINER_SWIMMER_M_OSCAR                188
#define TRAINER_SWIMMER_F_MIRANDA              189
#define TRAINER_SWIMMER_F_AUBREE               190
#define TRAINER_SWIMMER_F_PAIGE                191
#define TRAINER_SWIMMER_F_CRYSTAL              192
#define TRAINER_SWIMMER_F_CASSANDRA            193
#define TRAINER_SWIMMER_F_GABRIELLE            194
#define TRAINER_WORKER_COLIN                   195
#define TRAINER_WORKER_MASON                   196
#define TRAINER_WORKER_MICKEY                  197
#define TRAINER_SCIENTIST_MICKEY_2             198
#define TRAINER_SCIENTIST_MICKEY_3             199
#define TRAINER_SCIENTIST_MICKEY_4             200
#define TRAINER_BUG_CATCHER_JACK               201
#define TRAINER_BUG_CATCHER_PHILLIP            202
#define TRAINER_BUG_CATCHER_DONALD             203
#define TRAINER_LASS_BRIANA                    204
#define TRAINER_PSYCHIC_M_ELIJAH               205
#define TRAINER_PSYCHIC_F_LINDSEY              206
#define TRAINER_YOUNG_COUPLE_TARA_TIM_2        207
#define TRAINER_WORKER_MICKEY_2                208
#define TRAINER_WORKER_MICKEY_3                209
#define TRAINER_WORKER_MICKEY_4                210
#define TRAINER_ACE_TRAINER_SNOW_M_MICKEY      211
#define TRAINER_ACE_TRAINER_SNOW_M_MICKEY_2    212
#define TRAINER_ACE_TRAINER_SNOW_F_ANGELICA    213
#define TRAINER_ACE_TRAINER_SNOW_F_ANGELICA_2  214
#define TRAINER_VETERAN_MICKEY_2               215
#define TRAINER_VETERAN_MICKEY_3               216
#define TRAINER_PSYCHIC_M_MICKEY               217
#define TRAINER_PSYCHIC_F_ANGELICA             218
#define TRAINER_DRAGON_TAMER_MICKEY            219
#define TRAINER_SAILOR_MICKEY                  220
#define TRAINER_SCHOOL_KID_M_MICKEY            221
#define TRAINER_SCHOOL_KID_F_ANGELICA          222
#define TRAINER_YOUNG_COUPLE_TARA_TIM_3        223
#define TRAINER_ACE_TRAINER_M_OMAR             224
#define TRAINER_ACE_TRAINER_M_HENRY            225
#define TRAINER_ACE_TRAINER_F_MARIAH           226
#define TRAINER_ACE_TRAINER_F_SYDNEY           227
#define TRAINER_VETERAN_EDGAR                  228
#define TRAINER_VETERAN_CLAYTON                229
#define TRAINER_DRAGON_TAMER_ONDREJ            230
#define TRAINER_DRAGON_TAMER_CLINTON           231
#define TRAINER_BLACK_BELT_DAVID               232
#define TRAINER_BIRD_KEEPER_HANA               233
#define TRAINER_PSYCHIC_M_BRYCE                234
#define TRAINER_PSYCHIC_F_VALENCIA             235
#define TRAINER_DOUBLE_TEAM_JO_PAT             236
#define TRAINER_DOUBLE_TEAM_AL_KAY             237
#define TRAINER_YOUNGSTER_MICKEY_5             238
#define TRAINER_LASS_ANGELICA                  239
#define TRAINER_VETERAN_GRANT                  240
#define TRAINER_FISHERMAN_MICKEY_2             241
#define TRAINER_SAILOR_MICKEY_2                242
#define TRAINER_BEAUTY_ANGELICA_4              243
#define TRAINER_YOUNGSTER_JONATHON             244
#define TRAINER_YOUNGSTER_DARIUS               245
#define TRAINER_LEADER_ROARK_ROARK             246
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC      247
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_2    248
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_3    249
#define TRAINER_LEADER_BYRON_BYRON             250
#define TRAINER_ACE_TRAINER_F_ANGELICA_2       251
#define TRAINER_CAMPER_MICKEY_4                252
#define TRAINER_CAMPER_MICKEY_5                253
#define TRAINER_CAMPER_MICKEY_6                254
#define TRAINER_CAMPER_MICKEY_7                255
#define TRAINER_WORKER_JACKSON                 256
#define TRAINER_WORKER_GARY                    257
#define TRAINER_BLACK_BELT_PHILIP              258
#define TRAINER_AROMA_LADY_JENNA               259
#define TRAINER_AROMA_LADY_ANGELA              260
#define TRAINER_ELITE_FOUR_AARON_AARON         261
#define TRAINER_ELITE_FOUR_BERTHA_BERTHA       262
#define TRAINER_ELITE_FOUR_FLINT_FLINT         263
#define TRAINER_ELITE_FOUR_LUCIEN_LUCIAN       264
#define TRAINER_CAMPER_CURTIS                  265
#define TRAINER_CAMPER_DREW                    266
#define TRAINER_CHAMPION_CYNTHIA               267
#define TRAINER_ACE_TRAINER_SNOW_M_SERGIO      268
#define TRAINER_ACE_TRAINER_SNOW_M_ISAIAH      269
#define TRAINER_ACE_TRAINER_SNOW_F_SAVANNAH    270
#define TRAINER_ACE_TRAINER_SNOW_F_ALICIA      271
#define TRAINER_COLLECTOR_DOUGLAS              272
#define TRAINER_COLLECTOR_BRADY                273
#define TRAINER_COLLECTOR_IVAN                 274
#define TRAINER_COLLECTOR_FERNANDO             275
#define TRAINER_COLLECTOR_EDWIN                276
#define TRAINER_DRAGON_TAMER_HAYDEN            277
#define TRAINER_ACE_TRAINER_M_DENNIS           278
#define TRAINER_ACE_TRAINER_M_CESAR            279
#define TRAINER_ACE_TRAINER_M_ALLEN            280
#define TRAINER_ACE_TRAINER_M_ZACHERY          281
#define TRAINER_ACE_TRAINER_M_RUBEN            282
#define TRAINER_ACE_TRAINER_F_BREANNA          283
#define TRAINER_ACE_TRAINER_F_CATHERINE        284
#define TRAINER_ACE_TRAINER_F_DESTINY          285
#define TRAINER_ACE_TRAINER_F_JAMIE            286
#define TRAINER_ACE_TRAINER_F_MAYA             287
#define TRAINER_PSYCHIC_M_MAXWELL              288
#define TRAINER_PSYCHIC_F_BRITTNEY             289
#define TRAINER_BELLE__PA_AVA_MATT             290
#define TRAINER_RANCHER_MICKEY                 291
#define TRAINER_RANCHER_MARCO                  292
#define TRAINER_FISHERMAN_ERICK                293
#define TRAINER_TWINS_EMMA_LIL                 294
#define TRAINER_COMMANDER_MARS_MARS            295
#define TRAINER_GALACTIC_GRUNT                 296
#define TRAINER_GALACTIC_GRUNT_2               297
#define TRAINER_GALACTIC_GRUNT_3               298
#define TRAINER_GALACTIC_GRUNT_4               299
#define TRAINER_GUITARIST_TONY                 300
#define TRAINER_GUITARIST_JERRY                301
#define TRAINER_GUITARIST_PRESTON              302
#define TRAINER_GUITARIST_LONNIE               303
#define TRAINER_RUIN_MANIAC_CALVIN             304
#define TRAINER_RUIN_MANIAC_LARRY              305
#define TRAINER_JOGGER_WYATT                   306
#define TRAINER_JOGGER_CRAIG                   307
#define TRAINER_JOGGER_RAUL                    308
#define TRAINER_BLACK_BELT_COLBY               309
#define TRAINER_BLACK_BELT_DARREN              310
#define TRAINER_BLACK_BELT_RAFAEL              311
#define TRAINER_BLACK_BELT_JEFFERY             312
#define TRAINER_BLACK_BELT_CARL                313
#define TRAINER_BLACK_BELT_RICKY               314
#define TRAINER_LEADER_GARDENIA_GARDENIA       315
#define TRAINER_LEADER_WAKE_WAKE               316
#define TRAINER_LEADER_MAYLENE_MAYLENE         317
#define TRAINER_LEADER_FANTINA_FANTINA         318
#define TRAINER_LEADER_CANDICE_CANDICE         319
#define TRAINER_LEADER_VOLKNER_VOLKNER         320
#define TRAINER_LASS_ANGELICA_2                321
#define TRAINER_LASS_MADELINE                  322
#define TRAINER_LASS_KAITLIN                   323
#define TRAINER_LASS_CAROLINE                  324
#define TRAINER_LASS_MOLLY                     325
#define TRAINER_HIKER_LOUIS                    326
#define TRAINER_PARASOL_LADY_ALEXA             327
#define TRAINER_PARASOL_LADY_SABRINA           328
#define TRAINER_PICNICKER_DIANA                329
#define TRAINER_PICNICKER_CHEYENNE             330
#define TRAINER_POKE_KID_MEGHAN                331
#define TRAINER_POLICEMAN_DANNY                332
#define TRAINER_POLICEMAN_THOMAS               333
#define TRAINER_RICH_BOY_MICKEY                334
#define TRAINER_RICH_BOY_TREY                  335
#define TRAINER_LADY_ANGELICA                  336
#define TRAINER_SAILOR_MARC                    337
#define TRAINER_SAILOR_SKYLER                  338
#define TRAINER_SAILOR_DAMIAN                  339
#define TRAINER_SCHOOL_KID_M_CHANCE            340
#define TRAINER_SCHOOL_KID_M_FORREST           341
#define TRAINER_SCHOOL_KID_M_HARRISON          342
#define TRAINER_SCHOOL_KID_F_MACKENZIE         343
#define TRAINER_SCHOOL_KID_F_TIERA             344
#define TRAINER_SCHOOL_KID_F_CHRISTINE         345
#define TRAINER_BEAUTY_CYNDY                   346
#define TRAINER_BEAUTY_ANGELICA_5              347
#define TRAINER_BEAUTY_LINDSAY                 348
#define TRAINER_SKIER_M_MICKEY                 349
#define TRAINER_SKIER_F_ANGELICA               350
#define TRAINER_SWIMMER_M_MICKEY_5             351
#define TRAINER_SWIMMER_M_MICKEY_6             352
#define TRAINER_SWIMMER_F_ANGELICA_4           353
#define TRAINER_SWIMMER_F_ANGELICA_5           354
#define TRAINER_YOUNGSTER_DALLAS               355
#define TRAINER_YOUNGSTER_SEBASTIAN            356
#define TRAINER_YOUNGSTER_DONNY                357
#define TRAINER_TUBER_M_TRENTON                358
#define TRAINER_TUBER_M_CONNER                 359
#define TRAINER_TUBER_F_MARIEL                 360
#define TRAINER_TUBER_F_HOLLY                  361
#define TRAINER_VETERAN_ARMANDO                362
#define TRAINER_WAITER_MICKEY                  363
#define TRAINER_WAITER_MICKEY_2                364
#define TRAINER_WAITER_MICKEY_3                365
#define TRAINER_WAITRESS_KATI                  366
#define TRAINER_WORKER_GERARDO                 367
#define TRAINER_INTERVIEWERS_ROXY_OLI          368
#define TRAINER_CAMERAMAN_TEVIN                369
#define TRAINER_REPORTER_KINSEY                370
#define TRAINER_IDOL_GRACE                     371
#define TRAINER_BATTLE_GIRL_TYLER              372
#define TRAINER_BIRD_KEEPER_AUTUMN             373
#define TRAINER_PKMN_BREEDER_M_MICKEY          374
#define TRAINER_PKMN_BREEDER_F_ANGELICA        375
#define TRAINER_CAMERAMAN_MICKEY               376
#define TRAINER_CAMPER_ZACKARY                 377
#define TRAINER_CAMPER_LAWRENCE                378
#define TRAINER_CAMPER_DIEGO                   379
#define TRAINER_CAMPER_PARKER                  380
#define TRAINER_COLLECTOR_DOMINIQUE            381
#define TRAINER_COLLECTOR_JAMAL                382
#define TRAINER_COLLECTOR_TERRY                383
#define TRAINER_POKEFAN_M_MICKEY_3             384
#define TRAINER_POKEFAN_F_ANGELICA_3           385
#define TRAINER_DRAGON_TAMER_JOE               386
#define TRAINER_ACE_TRAINER_M_MICKEY_2         387
#define TRAINER_ACE_TRAINER_M_JONAH            388
#define TRAINER_ACE_TRAINER_M_MICAH            389
#define TRAINER_ACE_TRAINER_M_ARTHUR           390
#define TRAINER_ACE_TRAINER_F_ANGELICA_3       391
#define TRAINER_ACE_TRAINER_F_BRENDA           392
#define TRAINER_ACE_TRAINER_F_BRANDI           393
#define TRAINER_ACE_TRAINER_F_CLARICE          394
#define TRAINER_PSYCHIC_M_KODY                 395
#define TRAINER_PSYCHIC_M_LANDON               396
#define TRAINER_PSYCHIC_M_DEANDRE              397
#define TRAINER_PSYCHIC_F_RACHAEL              398
#define TRAINER_PSYCHIC_F_DESIREE              399
#define TRAINER_PSYCHIC_F_KENDRA               400
#define TRAINER_FISHERMAN_WALTER               401
#define TRAINER_GENTLEMAN_MICKEY               402
#define TRAINER_GALACTIC_BOSS_CYRUS            403
#define TRAINER_GALACTIC_BOSS_CYRUS_2          404
#define TRAINER_COMMANDER_MARS_MARS_2          405
#define TRAINER_COMMANDER_JUPITER_JUPITER      406
#define TRAINER_COMMANDER_JUPITER_JUPITER_2    407
#define TRAINER_COMMANDER_SATURN_SATURN        408
#define TRAINER_COMMANDER_SATURN_SATURN_2      409
#define TRAINER_GALACTIC_GRUNT_5               410
#define TRAINER_GALACTIC_GRUNT_6               411
#define TRAINER_GALACTIC_GRUNT_7               412
#define TRAINER_GALACTIC_GRUNT_8               413
#define TRAINER_GALACTIC_GRUNT_9               414
#define TRAINER_GALACTIC_GRUNT_10              415
#define TRAINER_GALACTIC_GRUNT_11              416
#define TRAINER_GALACTIC_GRUNT_12              417
#define TRAINER_GALACTIC_GRUNT_13              418
#define TRAINER_GALACTIC_GRUNT_14              419
#define TRAINER_GALACTIC_GRUNT_15              420
#define TRAINER_GALACTIC_F_GRUNT               421
#define TRAINER_GALACTIC_F_GRUNT_2             422
#define TRAINER_GALACTIC_F_GRUNT_3             423
#define TRAINER_GALACTIC_F_GRUNT_4             424
#define TRAINER_GALACTIC_F_GRUNT_5             425
#define TRAINER_GALACTIC_F_GRUNT_6             426
#define TRAINER_GALACTIC_F_GRUNT_7             427
#define TRAINER_GALACTIC_F_GRUNT_8             428
#define TRAINER_GALACTIC_F_GRUNT_9             429
#define TRAINER_GALACTIC_F_GRUNT_10            430
#define TRAINER_GUITARIST_ARTURO               431
#define TRAINER_GUITARIST_MICKEY_3             432
#define TRAINER_GUITARIST_MICKEY_4             433
#define TRAINER_GUITARIST_MICKEY_5             434
#define TRAINER_GUITARIST_MICKEY_6             435
#define TRAINER_GUITARIST_MICKEY_7             436
#define TRAINER_IDOL_ANGELICA                  437
#define TRAINER_IDOL_ANGELICA_2                438
#define TRAINER_IDOL_ANGELICA_3                439
#define TRAINER_IDOL_ANGELICA_4                440
#define TRAINER_RUIN_MANIAC_MICKEY_2           441
#define TRAINER_RUIN_MANIAC_HARRY              442
#define TRAINER_RUIN_MANIAC_GERALD             443
#define TRAINER_BLACK_BELT_MILES               444
#define TRAINER_BLACK_BELT_KENDAL              445
#define TRAINER_BLACK_BELT_EDDIE               446
#define TRAINER_BLACK_BELT_WILLIE              447
#define TRAINER_SOCIALITE_ANGELICA             448
#define TRAINER_LASS_ANGELICA_3                449
#define TRAINER_LASS_CASSIDY                   450
#define TRAINER_HIKER_THEODORE                 451
#define TRAINER_HIKER_DAMON                    452
#define TRAINER_HIKER_MAURICE                  453
#define TRAINER_HIKER_REGINALD                 454
#define TRAINER_HIKER_LORENZO                  455
#define TRAINER_PICNICKER_KARINA               456
#define TRAINER_PICNICKER_SUMMER               457
#define TRAINER_PICNICKER_TORI                 458
#define TRAINER_PICNICKER_ANA                  459
#define TRAINER_CLOWN_LEE                      460
#define TRAINER_CLOWN_MICKEY_2                 461
#define TRAINER_CLOWN_MICKEY_3                 462
#define TRAINER_CLOWN_MICKEY_4                 463
#define TRAINER_CLOWN_MICKEY_5                 464
#define TRAINER_POKE_KID_ARIEL                 465
#define TRAINER_POLICEMAN_MICKEY               466
#define TRAINER_RICH_BOY_MICKEY_2              467
#define TRAINER_RICH_BOY_MICKEY_3              468
#define TRAINER_LADY_ANGELICA_2                469
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_4    470
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_5    471
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_6    472
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_7    473
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_8    474
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_9    475
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_10   476
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_11   477
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_12   478
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_13   479
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_14   480
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_15   481
#define TRAINER_SAILOR_ZACHARIAH               482
#define TRAINER_SAILOR_SAMSON                  483
#define TRAINER_SCHOOL_KID_M_MICKEY_2          484
#define TRAINER_SCHOOL_KID_F_ANGELICA_2        485
#define TRAINER_SCIENTIST_SHAUN                486
#define TRAINER_SCIENTIST_MICKEY_5             487
#define TRAINER_NINJA_BOY_FABIAN               488
#define TRAINER_NINJA_BOY_BRENNAN              489
#define TRAINER_NINJA_BOY_BRUCE                490
#define TRAINER_BEAUTY_DEVON                   491
#define TRAINER_BEAUTY_NICOLA                  492
#define TRAINER_SWIMMER_M_MICKEY_7             493
#define TRAINER_SWIMMER_F_CLAIRE               494
#define TRAINER_YOUNGSTER_MICKEY_6             495
#define TRAINER_YOUNGSTER_WAYNE                496
#define TRAINER_TUBER_M_JACKY                  497
#define TRAINER_TUBER_F_CAITLYN                498
#define TRAINER_VETERAN_TERRELL                499
#define TRAINER_VETERAN_BRENDEN                500
#define TRAINER_WAITER_MICKEY_4                501
#define TRAINER_WORKER_MICKEY_5                502
#define TRAINER_WORKER_WILLY                   503
#define TRAINER_WORKER_BRADEN                  504
#define TRAINER_WORKER_BRENDON                 505
#define TRAINER_WORKER_QUENTIN                 506
#define TRAINER_GALACTIC_GRUNT_16              507
#define TRAINER_GALACTIC_GRUNT_17              508
#define TRAINER_GALACTIC_GRUNT_18              509
#define TRAINER_GALACTIC_GRUNT_19              510
#define TRAINER_GALACTIC_GRUNT_20              511
#define TRAINER_GALACTIC_GRUNT_21              512
#define TRAINER_GALACTIC_GRUNT_22              513
#define TRAINER_GALACTIC_GRUNT_23              514
#define TRAINER_GALACTIC_GRUNT_24              515
#define TRAINER_GALACTIC_GRUNT_25              516
#define TRAINER_GALACTIC_GRUNT_26              517
#define TRAINER_GALACTIC_GRUNT_27              518
#define TRAINER_GALACTIC_GRUNT_28              519
#define TRAINER_GALACTIC_GRUNT_29              520
#define TRAINER_GALACTIC_GRUNT_30              521
#define TRAINER_GALACTIC_F_GRUNT_11            522
#define TRAINER_GALACTIC_F_GRUNT_12            523
#define TRAINER_GALACTIC_F_GRUNT_13            524
#define TRAINER_GALACTIC_F_GRUNT_14            525
#define TRAINER_GALACTIC_F_GRUNT_15            526
#define TRAINER_GALACTIC_F_GRUNT_16            527
#define TRAINER_COMMANDER_MARS_MARS_3          528
#define TRAINER_ROUGHNECK_KIRBY                529
#define TRAINER_POKEFAN_M_LEONARD              530
#define TRAINER_POKEFAN_F_REBEKAH              531
#define TRAINER_YOUNGSTER_OLIVER               532
#define TRAINER_BELLE__PA_BETH_BOB             533
#define TRAINER_YOUNG_COUPLE_MIKE_NAT          534
#define TRAINER_AROMA_LADY_ALISON              535
#define TRAINER_ARTIST_ISMAEL                  536
#define TRAINER_PKMN_BREEDER_F_KAYLEE          537
#define TRAINER_CAMERAMAN_DARRYL               538
#define TRAINER_COLLECTOR_EUGENE               539
#define TRAINER_POKEFAN_F_MEREDITH             540
#define TRAINER_PI_KENDRICK                    541
#define TRAINER_GENTLEMAN_LEONARDO             542
#define TRAINER_SOCIALITE_REBECCA              543
#define TRAINER_LASS_BLYTHE                    544
#define TRAINER_RICH_BOY_ROMAN                 545
#define TRAINER_LADY_KYLIE                     546
#define TRAINER_REPORTER_VALERIE               547
#define TRAINER_SCHOOL_KID_M_ESTEBAN           548
#define TRAINER_SCIENTIST_EMILIO               549
#define TRAINER_BEAUTY_GABRIELLA               550
#define TRAINER_BEAUTY_HARLEY                  551
#define TRAINER_VETERAN_EMANUEL                552
#define TRAINER_RUIN_MANIAC_KARL               553
#define TRAINER_BIRD_KEEPER_AUDREY             554
#define TRAINER_BIRD_KEEPER_GENEVA             555
#define TRAINER_BIRD_KEEPER_KRYSTAL            556
#define TRAINER_DRAGON_TAMER_GEOFFREY          557
#define TRAINER_DRAGON_TAMER_DARIEN            558
#define TRAINER_DRAGON_TAMER_KEEGAN            559
#define TRAINER_DRAGON_TAMER_STANLEY           560
#define TRAINER_DRAGON_TAMER_DRAKE             561
#define TRAINER_DRAGON_TAMER_KENNY             562
#define TRAINER_ACE_TRAINER_M_RODOLFO          563
#define TRAINER_ACE_TRAINER_M_SAUL             564
#define TRAINER_ACE_TRAINER_M_JOSE             565
#define TRAINER_ACE_TRAINER_M_FELIX            566
#define TRAINER_ACE_TRAINER_M_QUINN            567
#define TRAINER_ACE_TRAINER_M_GRAHAM           568
#define TRAINER_ACE_TRAINER_M_KEENAN           569
#define TRAINER_ACE_TRAINER_M_STEFAN           570
#define TRAINER_ACE_TRAINER_M_SKYLAR           571
#define TRAINER_ACE_TRAINER_M_ABEL             572
#define TRAINER_ACE_TRAINER_F_DEANNA           573
#define TRAINER_ACE_TRAINER_F_ARIANA           574
#define TRAINER_ACE_TRAINER_F_DANA             575
#define TRAINER_ACE_TRAINER_F_MIKAYLA          576
#define TRAINER_ACE_TRAINER_F_MEAGAN           577
#define TRAINER_ACE_TRAINER_F_SANDRA           578
#define TRAINER_ACE_TRAINER_F_KASSANDRA        579
#define TRAINER_ACE_TRAINER_F_JASMIN           580
#define TRAINER_ACE_TRAINER_F_NATASHA          581
#define TRAINER_ACE_TRAINER_F_MONIQUE          582
#define TRAINER_PSYCHIC_M_CORBIN               583
#define TRAINER_PSYCHIC_M_STERLING             584
#define TRAINER_PSYCHIC_F_DAISY                585
#define TRAINER_PSYCHIC_F_CHELSEY              586
#define TRAINER_BLACK_BELT_DAVON               587
#define TRAINER_BLACK_BELT_GRIFFIN             588
#define TRAINER_BLACK_BELT_RAY                 589
#define TRAINER_BLACK_BELT_JARRETT             590
#define TRAINER_PKMN_RANGER_M_KYLER            591
#define TRAINER_PKMN_RANGER_M_DESHAWN          592
#define TRAINER_PKMN_RANGER_M_DWAYNE           593
#define TRAINER_PKMN_RANGER_F_ASHLEE           594
#define TRAINER_PKMN_RANGER_F_FELICIA          595
#define TRAINER_PKMN_RANGER_F_KRISTA           596
#define TRAINER_SWIMMER_M_GLENN                597
#define TRAINER_SWIMMER_M_KURT                 598
#define TRAINER_SWIMMER_M_SAM                  599
#define TRAINER_SWIMMER_M_WADE                 600
#define TRAINER_SWIMMER_F_JOANNA               601
#define TRAINER_SWIMMER_F_SOPHIA               602
#define TRAINER_SWIMMER_F_MALLORY              603
#define TRAINER_SWIMMER_F_LYDIA                604
#define TRAINER_VETERAN_MICKEY_4               605
#define TRAINER_VETERAN_HARLAN                 606
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_16   607
#define TRAINER_PKMN_TRAINER_AROMA_LADY_CHERYL 608
#define TRAINER_PKMN_TRAINER_RICH_BOY_RILEY    609
#define TRAINER_PKMN_TRAINER_PICNICKER_MARLEY  610
#define TRAINER_PKMN_TRAINER_CAMPER_BUCK       611
#define TRAINER_PKMN_TRAINER_POKEKID_MIRA      612
#define TRAINER_PKMN_TRAINER_LUCAS_LUCAS       613
#define TRAINER_PKMN_TRAINER_LUCAS_LUCAS_2     614
#define TRAINER_PKMN_TRAINER_LUCAS_LUCAS_3     615
#define TRAINER_PKMN_TRAINER_DAWN_DAWN         616
#define TRAINER_PKMN_TRAINER_DAWN_DAWN_2       617
#define TRAINER_PKMN_TRAINER_DAWN_DAWN_3       618
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_17   619
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_18   620
#define TRAINER_PKMN_TRAINER_LUCAS_LUCAS_4     621
#define TRAINER_PKMN_TRAINER_LUCAS_LUCAS_5     622
#define TRAINER_PKMN_TRAINER_LUCAS_LUCAS_6     623
#define TRAINER_PKMN_TRAINER_DAWN_DAWN_4       624
#define TRAINER_PKMN_TRAINER_DAWN_DAWN_5       625
#define TRAINER_PKMN_TRAINER_DAWN_DAWN_6       626
#define TRAINER_AROMA_LADY_ELIZABETH_2         627
#define TRAINER_AROMA_LADY_ELIZABETH_3         628
#define TRAINER_AROMA_LADY_ELIZABETH_4         629
#define TRAINER_ARTIST_KEVIN                   630
#define TRAINER_ARTIST_KEVIN_2                 631
#define TRAINER_ARTIST_KEVIN_3                 632
#define TRAINER_BATTLE_GIRL_HELEN_2            633
#define TRAINER_BATTLE_GIRL_HELEN_3            634
#define TRAINER_BATTLE_GIRL_HELEN_4            635
#define TRAINER_BIRD_KEEPER_BRIANNA_2          636
#define TRAINER_BIRD_KEEPER_BRIANNA_3          637
#define TRAINER_BIRD_KEEPER_AUDREY_2           638
#define TRAINER_PKMN_BREEDER_M_ALBERT_2        639
#define TRAINER_PKMN_BREEDER_M_ALBERT_3        640
#define TRAINER_PKMN_BREEDER_M_ALBERT_4        641
#define TRAINER_PKMN_BREEDER_F_JENNIFER_2      642
#define TRAINER_PKMN_BREEDER_F_JENNIFER_3      643
#define TRAINER_PKMN_BREEDER_F_JENNIFER_4      644
#define TRAINER_CAMPER_ZACKARY_2               645
#define TRAINER_CAMPER_ZACKARY_3               646
#define TRAINER_CAMPER_ZACKARY_4               647
#define TRAINER_ACE_TRAINER_SNOW_M_DALTON_2    648
#define TRAINER_ACE_TRAINER_SNOW_F_OLIVIA_2    649
#define TRAINER_COLLECTOR_IVAN_2               650
#define TRAINER_COWGIRL_ANGELICA_2             651
#define TRAINER_COWGIRL_ANGELICA_3             652
#define TRAINER_CYCLIST_M_JOHN_2               653
#define TRAINER_CYCLIST_M_JOHN_3               654
#define TRAINER_CYCLIST_M_JOHN_4               655
#define TRAINER_CYCLIST_F_KAYLA_2              656
#define TRAINER_CYCLIST_F_KAYLA_3              657
#define TRAINER_CYCLIST_F_KAYLA_4              658
#define TRAINER_DRAGON_TAMER_PATRICK_2         659
#define TRAINER_DRAGON_TAMER_PATRICK_3         660
#define TRAINER_DRAGON_TAMER_HAYDEN_2          661
#define TRAINER_DRAGON_TAMER_GEOFFREY_2        662
#define TRAINER_ACE_TRAINER_M_JAKE_2           663
#define TRAINER_ACE_TRAINER_M_DENNIS_2         664
#define TRAINER_ACE_TRAINER_M_DENNIS_3         665
#define TRAINER_ACE_TRAINER_M_RODOLFO_2        666
#define TRAINER_ACE_TRAINER_M_SAUL_2           667
#define TRAINER_ACE_TRAINER_F_SHANNON_2        668
#define TRAINER_ACE_TRAINER_F_MAYA_2           669
#define TRAINER_ACE_TRAINER_F_MAYA_3           670
#define TRAINER_ACE_TRAINER_F_DEANNA_2         671
#define TRAINER_ACE_TRAINER_F_ARIANA_2         672
#define TRAINER_PSYCHIC_M_MITCHELL_2           673
#define TRAINER_PSYCHIC_M_MITCHELL_3           674
#define TRAINER_PSYCHIC_M_MAXWELL_2            675
#define TRAINER_PSYCHIC_M_CORBIN_2             676
#define TRAINER_PSYCHIC_F_ABIGAIL_2            677
#define TRAINER_PSYCHIC_F_ABIGAIL_3            678
#define TRAINER_PSYCHIC_F_BRITTNEY_2           679
#define TRAINER_PSYCHIC_F_DAISY_2              680
#define TRAINER_RANCHER_MARCO_2                681
#define TRAINER_RANCHER_MARCO_3                682
#define TRAINER_FISHERMAN_JOSEPH_2             683
#define TRAINER_FISHERMAN_JOSEPH_3             684
#define TRAINER_FISHERMAN_MIGUEL_2             685
#define TRAINER_FISHERMAN_ALEC_2               686
#define TRAINER_TWINS_TERI_TIA_2               687
#define TRAINER_TWINS_TERI_TIA_3               688
#define TRAINER_PI_CARLOS_2                    689
#define TRAINER_PI_CARLOS_3                    690
#define TRAINER_GENTLEMAN_JEREMY_2             691
#define TRAINER_GENTLEMAN_JEREMY_3             692
#define TRAINER_GENTLEMAN_JEREMY_4             693
#define TRAINER_GUITARIST_TONY_2               694
#define TRAINER_RUIN_MANIAC_HARRY_2            695
#define TRAINER_RUIN_MANIAC_HARRY_3            696
#define TRAINER_JOGGER_CRAIG_2                 697
#define TRAINER_JOGGER_CRAIG_3                 698
#define TRAINER_BLACK_BELT_PHILIP_2            699
#define TRAINER_BLACK_BELT_DAVON_2             700
#define TRAINER_SOCIALITE_REINA_2              701
#define TRAINER_SOCIALITE_REINA_3              702
#define TRAINER_LASS_SAMANTHA_2                703
#define TRAINER_LASS_SAMANTHA_3                704
#define TRAINER_LASS_SAMANTHA_4                705
#define TRAINER_LASS_MADELINE_2                706
#define TRAINER_LASS_MADELINE_3                707
#define TRAINER_LASS_MADELINE_4                708
#define TRAINER_HIKER_THEODORE_2               709
#define TRAINER_HIKER_THEODORE_3               710
#define TRAINER_HIKER_THEODORE_4               711
#define TRAINER_BUG_CATCHER_BRANDON_2          712
#define TRAINER_BUG_CATCHER_BRANDON_3          713
#define TRAINER_BUG_CATCHER_BRANDON_4          714
#define TRAINER_PARASOL_LADY_ALEXA_2           715
#define TRAINER_PARASOL_LADY_ALEXA_3           716
#define TRAINER_PARASOL_LADY_ALEXA_4           717
#define TRAINER_PICNICKER_KARINA_2             718
#define TRAINER_PICNICKER_KARINA_3             719
#define TRAINER_PICNICKER_KARINA_4             720
#define TRAINER_POKE_KID_DANIELLE_2            721
#define TRAINER_POKE_KID_DANIELLE_3            722
#define TRAINER_POKE_KID_DANIELLE_4            723
#define TRAINER_POLICEMAN_DANNY_2              724
#define TRAINER_POLICEMAN_DANNY_3              725
#define TRAINER_POLICEMAN_DANNY_4              726
#define TRAINER_RICH_BOY_TREY_2                727
#define TRAINER_RICH_BOY_TREY_3                728
#define TRAINER_LADY_MELISSA_2                 729
#define TRAINER_LADY_MELISSA_3                 730
#define TRAINER_LADY_MELISSA_4                 731
#define TRAINER_PKMN_RANGER_M_TAYLOR_2         732
#define TRAINER_PKMN_RANGER_M_TAYLOR_3         733
#define TRAINER_PKMN_RANGER_M_TAYLOR_4         734
#define TRAINER_PKMN_RANGER_M_KYLER_2          735
#define TRAINER_PKMN_RANGER_F_ALLISON_2        736
#define TRAINER_PKMN_RANGER_F_ALLISON_3        737
#define TRAINER_PKMN_RANGER_F_ALLISON_4        738
#define TRAINER_PKMN_RANGER_F_ASHLEE_2         739
#define TRAINER_SAILOR_MARC_2                  740
#define TRAINER_SAILOR_MARC_3                  741
#define TRAINER_SAILOR_ZACHARIAH_2             742
#define TRAINER_SCIENTIST_SHAUN_2              743
#define TRAINER_SCIENTIST_SHAUN_3              744
#define TRAINER_SCIENTIST_SHAUN_4              745
#define TRAINER_NINJA_BOY_ZACH_2               746
#define TRAINER_NINJA_BOY_ZACH_3               747
#define TRAINER_NINJA_BOY_ZACH_4               748
#define TRAINER_BEAUTY_CYNDY_2                 749
#define TRAINER_BEAUTY_CYNDY_3                 750
#define TRAINER_SKIER_M_EDWARD_2               751
#define TRAINER_SKIER_M_EDWARD_3               752
#define TRAINER_SKIER_M_BJORN_2                753
#define TRAINER_SKIER_M_BJORN_3                754
#define TRAINER_SKIER_F_ANDREA_2               755
#define TRAINER_SKIER_F_ANDREA_3               756
#define TRAINER_SKIER_F_MADISON_2              757
#define TRAINER_SKIER_F_MADISON_3              758
#define TRAINER_SWIMMER_M_WESLEY_2             759
#define TRAINER_SWIMMER_M_FRANCISCO_2          760
#define TRAINER_SWIMMER_M_GLENN_2              761
#define TRAINER_SWIMMER_F_MIRANDA_2            762
#define TRAINER_SWIMMER_F_CRYSTAL_2            763
#define TRAINER_SWIMMER_F_JOANNA_2             764
#define TRAINER_YOUNGSTER_TRISTAN_2            765
#define TRAINER_YOUNGSTER_TRISTAN_3            766
#define TRAINER_YOUNGSTER_TRISTAN_4            767
#define TRAINER_YOUNGSTER_DALLAS_2             768
#define TRAINER_YOUNGSTER_DALLAS_3             769
#define TRAINER_YOUNGSTER_DALLAS_4             770
#define TRAINER_TUBER_M_JARED_2                771
#define TRAINER_TUBER_M_JARED_3                772
#define TRAINER_TUBER_F_CHELSEA_2              773
#define TRAINER_VETERAN_BRIAN_2                774
#define TRAINER_TUBER_F_CHELSEA_3              775
#define TRAINER_VETERAN_BRIAN_3                776
#define TRAINER_VETERAN_ARMANDO_2              777
#define TRAINER_VETERAN_MICKEY_5               778
#define TRAINER_CAMERAMAN_MICKEY_2             779
#define TRAINER_CAMERAMAN_MICKEY_3             780
#define TRAINER_CAMERAMAN_MICKEY_4             781
#define TRAINER_CAMERAMAN_MICKEY_5             782
#define TRAINER_CAMERAMAN_MICKEY_6             783
#define TRAINER_GUITARIST_MICKEY_8             784
#define TRAINER_GUITARIST_ARTURO_2             785
#define TRAINER_GUITARIST_ARTURO_3             786
#define TRAINER_GUITARIST_MICKEY_9             787
#define TRAINER_GUITARIST_MICKEY_10            788
#define TRAINER_GUITARIST_MICKEY_11            789
#define TRAINER_IDOL_ANGELICA_5                790
#define TRAINER_IDOL_ANGELICA_6                791
#define TRAINER_IDOL_ANGELICA_7                792
#define TRAINER_IDOL_ANGELICA_8                793
#define TRAINER_IDOL_ANGELICA_9                794
#define TRAINER_INTERVIEWERS_TARA_TIM          795
#define TRAINER_INTERVIEWERS_TARA_TIM_2        796
#define TRAINER_INTERVIEWERS_TARA_TIM_3        797
#define TRAINER_INTERVIEWERS_TARA_TIM_4        798
#define TRAINER_CLOWN_MICKEY_6                 799
#define TRAINER_CLOWN_MICKEY_7                 800
#define TRAINER_CLOWN_MICKEY_8                 801
#define TRAINER_CLOWN_MICKEY_9                 802
#define TRAINER_CLOWN_MICKEY_10                803
#define TRAINER_POKE_KID_ANGELICA              804
#define TRAINER_POKE_KID_ANGELICA_2            805
#define TRAINER_POKE_KID_ANGELICA_3            806
#define TRAINER_POKE_KID_ANGELICA_4            807
#define TRAINER_POLICEMAN_MICKEY_2             808
#define TRAINER_REPORTER_ANGELICA              809
#define TRAINER_REPORTER_ANGELICA_2            810
#define TRAINER_REPORTER_ANGELICA_3            811
#define TRAINER_REPORTER_ANGELICA_4            812
#define TRAINER_SCIENTIST_MICKEY_6             813
#define TRAINER_SWIMMER_M_MICKEY_8             814
#define TRAINER_WAITER_MICKEY_5                815
#define TRAINER_WORKER_MICKEY_6                816
#define TRAINER_YOUNGSTER_ROLAND               817
#define TRAINER_LASS_CARRIE                    818
#define TRAINER_YOUNGSTER_NORMAN               819
#define TRAINER_YOUNGSTER_ROLAND_2             820
#define TRAINER_LASS_CARRIE_2                  821
#define TRAINER_YOUNGSTER_NORMAN_2             822
#define TRAINER_YOUNGSTER_ROLAND_3             823
#define TRAINER_LASS_CARRIE_3                  824
#define TRAINER_YOUNGSTER_NORMAN_3             825
#define TRAINER_TOWER_TYCOON_PALMER            826
#define TRAINER_ACE_TRAINER_SNOW_M_ANTON       827
#define TRAINER_ACE_TRAINER_SNOW_F_BRENNA      828
#define TRAINER_SCIENTIST_DARRIUS              829
#define TRAINER_SCIENTIST_FREDRICK             830
#define TRAINER_SCIENTIST_TRAVON               831
#define TRAINER_POKE_KID_JANET                 832
#define TRAINER_GALACTIC_GRUNT_31              833
#define TRAINER_GALACTIC_GRUNT_32              834
#define TRAINER_GALACTIC_GRUNT_33              835
#define TRAINER_GALACTIC_GRUNT_34              836
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_19   837
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_20   838
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_21   839
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_22   840
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_23   841
#define TRAINER_PKMN_TRAINER_BARRY_CEDRIC_24   842
#define TRAINER_GALACTIC_GRUNT_35              843
#define TRAINER_WORKER_DILLAN                  844
#define TRAINER_WORKER_HOLDEN                  845
#define TRAINER_WORKER_CONRAD                  846
#define TRAINER_GALACTIC_GRUNT_36              847
#define TRAINER_GALACTIC_GRUNT_37              848
#define TRAINER_GALACTIC_GRUNT_38              849

#endif // POKEDIAMOND_CONSTANTS_TRAINERS_H
