#ifndef POKEDIAMOND_CONSTANTS_TRAINER_CLASSES_H
#define POKEDIAMOND_CONSTANTS_TRAINER_CLASSES_H

#define TRAINER_CLASS_PKMN_TRAINER_M               0
#define TRAINER_CLASS_PKMN_TRAINER_F               1
#define TRAINER_CLASS_YOUNGSTER                    2
#define TRAINER_CLASS_LASS                         3
#define TRAINER_CLASS_CAMPER                       4
#define TRAINER_CLASS_PICNICKER                    5
#define TRAINER_CLASS_BUG_CATCHER                  6
#define TRAINER_CLASS_AROMA_LADY                   7
#define TRAINER_CLASS_TWINS                        8
#define TRAINER_CLASS_HIKER                        9
#define TRAINER_CLASS_BATTLE_GIRL                 10
#define TRAINER_CLASS_FISHERMAN                   11
#define TRAINER_CLASS_CYCLIST_M                   12
#define TRAINER_CLASS_CYCLIST_F                   13
#define TRAINER_CLASS_BLACK_BELT                  14
#define TRAINER_CLASS_ARTIST                      15
#define TRAINER_CLASS_PKMN_BREEDER_M              16
#define TRAINER_CLASS_PKMN_BREEDER_F              17
#define TRAINER_CLASS_COWGIRL                     18
#define TRAINER_CLASS_JOGGER                      19
#define TRAINER_CLASS_POKEFAN_M                   20
#define TRAINER_CLASS_POKEFAN_F                   21
#define TRAINER_CLASS_POKE_KID                    22
#define TRAINER_CLASS_YOUNG_COUPLE                23
#define TRAINER_CLASS_ACE_TRAINER_M               24
#define TRAINER_CLASS_ACE_TRAINER_F               25
#define TRAINER_CLASS_WAITRESS                    26
#define TRAINER_CLASS_VETERAN                     27
#define TRAINER_CLASS_NINJA_BOY                   28
#define TRAINER_CLASS_DRAGON_TAMER                29
#define TRAINER_CLASS_BIRD_KEEPER                 30
#define TRAINER_CLASS_DOUBLE_TEAM                 31
#define TRAINER_CLASS_RICH_BOY                    32
#define TRAINER_CLASS_LADY                        33
#define TRAINER_CLASS_GENTLEMAN                   34
#define TRAINER_CLASS_SOCIALITE                   35
#define TRAINER_CLASS_BEAUTY                      36
#define TRAINER_CLASS_COLLECTOR                   37
#define TRAINER_CLASS_POLICEMAN                   38
#define TRAINER_CLASS_PKMN_RANGER_M               39
#define TRAINER_CLASS_PKMN_RANGER_F               40
#define TRAINER_CLASS_SCIENTIST                   41
#define TRAINER_CLASS_SWIMMER_M                   42
#define TRAINER_CLASS_SWIMMER_F                   43
#define TRAINER_CLASS_TUBER_M                     44
#define TRAINER_CLASS_TUBER_F                     45
#define TRAINER_CLASS_SAILOR                      46
#define TRAINER_CLASS_SIS_AND_BRO                 47
#define TRAINER_CLASS_RUIN_MANIAC                 48
#define TRAINER_CLASS_PSYCHIC_M                   49
#define TRAINER_CLASS_PSYCHIC_F                   50
#define TRAINER_CLASS_PI                          51
#define TRAINER_CLASS_GUITARIST                   52
#define TRAINER_CLASS_ACE_TRAINER_SNOW_M          53
#define TRAINER_CLASS_ACE_TRAINER_SNOW_F          54
#define TRAINER_CLASS_SKIER_M                     55
#define TRAINER_CLASS_SKIER_F                     56
#define TRAINER_CLASS_ROUGHNECK                   57
#define TRAINER_CLASS_CLOWN                       58
#define TRAINER_CLASS_WORKER                      59
#define TRAINER_CLASS_SCHOOL_KID_M                60
#define TRAINER_CLASS_SCHOOL_KID_F                61
#define TRAINER_CLASS_LEADER_ROARK                62
#define TRAINER_CLASS_PKMN_TRAINER_BARRY          63
#define TRAINER_CLASS_LEADER_BYRON                64
#define TRAINER_CLASS_ELITE_FOUR_AARON            65
#define TRAINER_CLASS_ELITE_FOUR_BERTHA           66
#define TRAINER_CLASS_ELITE_FOUR_FLINT            67
#define TRAINER_CLASS_ELITE_FOUR_LUCIEN           68
#define TRAINER_CLASS_CHAMPION                    69
#define TRAINER_CLASS_BELLE__PA                   70
#define TRAINER_CLASS_RANCHER                     71
#define TRAINER_CLASS_COMMANDER_MARS              72
#define TRAINER_CLASS_GALACTIC                    73
#define TRAINER_CLASS_LEADER_GARDENIA             74
#define TRAINER_CLASS_LEADER_WAKE                 75
#define TRAINER_CLASS_LEADER_MAYLENE              76
#define TRAINER_CLASS_LEADER_FANTINA              77
#define TRAINER_CLASS_LEADER_CANDICE              78
#define TRAINER_CLASS_LEADER_VOLKNER              79
#define TRAINER_CLASS_PARASOL_LADY                80
#define TRAINER_CLASS_WAITER                      81
#define TRAINER_CLASS_INTERVIEWERS                82
#define TRAINER_CLASS_CAMERAMAN                   83
#define TRAINER_CLASS_REPORTER                    84
#define TRAINER_CLASS_IDOL                        85
#define TRAINER_CLASS_GALACTIC_BOSS               86
#define TRAINER_CLASS_COMMANDER_JUPITER           87
#define TRAINER_CLASS_COMMANDER_SATURN            88
#define TRAINER_CLASS_GALACTIC_F                  89
#define TRAINER_CLASS_PKMN_TRAINER_CHERYL         90
#define TRAINER_CLASS_PKMN_TRAINER_RILEY          91
#define TRAINER_CLASS_PKMN_TRAINER_MARLEY         92
#define TRAINER_CLASS_PKMN_TRAINER_BUCK           93
#define TRAINER_CLASS_PKMN_TRAINER_MIRA           94
#define TRAINER_CLASS_PKMN_TRAINER_LUCAS          95
#define TRAINER_CLASS_PKMN_TRAINER_DAWN           96
#define TRAINER_CLASS_TOWER_TYCOON                97

#define TRAINER_BACKPIC_LUCAS                      0
#define TRAINER_BACKPIC_DAWN                       1
#define TRAINER_BACKPIC_BARRY                      2
#define TRAINER_BACKPIC_CHERYL                     3
#define TRAINER_BACKPIC_RILEY                      4
#define TRAINER_BACKPIC_MARLEY                     5
#define TRAINER_BACKPIC_BUCK                       6
#define TRAINER_BACKPIC_MIRA                       7

#endif //POKEDIAMOND_CONSTANTS_TRAINER_CLASSES_H
