#ifndef POKEDIAMOND_CONSTANTS_WEATHER_H
#define POKEDIAMOND_CONSTANTS_WEATHER_H

#define WEATHER_SUNNY        0
#define WEATHER_CLOUDY       1
#define WEATHER_RAIN         2
#define WEATHER_HEAVY_RAIN   3
#define WEATHER_THUNDERSTORM 4
#define WEATHER_LIGHT_SNOW   5
#define WEATHER_SNOW         6
#define WEATHER_BLIZZARD     7
#define WEATHER_FOG          8
#define WEATHER_ASH          9
#define WEATHER_SANDSTORM    10
#define WEATHER_DIAMOND_DUST 11
#define WEATHER_UNKNOWN_12   12 // WEATHER_SPIRIT?
#define WEATHER_UNKNOWN_13   13 // WEATHER_MYSTIC?
#define WEATHER_DEFOG        14
#define WEATHER_UNKNOWN_15   15 // WEATHER_MIST_2?
#define WEATHER_FLASH        16
#define WEATHER_LIGHTNING    17
#define WEATHER_UNKNOWN_18   18 // WEATHER_FOGS?
#define WEATHER_UNKNOWN_19   19 // WEATHER_FOGM?
#define WEATHER_UNKNOWN_20   20 // WEATHER_RAINBOW?
#define WEATHER_UNKNOWN_21   21 // WEATHER_SNOW_STORM?
#define WEATHER_UNKNOWN_22   22 // WEATHER_STORM?
#define WEATHER_CANOPY       23
#define WEATHER_UNKNOWN_24   24 // WEATHER_CAVE_1?
#define WEATHER_CAVE_2       25
#define WEATHER_UNKNOWN_26   26 // WEATHER_GALAXY?
#define WEATHER_LOST_TOWER   27
#define WEATHER_UNKNOWN_28   28 // WEATHER_HARD_MOUNTAIN?
#define WEATHER_CAVE_3       29
#define WEATHER_LOW_LIGHT    30

#endif // POKEDIAMOND_CONSTANTS_WEATHER_H
