//==============================================================================
/**
 * @file	battle_id.h
 * @brief	戦闘画面で使用するセルIDやパレットIDの定義等
 * @author	matsuda
 * @date	2005.09.28(水)
 */
//==============================================================================
#ifndef __BATTLE_ID_H__
#define __BATTLE_ID_H__


//==============================================================================
//	
//==============================================================================
///戦闘入力画面のID定義で、各ID間で空けるID数
#define INPUT_FONT_ID_OFFSET	(10)

//==============================================================================
//	キャラID
//==============================================================================
enum{
	CHARID_START = 20000,
	CHARID_POKE_OAM_0,			///< ポケモンのOAM0
	CHARID_POKE_OAM_1,			///< ポケモンのOAM1
	CHARID_POKE_OAM_2,			///< ポケモンのOAM2
	CHARID_POKE_OAM_3,			///< ポケモンのOAM3

	CHARID_GAUGE_AA_GROUND_0,	///<ClientTypeAAのHPゲージ下地左側
	CHARID_GAUGE_AA_GROUND_1,	///<ClientTypeAAのHPゲージ下地右側
	CHARID_GAUGE_AA_0,			///<ClientTypeAAのHPゲージ左側
	CHARID_GAUGE_AA_1,			///<ClientTypeAAのHPゲージ右側
	CHARID_GAUGE_BB_GROUND_0,	///<ClientTypeBBのHPゲージ下地左側
	CHARID_GAUGE_BB_GROUND_1,	///<ClientTypeBBのHPゲージ下地右側
	CHARID_GAUGE_BB_0,			///<ClientTypeBBのHPゲージ左側
	CHARID_GAUGE_BB_1,			///<ClientTypeBBのHPゲージ右側

	CHARID_GROUND_MINE,			///<地面：自分側
	CHARID_GROUND_ENEMY,		///<地面：敵側

	//エンカウントトレーナー
	CHARID_ENCOUNT_TRAINER1,
	CHARID_ENCOUNT_TRAINER2,
	
	//控えポケモンレベルアップアイコン
	CHARID_BENCH_LEVELUP_ICON,
	CHARID_BENCH_LEVELUP_POKEICON,
	
	//戦闘入力画面：手持ちボール
	CHARID_STOCK_MINE,			///<自機側手持ちボール
	CHARID_STOCK_ENEMY,			///<敵側手持ちボール
	
	//戦闘入力画面：技タイプアイコン
	CHARID_WAZATYPE_ICON_1,
	CHARID_WAZATYPE_ICON_2,
	CHARID_WAZATYPE_ICON_3,
	CHARID_WAZATYPE_ICON_4,

	//戦闘入力画面：技分類アイコン
	CHARID_WAZAKIND_ICON_1,
	CHARID_WAZAKIND_ICON_2,
	CHARID_WAZAKIND_ICON_3,
	CHARID_WAZAKIND_ICON_4,

	//戦闘入力画面：拡大する黒枠
	CHARID_BLACK_WAKU_A,
	CHARID_BLACK_WAKU_B,
	CHARID_BLACK_WAKU_C,
	//戦闘入力画面：ポケモンアイコン
	CHARID_POKEICON_COMMAND,
	CHARID_POKEICON_B,
	CHARID_POKEICON_D,
	
	//戦闘入力画面のフォントOBJ
	CHARID_INPUT_FIGHT,		///<「たたかう」
	CHARID_INPUT_ITEM = CHARID_INPUT_FIGHT + INPUT_FONT_ID_OFFSET,	///<「バッグ」
	CHARID_INPUT_POKEMON = CHARID_INPUT_ITEM + INPUT_FONT_ID_OFFSET,	///<「ポケモン」
	CHARID_INPUT_ESCAPE = CHARID_INPUT_POKEMON + INPUT_FONT_ID_OFFSET,	///<「にげる」
	//技選択画面のフォントOBJ
	CHARID_INPUT_WAZA_CANCEL = CHARID_INPUT_ESCAPE + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_WAZA_1 = CHARID_INPUT_WAZA_CANCEL + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_WAZA_2 = CHARID_INPUT_WAZA_1 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_WAZA_3 = CHARID_INPUT_WAZA_2 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_WAZA_4 = CHARID_INPUT_WAZA_3 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPMSG_1 = CHARID_INPUT_WAZA_4 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPMSG_2 = CHARID_INPUT_PPMSG_1 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPMSG_3 = CHARID_INPUT_PPMSG_2 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPMSG_4 = CHARID_INPUT_PPMSG_3 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPNOW_1 = CHARID_INPUT_PPMSG_4 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPNOW_2 = CHARID_INPUT_PPNOW_1 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPNOW_3 = CHARID_INPUT_PPNOW_2 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPNOW_4 = CHARID_INPUT_PPNOW_3 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPMAX_1 = CHARID_INPUT_PPNOW_4 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPMAX_2 = CHARID_INPUT_PPMAX_1 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPMAX_3 = CHARID_INPUT_PPMAX_2 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPMAX_4 = CHARID_INPUT_PPMAX_3 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPSURA_1 = CHARID_INPUT_PPMAX_4 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPSURA_2 = CHARID_INPUT_PPSURA_1 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPSURA_3 = CHARID_INPUT_PPSURA_2 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_PPSURA_4 = CHARID_INPUT_PPSURA_3 + INPUT_FONT_ID_OFFSET,
	//戦闘入力画面：技分類
	CHARID_WAZA_CLASS_1 = CHARID_INPUT_PPSURA_4 + INPUT_FONT_ID_OFFSET,
	CHARID_WAZA_CLASS_2 = CHARID_WAZA_CLASS_1 + INPUT_FONT_ID_OFFSET,
	CHARID_WAZA_CLASS_3 = CHARID_WAZA_CLASS_2 + INPUT_FONT_ID_OFFSET,
	CHARID_WAZA_CLASS_4 = CHARID_WAZA_CLASS_3 + INPUT_FONT_ID_OFFSET,
	//たたかいを　やめますか？
	CHARID_INPUT_ESCAPE_SELECT = CHARID_WAZA_CLASS_4 + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_ESCAPE_YES = CHARID_INPUT_ESCAPE_SELECT + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_ESCAPE_NO = CHARID_INPUT_ESCAPE_YES + INPUT_FONT_ID_OFFSET,
	//ポケモン選択(技効果)
	CHARID_INPUT_POKE_A = CHARID_INPUT_ESCAPE_NO + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_POKE_B = CHARID_INPUT_POKE_A + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_POKE_C = CHARID_INPUT_POKE_B + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_POKE_D = CHARID_INPUT_POKE_C + INPUT_FONT_ID_OFFSET,
	CHARID_INPUT_POKE_CANCEL = CHARID_INPUT_POKE_D + INPUT_FONT_ID_OFFSET,
	
	//戦闘入力画面ID定義終了
	CHARID_INPUT_ID_END,
	CHARID_INPUT_END = CHARID_INPUT_ID_END + INPUT_FONT_ID_OFFSET,

	CHARID_BATTLE_CURSOR,		///<戦闘カーソル
	CHARID_FINGER_CURSOR,		///<捕獲デモ用指カーソル
	CHARID_TEMOTI_GAUGE,		///<手持ちゲージ
};

//==============================================================================
//	パレットID
//==============================================================================
enum{
	PLTTID_START = 20000,
	PLTTID_POKE_OAM_0,			///< ポケモンのOAM0
	PLTTID_POKE_OAM_1,			///< ポケモンのOAM1
	PLTTID_POKE_OAM_2,			///< ポケモンのOAM2
	PLTTID_POKE_OAM_3,			///< ポケモンのOAM3
	PLTTID_POKE_OAM_4,			///< 予備
	
	PLTTID_GAUGE,				///<HPゲージ
	PLTTID_GAUGE_EFF,			///<HPゲージ(エフェクト用)
	PLTTID_GAUGE_SAFARI,		///<HPゲージ(サファリ用)

	PLTTID_GROUND,				///<地面

	//エンカウントトレーナー
	PLTTID_ENCOUNT_TRAINER1,
	PLTTID_ENCOUNT_TRAINER2,
	
	//控えポケモンレベルアップアイコン
	PLTTID_BENCH_LEVELUP_ICON,
	PLTTID_BENCH_LEVELUP_POKEICON,

	//戦闘入力画面：手持ちボール
	PLTTID_STOCK_MINE,			///<自機側手持ちボール
	PLTTID_STOCK_ENEMY,			///<敵側手持ちボール

	//戦闘入力画面：技タイプアイコン
	PLTTID_WAZATYPE_ICON,
	//戦闘入力画面：技分類アイコン
	PLTTID_WAZAKIND_ICON = PLTTID_WAZATYPE_ICON,
	//戦闘入力画面：拡大する黒枠
	PLTTID_BLACK_WAKU,
	//戦闘入力画面：ポケモンアイコン
	PLTTID_POKEICON,
	//戦闘入力画面：常駐OBJパレット
	PLTTID_INPUT_COMMON,
	//戦闘入力画面のフォントOBJ
	PLTTID_INPUT_FONTOBJ_COMMON = PLTTID_INPUT_COMMON,	///<戦闘入力画面フォントOBJ共用パレットID
	PLTTID_INPUT_FIGHT = PLTTID_INPUT_FONTOBJ_COMMON,		///<「たたかう」
	PLTTID_INPUT_ITEM = PLTTID_INPUT_FONTOBJ_COMMON,	///<「バッグ」
	PLTTID_INPUT_POKEMON = PLTTID_INPUT_FONTOBJ_COMMON,	///<「ポケモン」
	PLTTID_INPUT_ESCAPE = PLTTID_INPUT_FONTOBJ_COMMON,	///<「にげる」
	//技選択画面のフォントOBJ
	PLTTID_INPUT_WAZA_CANCEL = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_WAZA_1 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_WAZA_2 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_WAZA_3 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_WAZA_4 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPMSG_1 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPMSG_2 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPMSG_3 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPMSG_4 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPNOW_1 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPNOW_2 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPNOW_3 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPNOW_4 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPMAX_1 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPMAX_2 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPMAX_3 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPMAX_4 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPSURA_1 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPSURA_2 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPSURA_3 = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_PPSURA_4 = PLTTID_INPUT_FONTOBJ_COMMON,
	//戦闘入力画面：技分類
	PLTTID_WAZA_CLASS = PLTTID_INPUT_FONTOBJ_COMMON,
	//たたかいを　やめますか？
	PLTTID_INPUT_ESCAPE_SELECT = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_ESCAPE_YES = PLTTID_INPUT_FONTOBJ_COMMON,
	PLTTID_INPUT_ESCAPE_NO = PLTTID_INPUT_FONTOBJ_COMMON,
	//ポケモン選択(技効果)
	PLTTID_INPUT_POKE = PLTTID_INPUT_FONTOBJ_COMMON,

	//戦闘入力画面ID定義終了
	PLTTID_INPUT_ID_END,
	PLTTID_INPUT_END = PLTTID_INPUT_ID_END + INPUT_FONT_ID_OFFSET,

	PLTTID_BATTLE_CURSOR,		///<戦闘カーソル
	PLTTID_FINGER_CURSOR,		///<捕獲デモ用指カーソル
	PLTTID_TEMOTI_GAUGE,		///<手持ちゲージ
};

//==============================================================================
//	セルID
//==============================================================================
enum{
	CELLID_START = 20000,
	CELLID_POKE_OAM_0,			///< ポケモンのOAM0
	CELLID_POKE_OAM_1,			///< ポケモンのOAM1
	CELLID_POKE_OAM_2,			///< ポケモンのOAM2
	CELLID_POKE_OAM_3,			///< ポケモンのOAM3

	CELLID_GROUND_MINE,			///<地面(自分側)
	CELLID_GROUND_ENEMY,		///<地面(敵側)

	//エンカウントトレーナー
	CELLID_ENCOUNT_TRAINER1,
	CELLID_ENCOUNT_TRAINER2,
	
	//控えポケモンレベルアップアイコン
	CELLID_BENCH_LEVELUP_ICON,
	CELLID_BENCH_LEVELUP_POKEICON,

	//戦闘入力画面：手持ちボール
	CELLID_STOCK_MINE,			///<自機側手持ちボール
	CELLID_STOCK_ENEMY,			///<敵側手持ちボール

	//戦闘入力画面：技タイプアイコン
	CELLID_WAZATYPE_ICON,
	//戦闘入力画面：技分類アイコン
	CELLID_WAZAKIND_ICON = CELLID_WAZATYPE_ICON,
	//戦闘入力画面：拡大する黒枠
	CELLID_BLACK_WAKU_A,
	CELLID_BLACK_WAKU_B,
	CELLID_BLACK_WAKU_C,
	//戦闘入力画面：ポケモンアイコン
	CELLID_POKEICON,

	//戦闘入力画面のフォントOBJ
	CELLID_INPUT_FIGHT,		///<「たたかう」
	CELLID_INPUT_ITEM = CELLID_INPUT_FIGHT + INPUT_FONT_ID_OFFSET,	///<「バッグ」
	CELLID_INPUT_POKEMON = CELLID_INPUT_ITEM + INPUT_FONT_ID_OFFSET,	///<「ポケモン」
	CELLID_INPUT_ESCAPE = CELLID_INPUT_POKEMON + INPUT_FONT_ID_OFFSET,	///<「にげる」
	//技選択画面のフォントOBJ
	CELLID_INPUT_WAZA_CANCEL = CELLID_INPUT_ESCAPE + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_WAZA_1 = CELLID_INPUT_WAZA_CANCEL + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_WAZA_2 = CELLID_INPUT_WAZA_1 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_WAZA_3 = CELLID_INPUT_WAZA_2 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_WAZA_4 = CELLID_INPUT_WAZA_3 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPMSG_1 = CELLID_INPUT_WAZA_4 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPMSG_2 = CELLID_INPUT_PPMSG_1 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPMSG_3 = CELLID_INPUT_PPMSG_2 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPMSG_4 = CELLID_INPUT_PPMSG_3 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPNOW_1 = CELLID_INPUT_PPMSG_4 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPNOW_2 = CELLID_INPUT_PPNOW_1 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPNOW_3 = CELLID_INPUT_PPNOW_2 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPNOW_4 = CELLID_INPUT_PPNOW_3 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPMAX_1 = CELLID_INPUT_PPNOW_4 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPMAX_2 = CELLID_INPUT_PPMAX_1 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPMAX_3 = CELLID_INPUT_PPMAX_2 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPMAX_4 = CELLID_INPUT_PPMAX_3 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPSURA_1 = CELLID_INPUT_PPMAX_4 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPSURA_2 = CELLID_INPUT_PPSURA_1 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPSURA_3 = CELLID_INPUT_PPSURA_2 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_PPSURA_4 = CELLID_INPUT_PPSURA_3 + INPUT_FONT_ID_OFFSET,
	//戦闘入力画面：技分類
	CELLID_WAZA_CLASS_1 = CELLID_INPUT_PPSURA_4 + INPUT_FONT_ID_OFFSET,
	CELLID_WAZA_CLASS_2 = CELLID_WAZA_CLASS_1 + INPUT_FONT_ID_OFFSET,
	CELLID_WAZA_CLASS_3 = CELLID_WAZA_CLASS_2 + INPUT_FONT_ID_OFFSET,
	CELLID_WAZA_CLASS_4 = CELLID_WAZA_CLASS_3 + INPUT_FONT_ID_OFFSET,
	//たたかいを　やめますか？
	CELLID_INPUT_ESCAPE_SELECT = CELLID_WAZA_CLASS_4 + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_ESCAPE_YES = CELLID_INPUT_ESCAPE_SELECT + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_ESCAPE_NO = CELLID_INPUT_ESCAPE_YES + INPUT_FONT_ID_OFFSET,
	//ポケモン選択(技効果)
	CELLID_INPUT_POKE_A = CELLID_INPUT_ESCAPE_NO + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_POKE_B = CELLID_INPUT_POKE_A + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_POKE_C = CELLID_INPUT_POKE_B + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_POKE_D = CELLID_INPUT_POKE_C + INPUT_FONT_ID_OFFSET,
	CELLID_INPUT_POKE_CANCEL = CELLID_INPUT_POKE_D + INPUT_FONT_ID_OFFSET,

	//戦闘入力画面ID定義終了
	CELLID_INPUT_ID_END,
	CELLID_INPUT_END = CELLID_INPUT_ID_END + INPUT_FONT_ID_OFFSET,
	
	//ゲージ矢印
	CELLID_GAUGE_ARROW,
	CELLID_GAUGE_ARROW_END = CELLID_GAUGE_ARROW + INPUT_FONT_ID_OFFSET,

	CELLID_BATTLE_CURSOR,		///<戦闘カーソル
	CELLID_FINGER_CURSOR,		///<捕獲デモ用指カーソル
	CELLID_TEMOTI_GAUGE,		///<手持ちゲージ
};

//==============================================================================
//	セルアニメID
//==============================================================================
enum{
	CELLANMID_START = 20000,
	CELLANMID_POKE_OAM_0,			///< ポケモンのOAM0
	CELLANMID_POKE_OAM_1,			///< ポケモンのOAM1
	CELLANMID_POKE_OAM_2,			///< ポケモンのOAM2
	CELLANMID_POKE_OAM_3,			///< ポケモンのOAM3

	CELLANMID_GROUND_MINE,			///<地面(自分側)
	CELLANMID_GROUND_ENEMY,			///<地面(敵側)

	//エンカウントトレーナー
	CELLANMID_ENCOUNT_TRAINER1,
	CELLANMID_ENCOUNT_TRAINER2,

	//控えポケモンレベルアップアイコン
	CELLANMID_BENCH_LEVELUP_ICON,
	CELLANMID_BENCH_LEVELUP_POKEICON,

	//戦闘入力画面：手持ちボール
	CELLANMID_STOCK_MINE,			///<自機側手持ちボール
	CELLANMID_STOCK_ENEMY,			///<敵側手持ちボール

	//戦闘入力画面：技タイプアイコン
	CELLANMID_WAZATYPE_ICON,
	//戦闘入力画面：技タイプアイコン
	CELLANMID_WAZAKIND_ICON = CELLANMID_WAZATYPE_ICON,
	//戦闘入力画面：拡大する黒枠
	CELLANMID_BLACK_WAKU_A,
	CELLANMID_BLACK_WAKU_B,
	CELLANMID_BLACK_WAKU_C,
	//戦闘入力画面：ポケモンアイコン
	CELLANMID_POKEICON,

	//戦闘入力画面のフォントOBJ
	CELLANMID_INPUT_FIGHT,		///<「たたかう」
	CELLANMID_INPUT_ITEM = CELLANMID_INPUT_FIGHT + INPUT_FONT_ID_OFFSET,	///<「バッグ」
	CELLANMID_INPUT_POKEMON = CELLANMID_INPUT_ITEM + INPUT_FONT_ID_OFFSET,	///<「ポケモン」
	CELLANMID_INPUT_ESCAPE = CELLANMID_INPUT_POKEMON + INPUT_FONT_ID_OFFSET,	///<「にげる」
	//技選択画面のフォントOBJ
	CELLANMID_INPUT_WAZA_CANCEL = CELLANMID_INPUT_ESCAPE + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_WAZA_1 = CELLANMID_INPUT_WAZA_CANCEL + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_WAZA_2 = CELLANMID_INPUT_WAZA_1 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_WAZA_3 = CELLANMID_INPUT_WAZA_2 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_WAZA_4 = CELLANMID_INPUT_WAZA_3 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPMSG_1 = CELLANMID_INPUT_WAZA_4 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPMSG_2 = CELLANMID_INPUT_PPMSG_1 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPMSG_3 = CELLANMID_INPUT_PPMSG_2 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPMSG_4 = CELLANMID_INPUT_PPMSG_3 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPNOW_1 = CELLANMID_INPUT_PPMSG_4 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPNOW_2 = CELLANMID_INPUT_PPNOW_1 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPNOW_3 = CELLANMID_INPUT_PPNOW_2 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPNOW_4 = CELLANMID_INPUT_PPNOW_3 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPMAX_1 = CELLANMID_INPUT_PPNOW_4 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPMAX_2 = CELLANMID_INPUT_PPMAX_1 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPMAX_3 = CELLANMID_INPUT_PPMAX_2 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPMAX_4 = CELLANMID_INPUT_PPMAX_3 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPSURA_1 = CELLANMID_INPUT_PPMAX_4 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPSURA_2 = CELLANMID_INPUT_PPSURA_1 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPSURA_3 = CELLANMID_INPUT_PPSURA_2 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_PPSURA_4 = CELLANMID_INPUT_PPSURA_3 + INPUT_FONT_ID_OFFSET,
	//戦闘入力画面：技分類
	CELLANMID_WAZA_CLASS_1 = CELLANMID_INPUT_PPSURA_4 + INPUT_FONT_ID_OFFSET,
	CELLANMID_WAZA_CLASS_2 = CELLANMID_WAZA_CLASS_1 + INPUT_FONT_ID_OFFSET,
	CELLANMID_WAZA_CLASS_3 = CELLANMID_WAZA_CLASS_2 + INPUT_FONT_ID_OFFSET,
	CELLANMID_WAZA_CLASS_4 = CELLANMID_WAZA_CLASS_3 + INPUT_FONT_ID_OFFSET,
	//たたかいを　やめますか？
	CELLANMID_INPUT_ESCAPE_SELECT = CELLANMID_WAZA_CLASS_4 + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_ESCAPE_YES = CELLANMID_INPUT_ESCAPE_SELECT + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_ESCAPE_NO = CELLANMID_INPUT_ESCAPE_YES + INPUT_FONT_ID_OFFSET,
	//ポケモン選択(技効果)
	CELLANMID_INPUT_POKE_A = CELLANMID_INPUT_ESCAPE_NO + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_POKE_B = CELLANMID_INPUT_POKE_A + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_POKE_C = CELLANMID_INPUT_POKE_B + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_POKE_D = CELLANMID_INPUT_POKE_C + INPUT_FONT_ID_OFFSET,
	CELLANMID_INPUT_POKE_CANCEL = CELLANMID_INPUT_POKE_D + INPUT_FONT_ID_OFFSET,

	//戦闘入力画面ID定義終了
	CELLANMID_INPUT_ID_END,
	CELLANMID_INPUT_END = CELLANMID_INPUT_ID_END + 10,

	CELLANMID_BATTLE_CURSOR,		///<戦闘カーソル
	CELLANMID_FINGER_CURSOR,		///<捕獲デモ用指カーソル
	CELLANMID_TEMOTI_GAUGE,		///<手持ちゲージ
};

//==============================================================================
//	マルチセルID
//==============================================================================
enum{
	MCELLID_START = 20000,
};

//==============================================================================
//	マルチセルアニメID
//==============================================================================
enum{
	MCELLANMID_START = 20000,
};



#endif	//__BATTLE_ID_H__

