/* 文字列表示制御コードの定義 */

#define EOM_			0xff		/* 終了コード */
#if 0
#define CR_				0xfe		/* 改行コード */
#define I_MSG_			0xfd		/* 指定バッファのメッセージ展開(ID)	*/
#define CTRL_			0xfc		/* フォント制御コマンド */
#define	NORMAL_WAIT_	0xfb		/* "▼"		トリガー待ち→MSGエリアクリア	*/
#define	SCROLL_WAIT_	0xfa		/* "↓"		トリガー待ち→一行スクロール */
#define	EXFONT1_		0xf9		/* 拡張フォント(fontnum = 0x100～0x1ff) */
#define	EXICON_			0xf8		/* 拡張アイコン(キーアイコン) */
#define S_MSG_			0xf7		/* 指定バッファのメッセージ展開(任意)*/

#define	C_FCOL_		0x01		/* フォント制御サブコマンド:文字色変更 */
#define	C_BCOL_		0x02		/* フォント制御サブコマンド:背景色変更 */
#define C_SCOL_		0x03		/* フォント制御サブコマンド:影色変更 */
#define C_ACOL_		0x04		/* フォント制御サブコマンド:全色指定変更(パラメータはFBSの順) */
#define C_PAL_		0x05		/* フォント制御サブコマンド:パレット変更 */
#define C_FCHG_		0x06		/* フォント制御サブコマンド:フォント変更 */
#define C_FNML_		0x07		/* フォント制御サブコマンド:フォント復帰 */
#define	C_WAIT_		0x08		/* フォント制御サブコマンド:ウェイトセット */
#define C_TRGWAIT_	0x09		/* フォント制御サブコマンド:キーウェイト */
#define C_SEWAIT_	0x0a		/* フォント制御サブコマンド:SEの鳴り終わりまで待つ */
#define C_MUSPLAY_	0x0b		/* フォント制御サブコマンド:BGMをならす */
#define C_EXFONT_	0x0c		/* フォント制御サブコマンド:拡張フォント指定 */
#define C_XCHG_		0x0d		/* フォント制御サブコマンド:表示X位置移動 */
#define C_YCHG_		0x0e		/* フォント制御サブコマンド:表示Y位置移動 */
#define C_CLR_		0x0f		/* フォント制御サブコマンド:MSGエリアクリア */
#define C_SEPLAY_	0x10		/* フォント制御サブコマンド:SEをならす */

//サブコード0x11～0x16	は海外版サブコード
#define C_STRUT_	0x11		/* 引数１ */
#define C_OFSX_		0x12		/* 引数１ */
#define C_BLANK_	0x13		/* 引数１ */
#define C_WIDTH_	0x14		/* 引数１ */
#define C_LANG_JP	0x15		/* 引数なし */
#define C_LANG_DEF	0x16		/* 引数なし */

#define C_MUSPAUSE_	0x17		/* フォント制御サブコマンド:BGMをPAUSE */
#define C_MUSCONTINUE_	0x18	/* フォント制御サブコマンド:BGMをCONTINUE */
#endif


/* 文字コードの定義 */

#define spc_       0x00         /* "　" */
#define a_         0x01         /* "あ" */
#define i_         0x02         /* "い" */
#define u_         0x03         /* "う" */
#define e_         0x04         /* "え" */
#define o_         0x05         /* "お" */
#define ka_        0x06         /* "か" */
#define ki_        0x07         /* "き" */
#define ku_        0x08         /* "く" */
#define ke_        0x09         /* "け" */
#define ko_        0x0a         /* "こ" */
#define sa_        0x0b         /* "さ" */
#define si_        0x0c         /* "し" */
#define su_        0x0d         /* "す" */
#define se_        0x0e         /* "せ" */
#define so_        0x0f         /* "そ" */
#define ta_        0x10         /* "た" */
#define ti_        0x11         /* "ち" */
#define tu_        0x12         /* "つ" */
#define te_        0x13         /* "て" */
#define to_        0x14         /* "と" */
#define na_        0x15         /* "な" */
#define ni_        0x16         /* "に" */
#define nu_        0x17         /* "ぬ" */
#define ne_        0x18         /* "ね" */
#define no_        0x19         /* "の" */
#define ha_        0x1a         /* "は" */
#define hi_        0x1b         /* "ひ" */
#define hu_        0x1c         /* "ふ" */
#define he_        0x1d         /* "へ" */
#define ho_        0x1e         /* "ほ" */
#define ma_        0x1f         /* "ま" */
#define mi_        0x20         /* "み" */
#define mu_        0x21         /* "む" */
#define me_        0x22         /* "め" */
#define mo_        0x23         /* "も" */
#define ya_        0x24         /* "や" */
#define yu_        0x25         /* "ゆ" */
#define yo_        0x26         /* "よ" */
#define ra_        0x27         /* "ら" */
#define ri_        0x28         /* "り" */
#define ru_        0x29         /* "る" */
#define re_        0x2a         /* "れ" */
#define ro_        0x2b         /* "ろ" */
#define wa_        0x2c         /* "わ" */
#define wo_        0x2d         /* "を" */
#define n_         0x2e         /* "ん" */
#define aa_        0x2f         /* "ぁ" */
#define ii_        0x30         /* "ぃ" */
#define uu_        0x31         /* "ぅ" */
#define ee_        0x32         /* "ぇ" */
#define oo_        0x33         /* "ぉ" */
#define yya_       0x34         /* "ゃ" */
#define yyu_       0x35         /* "ゅ" */
#define yyo_       0x36         /* "ょ" */
#define ga_        0x37         /* "が" */
#define gi_        0x38         /* "ぎ" */
#define gu_        0x39         /* "ぐ" */
#define ge_        0x3a         /* "げ" */
#define go_        0x3b         /* "ご" */
#define za_        0x3c         /* "ざ" */
#define zi_        0x3d         /* "じ" */
#define zu_        0x3e         /* "ず" */
#define ze_        0x3f         /* "ぜ" */
#define zo_        0x40         /* "ぞ" */
#define da_        0x41         /* "だ" */
#define di_        0x42         /* "ぢ" */
#define du_        0x43         /* "づ" */
#define de_        0x44         /* "で" */
#define do_        0x45         /* "ど" */
#define ba_        0x46         /* "ば" */
#define bi_        0x47         /* "び" */
#define bu_        0x48         /* "ぶ" */
#define be_        0x49         /* "べ" */
#define bo_        0x4a         /* "ぼ" */
#define pa_        0x4b         /* "ぱ" */
#define pi_        0x4c         /* "ぴ" */
#define pu_        0x4d         /* "ぷ" */
#define pe_        0x4e         /* "ぺ" */
#define po_        0x4f         /* "ぽ" */
#define ttu_       0x50         /* "っ" */
#define A_         0x51         /* "ア" */
#define I_         0x52         /* "イ" */
#define U_         0x53         /* "ウ" */
#define E_         0x54         /* "エ" */
#define O_         0x55         /* "オ" */
#define KA_        0x56         /* "カ" */
#define KI_        0x57         /* "キ" */
#define KU_        0x58         /* "ク" */
#define KE_        0x59         /* "ケ" */
#define KO_        0x5a         /* "コ" */
#define SA_        0x5b         /* "サ" */
#define SI_        0x5c         /* "シ" */
#define SU_        0x5d         /* "ス" */
#define SE_        0x5e         /* "セ" */
#define SO_        0x5f         /* "ソ" */
#define TA_        0x60         /* "タ" */
#define TI_        0x61         /* "チ" */
#define TU_        0x62         /* "ツ" */
#define TE_        0x63         /* "テ" */
#define TO_        0x64         /* "ト" */
#define NA_        0x65         /* "ナ" */
#define NI_        0x66         /* "ニ" */
#define NU_        0x67         /* "ヌ" */
#define NE_        0x68         /* "ネ" */
#define NO_        0x69         /* "ノ" */
#define HA_        0x6a         /* "ハ" */
#define HI_        0x6b         /* "ヒ" */
#define HU_        0x6c         /* "フ" */
#define HE_        0x6d         /* "ヘ" */
#define HO_        0x6e         /* "ホ" */
#define MA_        0x6f         /* "マ" */
#define MI_        0x70         /* "ミ" */
#define MU_        0x71         /* "ム" */
#define ME_        0x72         /* "メ" */
#define MO_        0x73         /* "モ" */
#define YA_        0x74         /* "ヤ" */
#define YU_        0x75         /* "ユ" */
#define YO_        0x76         /* "ヨ" */
#define RA_        0x77         /* "ラ" */
#define RI_        0x78         /* "リ" */
#define RU_        0x79         /* "ル" */
#define RE_        0x7a         /* "レ" */
#define RO_        0x7b         /* "ロ" */
#define WA_        0x7c         /* "ワ" */
#define WO_        0x7d         /* "ヲ" */
#define N_         0x7e         /* "ン" */
#define AA_        0x7f         /* "ァ" */
#define II_        0x80         /* "ィ" */
#define UU_        0x81         /* "ゥ" */
#define EE_        0x82         /* "ェ" */
#define OO_        0x83         /* "ォ" */
#define YYA_       0x84         /* "ャ" */
#define YYU_       0x85         /* "ュ" */
#define YYO_       0x86         /* "ョ" */
#define GA_        0x87         /* "ガ" */
#define GI_        0x88         /* "ギ" */
#define GU_        0x89         /* "グ" */
#define GE_        0x8a         /* "ゲ" */
#define GO_        0x8b         /* "ゴ" */
#define ZA_        0x8c         /* "ザ" */
#define ZI_        0x8d         /* "ジ" */
#define ZU_        0x8e         /* "ズ" */
#define ZE_        0x8f         /* "ゼ" */
#define ZO_        0x90         /* "ゾ" */
#define DA_        0x91         /* "ダ" */
#define DI_        0x92         /* "ヂ" */
#define DU_        0x93         /* "ヅ" */
#define DE_        0x94         /* "デ" */
#define DO_        0x95         /* "ド" */
#define BA_        0x96         /* "バ" */
#define BI_        0x97         /* "ビ" */
#define BU_        0x98         /* "ブ" */
#define BE_        0x99         /* "ベ" */
#define BO_        0x9a         /* "ボ" */
#define PA_        0x9b         /* "パ" */
#define PI_        0x9c         /* "ピ" */
#define PU_        0x9d         /* "プ" */
#define PE_        0x9e         /* "ペ" */
#define PO_        0x9f         /* "ポ" */
#define TTU_       0xa0         /* "ッ" */
#define n0_        0xa1         /* "０" */
#define n1_        0xa2         /* "１" */
#define n2_        0xa3         /* "２" */
#define n3_        0xa4         /* "３" */
#define n4_        0xa5         /* "４" */
#define n5_        0xa6         /* "５" */
#define n6_        0xa7         /* "６" */
#define n7_        0xa8         /* "７" */
#define n8_        0xa9         /* "８" */
#define n9_        0xaa         /* "９" */
#define gyoe_     0xab         /* "！" */
#define hate_     0xac         /* "？" */
#define kten_     0xad         /* "。" */
#define bou_      0xae         /* "ー" */
#define nakag_    0xaf         /* "・" */
#define tenten_   0xb0         /* "…" */
#define kako2_    0xb1         /* "『" */
#define kakot2_   0xb2         /* "』" */
#define kako_     0xb3         /* "「" */
#define kakot_    0xb4         /* "」" */
#define osu_      0xb5         /* "♂" */
#define mesu_     0xb6         /* "♀" */
#define yen_      0xb7         /* "円" */
#define ten_      0xb8         /* "．" */
#define batu_     0xb9         /* "×" */
#define sura_     0xba         /* "／" */
#define A__        0xbb         /* "Ａ" */
#define B__        0xbc         /* "Ｂ" */
#define C__        0xbd         /* "Ｃ" */
#define D__        0xbe         /* "Ｄ" */
#define E__        0xbf         /* "Ｅ" */
#define F__        0xc0         /* "Ｆ" */
#define G__        0xc1         /* "Ｇ" */
#define H__        0xc2         /* "Ｈ" */
#define I__        0xc3         /* "Ｉ" */
#define J__        0xc4         /* "Ｊ" */
#define K__        0xc5         /* "Ｋ" */
#define L__        0xc6         /* "Ｌ" */
#define M__        0xc7         /* "Ｍ" */
#define N__        0xc8         /* "Ｎ" */
#define O__        0xc9         /* "Ｏ" */
#define P__        0xca         /* "Ｐ" */
#define Q__        0xcb         /* "Ｑ" */
#define R__        0xcc         /* "Ｒ" */
#define S__        0xcd         /* "Ｓ" */
#define T__        0xce         /* "Ｔ" */
#define U__        0xcf         /* "Ｕ" */
#define V__        0xd0         /* "Ｖ" */
#define W__        0xd1         /* "Ｗ" */
#define X__        0xd2         /* "Ｘ" */
#define Y__        0xd3         /* "Ｙ" */
#define Z__        0xd4         /* "Ｚ" */
#define a__        0xd5         /* "ａ" */
#define b__        0xd6         /* "ｂ" */
#define c__        0xd7         /* "ｃ" */
#define d__        0xd8         /* "ｄ" */
#define e__        0xd9         /* "ｅ" */
#define f__        0xda         /* "ｆ" */
#define g__        0xdb         /* "ｇ" */
#define h__        0xdc         /* "ｈ" */
#define i__        0xdd         /* "ｉ" */
#define j__        0xde         /* "ｊ" */
#define k__        0xdf         /* "ｋ" */
#define l__        0xe0         /* "ｌ" */
#define m__        0xe1         /* "ｍ" */
#define n__        0xe2         /* "ｎ" */
#define o__        0xe3         /* "ｏ" */
#define p__        0xe4         /* "ｐ" */
#define q__        0xe5         /* "ｑ" */
#define r__        0xe6         /* "ｒ" */
#define s__        0xe7         /* "ｓ" */
#define t__        0xe8         /* "ｔ" */
#define u__        0xe9         /* "ｕ" */
#define v__        0xea         /* "ｖ" */
#define w__        0xeb         /* "ｗ" */
#define x__        0xec         /* "ｘ" */
#define y__        0xed         /* "ｙ" */
#define z__        0xee         /* "ｚ" */
#define cursor_    0xef			/* 右カーソル */
#define colon_     0xf0			/* "：" */
#define	Auml_      0xf1			/* ウムラウト大文字A */
#define	Ouml_      0xf2			/* ウムラウト大文字O */
#define	Uuml_      0xf3			/* ウムラウト大文字U */
#define	auml_      0xf4			/* ウムラウト小文字a */
#define	ouml_      0xf5			/* ウムラウト小文字o */
#define	uuml_      0xf6			/* ウムラウト小文字u */

#if 0
/* 拡張フォント文字コードの定義 */
//#define ArrowU__	0xf7		/* 上向きやじるし */
//#define ArrowD__	0xf8		/* 下向きやじるし */
//#define ArrowL__	0xf9		/* 左向きやじるし */
//#define ArrowR__	0xfa		/* 右向きやじるし */
//#define Plus__	0xfb		/* プラス記号 */

/* 拡張フォント文字コードの定義 2003.4.10 追加*/
#define ArrowU__	0x00		/* 上向きやじるし */
#define ArrowD__	0x01		/* 下向きやじるし */
#define	ArrowL__	0x02		/* 左向きやじるし */
#define	ArrowR__	0x03		/* 右向きやじるし */
#define Plus__		0x04		/* プラス記号 */
#define Lv__		0x05		/* レベル記号 */
#define PP__		0x06		/* ＰＰ記号 */
#define ID__		0x07		/* ＩＤ記号 */
#define No__		0x08		/* Ｎｏ記号 */
#define	UnderBer_	0x09		/* アンダーバー */
#define MARU1__		0x0a		/* ① */
#define MARU2__		0x0b		/* ② */
#define MARU3__		0x0c		/* ③ */
#define MARU4__		0x0d		/* ④ */
#define MARU5__		0x0e		/* ⑤ */
#define MARU6__		0x0f		/* ⑥ */
#define MARU7__		0x10		/* ⑦ */
#define MARU8__		0x11		/* ⑧ */
#define MARU9__		0x12		/* ⑨ */
#define MaruKako__	0x13		/* （ */
#define MaruKakot__	0x14		/* ） */
#define NijuMaru_	0x15		/* ◎ */
#define Sankaku_	0x16		/* △ */

#define	E_RBUTTON_		0xcc		/* Ｒボタン */
#define	E_DAI_			0xcd		/* 大 */
#define	E_SYOU_			0xce		/* 小 */
#define	E_DAKU_			0xcf		/* 濁点 */
#define	E_HANDAKU_		0xd0		/* 半濁点 */
#define	E_VBAR_			0xd1		/* 縦棒 */
#define	E_HBAR_			0xd2		/* 横棒 */
#define	E_NYORO_		0xd3		/* ～ */
#define	E_KAKO_			0xd4		/* （ */
#define	E_KAKOT_		0xd5		/* ） */
#define	E_SET_			0xd6		/* ⊂ */
#define E_GREAT_		0xd7		/* ＞ */
#define	E_EYE_L_		0xd8		/* 左目 */
#define	E_EYE_R_		0xd9		/* 右目 */
#define	E_ATMARK_		0xda		/* ＠ */
#define E_SEMICOLON_	0xdb		/* ； */
#define	E_PLUS_			0xdc		/* ＋ */
#define	E_MINUS_		0xdd		/* － */
#define	E_EQUAL_		0xde		/* ＝ */
#define	E_UZUMAKI_		0xdf		/* うずまきマーク */
#define	E_BERO_			0xe0		/* べろマーク */
#define	E_SANKAKU_		0xe1		/* △ */
#define	E_QUOT_			0xe2		/* クォーテーション開き */
#define	E_QUOTT_		0xe3		/* クォーテーション閉じ */
#define	E_CIRCLE_		0xe4		/* ● */
#define	E_TRIANGLE_		0xe5		/* ▼ */
#define	E_SQUARE_		0xe6		/* ■ */
#define	E_HEART_		0xe7		/* ハート */
#define	E_MOON_			0xe8		/* 三日月 */
#define	E_NOTE_			0xe9		/* 音符 */
#define	E_MBALL_		0xea		/* モンスターボール */
#define	E_THUNDER_		0xeb		/* 雷マーク */
#define	E_LEAF_			0xec		/* 葉っぱマーク */
#define	E_FIRE_			0xed		/* 炎マーク */
#define	E_WATER_		0xee		/* 水マーク */
#define	E_HANDR_		0xef		/* 右手 */
#define	E_HANDL_		0xf0		/* 左手 */
#define	E_FLOWER_		0xf1		/* 花マーク */
#define	E_EYE1_			0xf2		/* 目マーク１ */
#define	E_EYE2_			0xf3		/* 目マーク２ */
#define	E_IKARI_		0xf4		/* 怒りマーク */
#define	E_KAO_01_		0xf5		/* 顔１ */
#define	E_KAO_02_		0xf6		/* 顔２ */
#define	E_KAO_03_		0xf7		/* 顔３（ヘの字口）*/
#define	E_KAO_04_		0xf8		/* 顔４（鼻） */
#define	E_KAO_05_		0xf9		/* 顔５（笑顔）*/
#define	E_KAO_06_		0xfa		/* 顔６（悪そう）*/
#define	E_KAO_07_		0xfb		/* 顔７（ヘコみ）*/
#define	E_KAO_08_		0xfc		/* 顔８（真顔）*/
#define	E_KAO_09_		0xfd		/* 顔９（驚き）*/
#define	E_KAO_10_		0xfe		/* 顔10（怒り）*/

// ------------ 0xff は EOM_ と判定されるので使わないこと！ ---------

/* 拡張アイコン(キーアイコン)文字コードの定義 2003.7.30 追加*/
#define	FICN_BTN_A_		0x00		/* Ａボタン */
#define	FICN_BTN_B_		0x01		/* Ｂボタン */
#define	FICN_BTN_L_		0x02		/* Ｌボタン */
#define	FICN_BTN_R_		0x03		/* Ｒボタン */
#define	FICN_BTN_ST_	0x04		/* スタートボタン */
#define	FICN_BTN_SE_	0x05		/* セレクトボタン */
#define	FICN_KEY_U_		0x06		/* Ｕキー */
#define	FICN_KEY_D_		0x07		/* Ｄキー */
#define	FICN_KEY_L_		0x08		/* Ｌキー */
#define	FICN_KEY_R_		0x09		/* Ｒキー */
#define	FICN_KEY_UD_	0x0a		/* ＵＤキー */
#define	FICN_KEY_LR_	0x0b		/* ＬＲキー */
#define	FICN_KEY_UDLR_	0x0c		/* ＵＤＬＲキー */
#endif
