#define	ITEMUSE_FLD_RECOVER				( 1 )	// フィールド：回復
#define	ITEMUSE_FLD_TOWNMAP				( 2 )	// フィールド：タウンマップ
#define	ITEMUSE_FLD_UPDOWN				( 3 )	// フィールド：探検セット
#define	ITEMUSE_FLD_CYCLE				( 4 )	// フィールド：自転車
#define	ITEMUSE_FLD_FNOTE				( 5 )	// フィールド：冒険ノート
#define	ITEMUSE_FLD_WAZA				( 6 )	// フィールド：技マシン
#define	ITEMUSE_FLD_MAIL				( 7 )	// フィールド：メール
#define	ITEMUSE_FLD_KINOMI				( 8 )	// フィールド：きのみ
#define	ITEMUSE_FLD_PRT_CASE			( 9 )	// フィールド：ポルトケース
#define	ITEMUSE_FLD_FRIENDBOOK			( 10 )	// フィールド：友達手帳
#define	ITEMUSE_FLD_POKESEARCH			( 11 )	// フィールド：ポケサーチャー
#define	ITEMUSE_FLD_ZYORO				( 12 )	// フィールド：じょうろ
#define	ITEMUSE_FLD_KOYASHI				( 13 )	// フィールド：肥やし
#define	ITEMUSE_FLD_MITSU				( 14 )	// フィールド：甘い蜜
#define	ITEMUSE_FLD_BTLSEARCHER			( 15 )	// フィールド：バトルサーチャー
#define ITEMUSE_FLD_FISHING_ROD_BAD 	( 16 )	// フィールド：ボロの釣り竿
#define ITEMUSE_FLD_FISHING_ROD_GOOD	( 17 )	// フィールド：良い釣り竿
#define ITEMUSE_FLD_FISHING_ROD_GREAT 	( 18 )	// フィールド：凄い釣り竿
#define ITEMUSE_FLD_BAG_MSG			 	( 19 )	// フィールド：バッグでメッセージを表示するだけ
#define ITEMUSE_FLD_EVOLUTION			( 20 )	// フィールド：進化
#define ITEMUSE_FLD_ANANUKE			 	( 21 )	// フィールド：穴抜けの紐
#define ITEMUSE_FLD_TENKAINOFUE		 	( 22 )	// フィールド：天界の笛

#define	ITEMUSE_BTL_BALL		( 1 )	// バトル：ボール
#define	ITEMUSE_BTL_RECOVER		( 2 )	// バトル：回復
#define	ITEMUSE_BTL_ESCAPE		( 3 )	// バトル：逃げる
