#ifndef _FIELD_3D_ANIME_DEF_H_
#define _FIELD_3D_ANIME_DEF_H_

#include "../fielddata/build_model/build_model_id.h"

#define FUNSUI_CODE				(BMID_FUNSUI)
#define TREEEFF_CODE			(BMID_TREEEFF)
#define DOCTOR_MACHINE_CODE		(BMID_MACHINE_L02)
#define DOOR_TYPE1_CODE			(BMID_DOOR01)
#define DOOR_TYPE2_CODE			(BMID_T1_DOOR1)
#define DOOR_TYPE3_CODE			(BMID_T2_DOOR1)
#define DOOR_TYPE4_CODE			(BMID_T2_DOOR2)
#define P_DOOR_TYPE1_CODE		(BMID_P_DOOR)
#define GYM_BUTN1_CODE			(BMID_R04_B1)
#define GYM_BUTN2_CODE			(BMID_R04_B2)
#define GYM_BUTN3_CODE			(BMID_R04_B3)
#define GYM_WATER_CODE			(BMID_R04_W)
#define ESCA_DOWN_CODE			(BMID_STAIR_PC_D01)
#define ESCA_UP_CODE			(BMID_STAIR_PC_U01)
#define GHOST_GYM_DOOR_CODE		(BMID_GYM_DOOR01)
#define	GHOST_GYM_LIGHT_CODE	(BMID_GYM05_O4)
#define	FALL1_CODE				(BMID_WFALL3_4)
#define	FALL2_CODE				(BMID_WFALL3_5)
#define	FALL3_CODE				(BMID_WFALL16_5)
#define	FALL4_CODE				(BMID_WFALL11_14)
#define	FALL5_CODE				(BMID_WFALL7_4DUN)
#define	FALL6_CODE				(BMID_WFALL3_4DUN)
#define	LAKE_CODE				(BMID_L_LAKE)
#define	CY_SLOPE_CODE			(BMID_CY_SLOPE)
#define	ELE_MACHINE_CODE		(BMID_MACHINE_L03)
#define	FLAG_CODE				(BMID_C1_S01)
#define	MONITOR_CODE			(BMID_C1_S02)
#define	PROPELLER1_CODE			(BMID_D2_S01)
#define	PROPELLER2_CODE			(BMID_D2_S01A)
#define	PROPELLER3_CODE			(BMID_D2_S01B)

//ドア共通
#define ANIME_NO_DOOR_OPEN	(0)
#define ANIME_NO_DOOR_CLOSE	(1)

//自動ドア
#define ANIME_NO_DOOR_AUTO_OPEN		(ANIME_NO_DOOR_OPEN)
#define ANIME_NO_DOOR_AUTO_CLOSE	(ANIME_NO_DOOR_CLOSE)
//ドア
#define ANIME_NO_DOOR_OPEN_IN		(ANIME_NO_DOOR_OPEN)
#define ANIME_NO_DOOR_CLOSE_IN		(ANIME_NO_DOOR_CLOSE)
#define ANIME_NO_DOOR_OPEN_OUT		(2)
#define ANIME_NO_DOOR_CLOSE_OUT		(3)
//エスカレーター
#define ANIME_NO_ESCA			(0)
#endif	//_FIELD_3D_ANIME_DEF_H_
