//リボン参照用define by tomo
//スクリプト上では、リボン番号が扱えない(poketool.hが参照不可)ので間接的に扱っています。
//中村君のリボン関数と並びが同期しています。

#define RIBBON_CHAMP_RIBBON						(0)			//チャンプリボン
#define RIBBON_STYLEMEDAL_NORMAL 					(1)			//かっこよさ勲章(ノーマル)AGBコンテスト
#define RIBBON_STYLEMEDAL_SUPER 					(2)			//かっこよさ勲章(スーパー)AGBコンテスト
#define RIBBON_STYLEMEDAL_HYPER 					(3)			//かっこよさ勲章(ハイパー)AGBコンテスト
#define RIBBON_STYLEMEDAL_MASTER 					(4)			//かっこよさ勲章(マスター)AGBコンテスト
#define RIBBON_BEAUTIFULMEDAL_NORMAL 				(5)			//うつくしさ勲章(ノーマル)AGBコンテスト
#define RIBBON_BEAUTIFULMEDAL_SUPER 				(6)			//うつくしさ勲章(スーパー)AGBコンテスト
#define RIBBON_BEAUTIFULMEDAL_HYPER 				(7)			//うつくしさ勲章(ハイパー)AGBコンテスト
#define RIBBON_BEAUTIFULMEDAL_MASTER 				(8)			//うつくしさ勲章(マスター)AGBコンテスト
#define RIBBON_CUTEMEDAL_NORMAL 					(9)			//かわいさ勲章(ノーマル)AGBコンテスト
#define RIBBON_CUTEMEDAL_SUPER 					(10)		//かわいさ勲章(スーパー)AGBコンテスト
#define RIBBON_CUTEMEDAL_HYPER 					(11)		//かわいさ勲章(ハイパー)AGBコンテスト
#define RIBBON_CUTEMEDAL_MASTER 					(12)		//かわいさ勲章(マスター)AGBコンテスト
#define RIBBON_CLEVERMEDAL_NORMAL 					(13)		//かしこさ勲章(ノーマル)AGBコンテスト
#define RIBBON_CLEVERMEDAL_SUPER 					(14)		//かしこさ勲章(スーパー)AGBコンテスト
#define RIBBON_CLEVERMEDAL_HYPER 					(15)		//かしこさ勲章(ハイパー)AGBコンテスト
#define RIBBON_CLEVERMEDAL_MASTER 					(16)		//かしこさ勲章(マスター)AGBコンテスト
#define RIBBON_STRONGMEDAL_NORMAL 					(17)		//たくましさ勲章(ノーマル)AGBコンテスト
#define RIBBON_STRONGMEDAL_SUPER 					(18)		//たくましさ勲章(スーパー)AGBコンテスト
#define RIBBON_STRONGMEDAL_HYPER 					(19)		//たくましさ勲章(ハイパー)AGBコンテスト
#define RIBBON_STRONGMEDAL_MASTER 					(20)		//たくましさ勲章(マスター)AGBコンテスト
#define RIBBON_WINNING_RIBBON						(21)		//ウィニングリボン
#define RIBBON_VICTORY_RIBBON						(22)		//ビクトリーリボン
#define RIBBON_BROMIDE_RIBBON						(23)		//ブロマイドリボン
#define RIBBON_GANBA_RIBBON						(24)		//がんばリボン
#define RIBBON_MARINE_RIBBON						(25)		//マリンリボン
#define RIBBON_LAND_RIBBON							(26)		//ランドリボン
#define RIBBON_SKY_RIBBON							(27)		//スカイリボン
#define RIBBON_COUNTRY_RIBBON						(28)		//カントリーリボン
#define RIBBON_NATIONAL_RIBBON 					(29)		//ナショナルリボン
#define RIBBON_EARTH_RIBBON						(30)		//アースリボン
#define RIBBON_WORLD_RIBBON						(31)		//ワールドリボン
#define RIBBON_SINOU_CHAMP_RIBBON 					(32)		//シンオウチャンプリボン
#define RIBBON_TRIAL_STYLEMEDAL_NORMAL 			(33)		//かっこよさ勲章(ノーマル)トライアル
#define RIBBON_TRIAL_STYLEMEDAL_SUPER 				(34)		//かっこよさ勲章(スーパー)トライアル
#define RIBBON_TRIAL_STYLEMEDAL_HYPER 				(35)		//かっこよさ勲章(ハイパー)トライアル
#define RIBBON_TRIAL_STYLEMEDAL_MASTER 			(36)		//かっこよさ勲章(マスター)トライアル
#define RIBBON_TRIAL_BEAUTIFULMEDAL_NORMAL			(37)		//うつくしさ勲章(ノーマル)トライアル
#define RIBBON_TRIAL_BEAUTIFULMEDAL_SUPER 			(38)		//うつくしさ勲章(スーパー)トライアル
#define RIBBON_TRIAL_BEAUTIFULMEDAL_HYPER 			(39)		//うつくしさ勲章(ハイパー)トライアル
#define RIBBON_TRIAL_BEAUTIFULMEDAL_MASTER			(40)		//うつくしさ勲章(マスター)トライアル
#define RIBBON_TRIAL_CUTEMEDAL_NORMAL 				(41)		//かわいさ勲章(ノーマル)トライアル
#define RIBBON_TRIAL_CUTEMEDAL_SUPER 				(42)		//かわいさ勲章(スーパー)トライアル
#define RIBBON_TRIAL_CUTEMEDAL_HYPER 				(43)		//かわいさ勲章(ハイパー)トライアル
#define RIBBON_TRIAL_CUTEMEDAL_MASTER 				(44)		//かわいさ勲章(マスター)トライアル
#define RIBBON_TRIAL_CLEVERMEDAL_NORMAL 			(45)		//かしこさ勲章(ノーマル)トライアル
#define RIBBON_TRIAL_CLEVERMEDAL_SUPER 			(46)		//かしこさ勲章(スーパー)トライアル
#define RIBBON_TRIAL_CLEVERMEDAL_HYPER 			(47)		//かしこさ勲章(ハイパー)トライアル
#define RIBBON_TRIAL_CLEVERMEDAL_MASTER 			(48)		//かしこさ勲章(マスター)トライアル
#define RIBBON_TRIAL_STRONGMEDAL_NORMAL 			(49)		//たくましさ勲章(ノーマル)トライアル
#define RIBBON_TRIAL_STRONGMEDAL_SUPER 			(50)		//たくましさ勲章(スーパー)トライアル
#define RIBBON_TRIAL_STRONGMEDAL_HYPER 			(51)		//たくましさ勲章(ハイパー)トライアル
#define RIBBON_TRIAL_STRONGMEDAL_MASTER 			(52)		//たくましさ勲章(マスター)トライアル
#define RIBBON_SINOU_BATTLE_TOWER_TTWIN_FIRST		(53)		//シンオウバトルタワータワータイクーン勝利1回目
#define RIBBON_SINOU_BATTLE_TOWER_TTWIN_SECOND		(54)		//シンオウバトルタワータワータイクーン勝利2回目
#define RIBBON_SINOU_BATTLE_TOWER_2VS2_WIN50		(55)		//シンオウバトルタワータワーダブル50連勝
#define RIBBON_SINOU_BATTLE_TOWER_AIMULTI_WIN50	(56)		//シンオウバトルタワータワーAIマルチ50連勝
#define RIBBON_SINOU_BATTLE_TOWER_SIOMULTI_WIN50 	(57)		//シンオウバトルタワータワー通信マルチ50連勝
#define RIBBON_SINOU_BATTLE_TOWER_WIFI_RANK5 		(58)		//シンオウバトルタワーWIFIランク５入り
#define RIBBON_SINOU_SYAKKI_RIBBON 				(59)		//シンオウしゃっきリボン
#define RIBBON_SINOU_DOKKI_RIBBON 					(60)		//シンオウどっきリボン
#define RIBBON_SINOU_SYONBO_RIBBON 				(61)		//シンオウしょんぼリボン
#define RIBBON_SINOU_UKKA_RIBBON 					(62)		//シンオウうっかリボン
#define RIBBON_SINOU_SUKKI_RIBBON 					(63)		//シンオウすっきリボン
#define RIBBON_SINOU_GUSSU_RIBBON 					(64)		//シンオウぐっすリボン
#define RIBBON_SINOU_NIKKO_RIBBON 					(65)		//シンオウにっこリボン
#define RIBBON_SINOU_GORGEOUS_RIBBON 				(66)		//シンオウゴージャスリボン
#define RIBBON_SINOU_ROYAL_RIBBON 					(67)		//シンオウロイヤルリボン
#define RIBBON_SINOU_GORGEOUSROYAL_RIBBON 			(68)		//シンオウゴージャスロイヤルリボン
#define RIBBON_SINOU_ASHIATO_RIBBON 				(69)		//シンオウあしあとリボン
#define RIBBON_SINOU_RECORD_RIBBON 				(70)		//シンオウレコードリボン
#define RIBBON_SINOU_HISTORY_RIBBON 				(71)		//シンオウヒストリーリボン
#define RIBBON_SINOU_LEGEND_RIBBON 				(72)		//シンオウレジェンドリボン
#define RIBBON_SINOU_RED_RIBBON 					(73)		//シンオウレッドリボン
#define RIBBON_SINOU_GREEN_RIBBON 					(74)		//シンオウグリーンリボン
#define RIBBON_SINOU_BLUE_RIBBON 					(75)		//シンオウブルーリボン
#define RIBBON_SINOU_FESTIVAL_RIBBON 				(76)		//シンオウフェスティバルリボン
#define RIBBON_SINOU_CARNIVAL_RIBBON 				(77)		//シンオウカーニバルリボン
#define RIBBON_SINOU_CLASSIC_RIBBON 				(78)		//シンオウクラシックリボン
#define RIBBON_SINOU_PREMIERE_RIBBON 				(79)		//シンオウプレミアリボン

