//============================================================================================
//	AGBのアイテムID（エメラルドより）
//============================================================================================
#define	AGB_ITEM_DUMMY_DATA				0		// ダミーデータ
#define	AGB_ITEM_MASUTAABOORU			1		// マスターボール
#define	AGB_ITEM_HAIPAABOORU			2		// ハイパーボール
#define	AGB_ITEM_SUUPAABOORU			3		// スーパーボール
#define	AGB_ITEM_MONSUTAABOORU			4		// モンスターボール
#define	AGB_ITEM_SAFARIBOORU			5		// サファリボール
#define	AGB_ITEM_NETTOBOORU				6		// ネットボール
#define	AGB_ITEM_DAIBUBOORU				7		// ダイブボール
#define	AGB_ITEM_NESUTOBOORU			8		// ネストボール
#define	AGB_ITEM_RIPIITOBOORU			9		// リピートボール
#define	AGB_ITEM_TAIMAABOORU			10		// タイマーボール
#define	AGB_ITEM_GOOZYASUBOORU			11		// ゴージャスボール
#define	AGB_ITEM_PUREMIABOORU			12		// プレミアボール
#define	AGB_ITEM_KIZUGUSURI				13		// キズぐすり
#define	AGB_ITEM_DOKUKESI				14		// どくけし
#define	AGB_ITEM_YAKEDONAOSI			15		// やけどなおし
#define	AGB_ITEM_KOORINAOSI				16		// こおりなおし
#define	AGB_ITEM_NEMUKEZAMASI			17		// ねむけざまし
#define	AGB_ITEM_MAHINAOSI				18		// まひなおし
#define	AGB_ITEM_KAIHUKUNOKUSURI		19		// かいふくのくすり
#define	AGB_ITEM_MANTANNOKUSURI			20		// まんたんのくすり
#define	AGB_ITEM_SUGOIKIZUGUSURI		21		// すごいキズぐすり
#define	AGB_ITEM_IIKIZUGUSURI			22		// いいキズぐすり
#define	AGB_ITEM_NANDEMONAOSI			23		// なんでもなおし
#define	AGB_ITEM_GENKINOKAKERA			24		// げんきのかけら
#define	AGB_ITEM_GENKINOKATAMARI		25		// げんきのかたまり
#define	AGB_ITEM_OISIIMIZU				26		// おいしいみず
#define	AGB_ITEM_SAIKOSOODA				27		// サイコソーダ
#define	AGB_ITEM_MIKKUSUORE				28		// ミックスオレ
#define	AGB_ITEM_MOOMOOMIRUKU			29		// モーモーミルク
#define	AGB_ITEM_TIKARANOKONA			30		// ちからのこな
#define	AGB_ITEM_TIKARANONEKKO			31		// ちからのねっこ
#define	AGB_ITEM_BANNOUGONA				32		// ばんのうごな
#define	AGB_ITEM_HUKKATUSOU				33		// ふっかつそう
#define	AGB_ITEM_PIIPIIEIDO				34		// ピーピーエイド
#define	AGB_ITEM_PIIPIIRIKABAA			35		// ピーピーリカバー
#define	AGB_ITEM_PIIPIIEIDAA			36		// ピーピーエイダー
#define	AGB_ITEM_PIIPIIMAKKUSU			37		// ピーピーマックス
#define	AGB_ITEM_HUENSENBEI				38		// フエンせんべい
#define	AGB_ITEM_AOIBIIDORO				39		// あおいビードロ
#define	AGB_ITEM_KIIROBIIDORO			40		// きいろビードロ
#define	AGB_ITEM_AKAIBIIDORO			41		// あかいビードロ
#define	AGB_ITEM_KUROIBIIDORO			42		// くろいビードロ
#define	AGB_ITEM_SIROIBIIDORO			43		// しろいビードロ
#define	AGB_ITEM_KINOMIZYUUSU			44		// きのみジュース
#define	AGB_ITEM_SEINARUHAI				45		// せいなるはい
#define	AGB_ITEM_ASASENOSIO				46		// あさせのしお
#define	AGB_ITEM_ASASENOKAIGARA			47		// あさせのかいがら
#define	AGB_ITEM_AKAIKAKERA				48		// あかいかけら
#define	AGB_ITEM_AOIKAKERA				49		// あおいかけら
#define	AGB_ITEM_KIIROIKAKERA			50		// きいろいかけら
#define	AGB_ITEM_MIDORINOKAKERA			51		// みどりのかけら
#define	AGB_ITEM_MAKKUSUAPPU			63		// マックスアップ
#define	AGB_ITEM_TAURIN					64		// タウリン
#define	AGB_ITEM_BUROMUHEKISIN			65		// ブロムヘキシン
#define	AGB_ITEM_INDOMETASIN			66		// インドメタシン
#define	AGB_ITEM_RIZOTIUMU				67		// リゾチウム
#define	AGB_ITEM_HUSIGINAAME			68		// ふしぎなアメ
#define	AGB_ITEM_POINTOAPPU				69		// ポイントアップ
#define	AGB_ITEM_KITOSAN				70		// キトサン
#define	AGB_ITEM_POINTOMAKKUSU			71		// ポイントマックス
#define	AGB_ITEM_EFEKUTOGAADO			73		// エフェクトガード
#define	AGB_ITEM_KURITHIKATTAA			74		// クリティカッター
#define	AGB_ITEM_PURASUPAWAA			75		// プラスパワー
#define	AGB_ITEM_DHIFENDAA				76		// ディフェンダー
#define	AGB_ITEM_SUPIIDAA				77		// スピーダー
#define	AGB_ITEM_YOKUATAARU				78		// ヨクアタール
#define	AGB_ITEM_SUPESYARUAPPU			79		// スペシャルアップ
#define	AGB_ITEM_PIPPININGYOU			80		// ピッピにんぎょう
#define	AGB_ITEM_ENEKONOSIPPO			81		// エネコのシッポ
#define	AGB_ITEM_SIRUBAASUPUREE			83		// シルバースプレー
#define	AGB_ITEM_GOORUDOSUPUREE			84		// ゴールドスプレー
#define	AGB_ITEM_ANANUKENOHIMO			85		// あなぬけのヒモ
#define	AGB_ITEM_MUSIYOKESUPUREE		86		// むしよけスプレー
#define	AGB_ITEM_TAIYOUNOISI			93		// たいようのいし
#define	AGB_ITEM_TUKINOISI				94		// つきのいし
#define	AGB_ITEM_HONOONOISI				95		// ほのおのいし
#define	AGB_ITEM_KAMINARINOISI			96		// かみなりのいし
#define	AGB_ITEM_MIZUNOISI				97		// みずのいし
#define	AGB_ITEM_RIIHUNOISI				98		// リーフのいし
#define	AGB_ITEM_TIISANAKINOKO			103		// ちいさなキノコ
#define	AGB_ITEM_OOKINAKINOKO			104		// おおきなキノコ
#define	AGB_ITEM_SINZYU					106		// しんじゅ
#define	AGB_ITEM_OOKINASINZYU			107		// おおきなしんじゅ
#define	AGB_ITEM_HOSINOSUNA				108		// ほしのすな
#define	AGB_ITEM_HOSINOKAKERA			109		// ほしのかけら
#define	AGB_ITEM_KINNOTAMA				110		// きんのたま
#define	AGB_ITEM_HAATONOUROKO			111		// ハートのウロコ
#define	AGB_ITEM_ORENZIMEERU			121		// オレンジメール
#define	AGB_ITEM_HAABAAMEERU			122		// ハーバーメール
#define	AGB_ITEM_KIRAKIRAMEERU			123		// キラキラメール
#define	AGB_ITEM_MEKANIKARUMEERU		124		// メカニカルメール
#define	AGB_ITEM_UDDHIMEERU				125		// ウッディメール
#define	AGB_ITEM_KUROSUMEERU			126		// クロスメール
#define	AGB_ITEM_TOREZYAAMEERU			127		// トレジャーメール
#define	AGB_ITEM_SYADOOMEERU			128		// シャドーメール
#define	AGB_ITEM_TOROPIKARUMEERU		129		// トロピカルメール
#define	AGB_ITEM_DORIIMUMEERU			130		// ドリームメール
#define	AGB_ITEM_MIRAKURUMEERU			131		// ミラクルメール
#define	AGB_ITEM_RETOROMEERU			132		// レトロメール
#define	AGB_ITEM_KURABONOMI				133		// クラボのみ
#define	AGB_ITEM_KAGONOMI				134		// カゴのみ
#define	AGB_ITEM_MOMONNOMI				135		// モモンのみ
#define	AGB_ITEM_TIIGONOMI				136		// チーゴのみ
#define	AGB_ITEM_NANASINOMI				137		// ナナシのみ
#define	AGB_ITEM_HIMERINOMI				138		// ヒメリのみ
#define	AGB_ITEM_ORENNOMI				139		// オレンのみ
#define	AGB_ITEM_KIINOMI				140		// キーのみ
#define	AGB_ITEM_RAMUNOMI				141		// ラムのみ
#define	AGB_ITEM_OBONNOMI				142		// オボンのみ
#define	AGB_ITEM_FIRANOMI				143		// フィラのみ
#define	AGB_ITEM_UINOMI					144		// ウイのみ
#define	AGB_ITEM_MAGONOMI				145		// マゴのみ
#define	AGB_ITEM_BANZINOMI				146		// バンジのみ
#define	AGB_ITEM_IANOMI					147		// イアのみ
#define	AGB_ITEM_ZURINOMI				148		// ズリのみ
#define	AGB_ITEM_BURIINOMI				149		// ブリーのみ
#define	AGB_ITEM_NANANOMI				150		// ナナのみ
#define	AGB_ITEM_SESINANOMI				151		// セシナのみ
#define	AGB_ITEM_PAIRUNOMI				152		// パイルのみ
#define	AGB_ITEM_ZAROKUNOMI				153		// ザロクのみ
#define	AGB_ITEM_NEKOBUNOMI				154		// ネコブのみ
#define	AGB_ITEM_TAPORUNOMI				155		// タポルのみ
#define	AGB_ITEM_ROMENOMI				156		// ロメのみ
#define	AGB_ITEM_UBUNOMI				157		// ウブのみ
#define	AGB_ITEM_MATOMANOMI				158		// マトマのみ
#define	AGB_ITEM_MOKOSINOMI				159		// モコシのみ
#define	AGB_ITEM_GOSUNOMI				160		// ゴスのみ
#define	AGB_ITEM_RABUTANOMI				161		// ラブタのみ
#define	AGB_ITEM_NOMERUNOMI				162		// ノメルのみ
#define	AGB_ITEM_NOWAKINOMI				163		// ノワキのみ
#define	AGB_ITEM_SIIYANOMI				164		// シーヤのみ
#define	AGB_ITEM_KAISUNOMI				165		// カイスのみ
#define	AGB_ITEM_DORINOMI				166		// ドリのみ
#define	AGB_ITEM_BERIBUNOMI				167		// ベリブのみ
#define	AGB_ITEM_TIIRANOMI				168		// チイラのみ
#define	AGB_ITEM_RYUGANOMI				169		// リュガのみ
#define	AGB_ITEM_KAMURANOMI				170		// カムラのみ
#define	AGB_ITEM_YATAPINOMI				171		// ヤタピのみ
#define	AGB_ITEM_ZUANOMI				172		// ズアのみ
#define	AGB_ITEM_SANNOMI				173		// サンのみ
#define	AGB_ITEM_SUTAANOMI				174		// スターのみ
#define	AGB_ITEM_NAZONOMI				175		// ナゾのみ
#define	AGB_ITEM_HIKARINOKONA			179		// ひかりのこな
#define	AGB_ITEM_SIROIHAABU				180		// しろいハーブ
#define	AGB_ITEM_KYOUSEIGIPUSU			181		// きょうせいギプス
#define	AGB_ITEM_GAKUSYUUSOUTI			182		// がくしゅうそうち
#define	AGB_ITEM_SENSEINOTUME			183		// せんせいのツメ
#define	AGB_ITEM_YASURAGINOSUZU			184		// やすらぎのすず
#define	AGB_ITEM_MENTARUHAABU			185		// メンタルハーブ
#define	AGB_ITEM_KODAWARIHATIMAKI		186		// こだわりハチマキ
#define	AGB_ITEM_OUZYANOSIRUSI			187		// おうじゃのしるし
#define	AGB_ITEM_GINNOKONA				188		// ぎんのこな
#define	AGB_ITEM_OMAMORIKOBAN			189		// おまもりこばん
#define	AGB_ITEM_KIYOMENOOHUDA			190		// きよめのおふだ
#define	AGB_ITEM_KOKORONOSIZUKU			191		// こころのしずく
#define	AGB_ITEM_SINKAINOKIBA			192		// しんかいのキバ
#define	AGB_ITEM_SINKAINOUROKO			193		// しんかいのウロコ
#define	AGB_ITEM_KEMURIDAMA				194		// けむりだま
#define	AGB_ITEM_KAWARAZUNOISI			195		// かわらずのいし
#define	AGB_ITEM_KIAINOHATIMAKI			196		// きあいのハチマキ
#define	AGB_ITEM_SIAWASETAMAGO			197		// しあわせタマゴ
#define	AGB_ITEM_PINTORENZU				198		// ピントレンズ
#define	AGB_ITEM_METARUKOOTO			199		// メタルコート
#define	AGB_ITEM_TABENOKOSI				200		// たべのこし
#define	AGB_ITEM_RYUUNOUROKO			201		// りゅうのウロコ
#define	AGB_ITEM_DENKIDAMA				202		// でんきだま
#define	AGB_ITEM_YAWARAKAISUNA			203		// やわらかいすな
#define	AGB_ITEM_KATAIISI				204		// かたいいし
#define	AGB_ITEM_KISEKINOTANE			205		// きせきのタネ
#define	AGB_ITEM_KUROIMEGANE			206		// くろいメガネ
#define	AGB_ITEM_KUROOBI				207		// くろおび
#define	AGB_ITEM_ZISYAKU				208		// じしゃく
#define	AGB_ITEM_SINPINOSIZUKU			209		// しんぴのしずく
#define	AGB_ITEM_SURUDOIKUTIBASI		210		// するどいくちばし
#define	AGB_ITEM_DOKUBARI				211		// どくバリ
#define	AGB_ITEM_TOKENAIKOORI			212		// とけないこおり
#define	AGB_ITEM_NOROINOOHUDA			213		// のろいのおふだ
#define	AGB_ITEM_MAGATTASUPUUN			214		// まがったスプーン
#define	AGB_ITEM_MOKUTAN				215		// もくたん
#define	AGB_ITEM_RYUUNOKIBA				216		// りゅうのキバ
#define	AGB_ITEM_SIRUKUNOSUKAAHU		217		// シルクのスカーフ
#define	AGB_ITEM_APPUGUREEDO			218		// アップグレード
#define	AGB_ITEM_KAIGARANOSUZU			219		// かいがらのすず
#define	AGB_ITEM_USIONOOKOU				220		// うしおのおこう
#define	AGB_ITEM_NONKINOOKOU			221		// のんきのおこう
#define	AGB_ITEM_RAKKIIPANTI			222		// ラッキーパンチ
#define	AGB_ITEM_METARUPAUDAA			223		// メタルパウダー
#define	AGB_ITEM_HUTOIHONE				224		// ふといホネ
#define	AGB_ITEM_NAGANEGI				225		// ながねぎ
#define	AGB_ITEM_AKAIBANDANA			254		// あかいバンダナ
#define	AGB_ITEM_AOIBANDANA				255		// あおいバンダナ
#define	AGB_ITEM_PINKUNOBANDANA			256		// ピンクのバンダナ
#define	AGB_ITEM_MIDORINOBANDANA		257		// みどりのバンダナ
#define	AGB_ITEM_KIIRONOBANDANA			258		// きいろのバンダナ
#define	AGB_ITEM_MAHHAZITENSYA			259		// マッハじてんしゃ
#define	AGB_ITEM_KOINKEESU				260		// コインケース
#define	AGB_ITEM_DAUZINGUMASIN			261		// ダウジングマシン
#define	AGB_ITEM_BORONOTURIZAO			262		// ボロのつりざお
#define	AGB_ITEM_IITURIZAO				263		// いいつりざお
#define	AGB_ITEM_SUGOITURIZAO			264		// すごいつりざお
#define	AGB_ITEM_HUNENOTIKETTO			265		// ふねのチケット
#define	AGB_ITEM_KONTESUTOPASU			266		// コンテストパス
#define	AGB_ITEM_HOERUKOZYOURO			268		// ホエルコじょうろ
#define	AGB_ITEM_DEBONNONIMOTU			269		// デボンのにもつ
#define	AGB_ITEM_HAIBUKURO				270		// はいぶくろ
#define	AGB_ITEM_TIKANOKAGI				271		// ちかのカギ
#define	AGB_ITEM_DAATOZITENSYA			272		// ダートじてんしゃ
#define	AGB_ITEM_POROKKUKEESU			273		// ポロックケース
#define	AGB_ITEM_DAIGOHENOTEGAMI		274		// ダイゴへのてがみ
#define	AGB_ITEM_MUGENNOTIKETTO			275		// むげんのチケット
#define	AGB_ITEM_BENIIRONOTAMA			276		// べにいろのたま
#define	AGB_ITEM_AIIRONOTAMA			277		// あいいろのたま
#define	AGB_ITEM_TANTIKI				278		// たんちき
#define	AGB_ITEM_GOOGOOGOOGURU			279		// ゴーゴーゴーグル
#define	AGB_ITEM_INSEKI					280		// いんせき
#define	AGB_ITEM_1GOUSITUNOKAGI			281		// １ごうしつのカギ
#define	AGB_ITEM_2GOUSITUNOKAGI			282		// ２ごうしつのカギ
#define	AGB_ITEM_4GOUSITUNOKAGI			283		// ４ごうしつのカギ
#define	AGB_ITEM_6GOUSITUNOKAGI			284		// ６ごうしつのカギ
#define	AGB_ITEM_SOUKONOKAGI			285		// そうこのカギ
#define	AGB_ITEM_NEKKONOKASEKI			286		// ねっこのカセキ
#define	AGB_ITEM_TUMENOKASEKI			287		// ツメのカセキ
#define	AGB_ITEM_DEBONSUKOOPU			288		// デボンスコープ
#define	AGB_ITEM_WAZAMASIN01			289		// わざマシン０１
#define	AGB_ITEM_WAZAMASIN02			290		// わざマシン０２
#define	AGB_ITEM_WAZAMASIN03			291		// わざマシン０３
#define	AGB_ITEM_WAZAMASIN04			292		// わざマシン０４
#define	AGB_ITEM_WAZAMASIN05			293		// わざマシン０５
#define	AGB_ITEM_WAZAMASIN06			294		// わざマシン０６
#define	AGB_ITEM_WAZAMASIN07			295		// わざマシン０７
#define	AGB_ITEM_WAZAMASIN08			296		// わざマシン０８
#define	AGB_ITEM_WAZAMASIN09			297		// わざマシン０９
#define	AGB_ITEM_WAZAMASIN10			298		// わざマシン１０
#define	AGB_ITEM_WAZAMASIN11			299		// わざマシン１１
#define	AGB_ITEM_WAZAMASIN12			300		// わざマシン１２
#define	AGB_ITEM_WAZAMASIN13			301		// わざマシン１３
#define	AGB_ITEM_WAZAMASIN14			302		// わざマシン１４
#define	AGB_ITEM_WAZAMASIN15			303		// わざマシン１５
#define	AGB_ITEM_WAZAMASIN16			304		// わざマシン１６
#define	AGB_ITEM_WAZAMASIN17			305		// わざマシン１７
#define	AGB_ITEM_WAZAMASIN18			306		// わざマシン１８
#define	AGB_ITEM_WAZAMASIN19			307		// わざマシン１９
#define	AGB_ITEM_WAZAMASIN20			308		// わざマシン２０
#define	AGB_ITEM_WAZAMASIN21			309		// わざマシン２１
#define	AGB_ITEM_WAZAMASIN22			310		// わざマシン２２
#define	AGB_ITEM_WAZAMASIN23			311		// わざマシン２３
#define	AGB_ITEM_WAZAMASIN24			312		// わざマシン２４
#define	AGB_ITEM_WAZAMASIN25			313		// わざマシン２５
#define	AGB_ITEM_WAZAMASIN26			314		// わざマシン２６
#define	AGB_ITEM_WAZAMASIN27			315		// わざマシン２７
#define	AGB_ITEM_WAZAMASIN28			316		// わざマシン２８
#define	AGB_ITEM_WAZAMASIN29			317		// わざマシン２９
#define	AGB_ITEM_WAZAMASIN30			318		// わざマシン３０
#define	AGB_ITEM_WAZAMASIN31			319		// わざマシン３１
#define	AGB_ITEM_WAZAMASIN32			320		// わざマシン３２
#define	AGB_ITEM_WAZAMASIN33			321		// わざマシン３３
#define	AGB_ITEM_WAZAMASIN34			322		// わざマシン３４
#define	AGB_ITEM_WAZAMASIN35			323		// わざマシン３５
#define	AGB_ITEM_WAZAMASIN36			324		// わざマシン３６
#define	AGB_ITEM_WAZAMASIN37			325		// わざマシン３７
#define	AGB_ITEM_WAZAMASIN38			326		// わざマシン３８
#define	AGB_ITEM_WAZAMASIN39			327		// わざマシン３９
#define	AGB_ITEM_WAZAMASIN40			328		// わざマシン４０
#define	AGB_ITEM_WAZAMASIN41			329		// わざマシン４１
#define	AGB_ITEM_WAZAMASIN42			330		// わざマシン４２
#define	AGB_ITEM_WAZAMASIN43			331		// わざマシン４３
#define	AGB_ITEM_WAZAMASIN44			332		// わざマシン４４
#define	AGB_ITEM_WAZAMASIN45			333		// わざマシン４５
#define	AGB_ITEM_WAZAMASIN46			334		// わざマシン４６
#define	AGB_ITEM_WAZAMASIN47			335		// わざマシン４７
#define	AGB_ITEM_WAZAMASIN48			336		// わざマシン４８
#define	AGB_ITEM_WAZAMASIN49			337		// わざマシン４９
#define	AGB_ITEM_WAZAMASIN50			338		// わざマシン５０
#define	AGB_ITEM_HIDENMASIN01			339		// ひでんマシン０１
#define	AGB_ITEM_HIDENMASIN02			340		// ひでんマシン０２
#define	AGB_ITEM_HIDENMASIN03			341		// ひでんマシン０３
#define	AGB_ITEM_HIDENMASIN04			342		// ひでんマシン０４
#define	AGB_ITEM_HIDENMASIN05			343		// ひでんマシン０５
#define	AGB_ITEM_HIDENMASIN06			344		// ひでんマシン０６
#define	AGB_ITEM_HIDENMASIN07			345		// ひでんマシン０７
#define	AGB_ITEM_HIDENMASIN08			346		// ひでんマシン０８
#define	AGB_ITEM_OTODOKEMONO			349		// おとどけもの
#define	AGB_ITEM_POKEMONNOHUE			350		// ポケモンのふえ
#define	AGB_ITEM_HIMITUNOKAGI			351		// ひみつのカギ
#define	AGB_ITEM_HIKIKAEKEN				352		// ひきかえけん
#define	AGB_ITEM_KINNOIREBA				353		// きんのいれば
#define	AGB_ITEM_HIMITUNOKOHAKU			354		// ひみつのコハク
#define	AGB_ITEM_KAADOKII				355		// カードキー
#define	AGB_ITEM_EREBEETANOKAGI			356		// エレベータのカギ
#define	AGB_ITEM_KAINOKASEKI			357		// かいのカセキ
#define	AGB_ITEM_KOURANOKASEKI			358		// こうらのカセキ
#define	AGB_ITEM_SIRUHUSUKOOPU			359		// シルフスコープ
#define	AGB_ITEM_ZITENSYA				360		// じてんしゃ
#define	AGB_ITEM_TAUNMAPPU				361		// タウンマップ
#define	AGB_ITEM_BATORUSAATYAA			362		// バトルサーチャー
#define	AGB_ITEM_BOISUTHEKKAA			363		// ボイスチェッカー
#define	AGB_ITEM_WAZAMASINKEESU			364		// わざマシンケース
#define	AGB_ITEM_KINOMIBUKURO			365		// きのみぶくろ
#define	AGB_ITEM_OSIETEREBI				366		// おしえテレビ
#define	AGB_ITEM_TORAIPASU				367		// トライパス
#define	AGB_ITEM_REINBOOPASU			368		// レインボーパス
#define	AGB_ITEM_OTYA					369		// おちゃ
#define	AGB_ITEM_SINPINOTIKETTO			370		// しんぴのチケット
#define	AGB_ITEM_OORORATIKETTO			371		// オーロラチケット
#define	AGB_ITEM_KONAIRE				372		// こないれ
#define	AGB_ITEM_RUBII					373		// ルビー
#define	AGB_ITEM_SAFAIA					374		// サファイア
#define	AGB_ITEM_MAGUMANOSIRUSI			375		// マグマのしるし
#define	AGB_ITEM_HURUBITAKAIZU			376		// ふるびたかいず

#define	AGB_ITEM_DATA_MAX				376		// アイテム最大数
