/*****************************************************************************
	Archive file index definition.
	File: poketch.naix

	This file was created by NINTENDO NITRO-System Archiver.

	Update:2006-06-26T17:57:17
 *****************************************************************************/

#ifndef NARC_POKETCH_NAIX_
#define NARC_POKETCH_NAIX_

enum {
	NARC_poketch_app_nclr = 0,
	NARC_poketch_colorapp_nclr = 1,
	NARC_poketch_numobj_ncgr = 2,
	NARC_poketch_numobj_ncer = 3,
	NARC_poketch_numobj_nanr = 4,
	NARC_poketch_pokeicon_ncer = 5,
	NARC_poketch_pokeicon_nanr = 6,
	NARC_poketch_simple_ncgr = 7,
	NARC_poketch_test_ncgr = 8,
	NARC_poketch_test_nclr = 9,
	NARC_poketch_before_lz_ncgr = 10,
	NARC_poketch_before_lz_nscr = 11,
	NARC_poketch_before_nclr = 12,
	NARC_poketch_board_nclr = 13,
	NARC_poketch_board_ncgr = 14,
	NARC_poketch_board_nscr = 15,
	NARC_poketch_dentaku_ncgr = 16,
	NARC_poketch_dentaku_nscr = 17,
	NARC_poketch_stop_ncer = 18,
	NARC_poketch_stop_nanr = 19,
	NARC_poketch_stop_nscr = 20,
	NARC_poketch_stopbg_ncgr = 21,
	NARC_poketch_stopobj_ncgr = 22,
	NARC_poketch_dwatch_ncgr = 23,
	NARC_poketch_dwatch_nscr = 24,
	NARC_poketch_dwatch_num_nscr = 25,
	NARC_poketch_awatch_nscr = 26,
	NARC_poketch_awatch_ncer = 27,
	NARC_poketch_awatch_nanr = 28,
	NARC_poketch_awatch_obj_ncgr = 29,
	NARC_poketch_memo_ncgr = 30,
	NARC_poketch_memo_nscr = 31,
	NARC_poketch_memo_obj_ncgr = 32,
	NARC_poketch_memo_button_ncer = 33,
	NARC_poketch_memo_button_nanr = 34,
	NARC_poketch_natsuki_ncgr = 35,
	NARC_poketch_natsuki_ncer = 36,
	NARC_poketch_natsuki_nanr = 37,
	NARC_poketch_sonar_nscr = 38,
	NARC_poketch_sonar_ncgr = 39,
	NARC_poketch_sonar_ncer = 40,
	NARC_poketch_sonar_nanr = 41,
	NARC_poketch_sonar_obj_ncgr = 42,
	NARC_poketch_counter_lz_nscr = 43,
	NARC_poketch_counter_bg_lz_ncgr = 44,
	NARC_poketch_counter_lz_ncer = 45,
	NARC_poketch_counter_lz_nanr = 46,
	NARC_poketch_counter_obj_lz_ncgr = 47,
	NARC_poketch_walk_lz_nscr = 48,
	NARC_poketch_walk_lz_ncgr = 49,
	NARC_poketch_walk_lz_ncer = 50,
	NARC_poketch_walk_lz_nanr = 51,
	NARC_poketch_walk_obj_lz_ncgr = 52,
	NARC_poketch_coin_nscr = 53,
	NARC_poketch_coin_ncgr = 54,
	NARC_poketch_coin_ncer = 55,
	NARC_poketch_coin_nanr = 56,
	NARC_poketch_coin_obj_ncgr = 57,
	NARC_poketch_traner_lz_nscr = 58,
	NARC_poketch_traner_lz_ncgr = 59,
	NARC_poketch_aisyo_lz_nscr = 60,
	NARC_poketch_aisyo_lz_ncgr = 61,
	NARC_poketch_aisyo_lz_ncer = 62,
	NARC_poketch_aisyo_lz_nanr = 63,
	NARC_poketch_aisyo_obj_lz_ncgr = 64,
	NARC_poketch_changer_lz_nscr = 65,
	NARC_poketch_changer_lz_ncgr = 66,
	NARC_poketch_changer_lz_ncer = 67,
	NARC_poketch_changer_lz_nanr = 68,
	NARC_poketch_changer_obj_lz_ncgr = 69,
	NARC_poketch_love_lz_nscr = 70,
	NARC_poketch_love_lz_ncgr = 71,
	NARC_poketch_love_lz_ncer = 72,
	NARC_poketch_love_lz_nanr = 73,
	NARC_poketch_love_obj_lz_ncgr = 74,
	NARC_poketch_alarm_lz_nscr = 75,
	NARC_poketch_alarm_lz_ncgr = 76,
	NARC_poketch_alarm_lz_ncer = 77,
	NARC_poketch_alarm_lz_nanr = 78,
	NARC_poketch_alarm_obj_lz_ncgr = 79,
	NARC_poketch_sodate_lz_nscr = 80,
	NARC_poketch_sodate_lz_ncgr = 81,
	NARC_poketch_sodate_lz_ncer = 82,
	NARC_poketch_sodate_lz_nanr = 83,
	NARC_poketch_sodate_obj_lz_ncgr = 84,
	NARC_poketch_rlt_lz_nscr = 85,
	NARC_poketch_rlt_lz_ncgr = 86,
	NARC_poketch_rlt_lz_ncer = 87,
	NARC_poketch_rlt_lz_nanr = 88,
	NARC_poketch_rlt_obj_lz_ncgr = 89,
	NARC_poketch_kitchen_lz_nscr = 90,
	NARC_poketch_kitchen_lz_ncgr = 91,
	NARC_poketch_kitchen_lz_ncer = 92,
	NARC_poketch_kitchen_lz_nanr = 93,
	NARC_poketch_kitchen_obj_lz_ncgr = 94,
	NARC_poketch_tusin_lz_nscr = 95,
	NARC_poketch_tusin_lz_ncgr = 96,
	NARC_poketch_tusin_lz_ncer = 97,
	NARC_poketch_tusin_lz_nanr = 98,
	NARC_poketch_tusin_obj_lz_ncgr = 99,
	NARC_poketch_light_lz_nscr = 100,
	NARC_poketch_light_lz_ncgr = 101,
	NARC_poketch_light_lz_ncer = 102,
	NARC_poketch_light_lz_nanr = 103,
	NARC_poketch_light_obj_lz_ncgr = 104,
	NARC_poketch_list_lz_nscr = 105,
	NARC_poketch_list_lz_ncgr = 106,
	NARC_poketch_list_obj_lz_ncer = 107,
	NARC_poketch_list_obj_lz_nanr = 108,
	NARC_poketch_list_obj_lz_ncgr = 109,
	NARC_poketch_calendar_lz_nscr = 110,
	NARC_poketch_calendar_lz_ncgr = 111,
	NARC_poketch_calendar_lz_ncer = 112,
	NARC_poketch_calendar_lz_nanr = 113,
	NARC_poketch_calendar_obj_lz_ncgr = 114,
	NARC_poketch_pmap_mark_lz_nscr = 115,
	NARC_poketch_pmap_kinomi_lz_nscr = 116,
	NARC_poketch_pmap_lz_ncgr = 117,
	NARC_poketch_pmap_lz_ncer = 118,
	NARC_poketch_pmap_lz_nanr = 119,
	NARC_poketch_pmap_obj_lz_ncgr = 120,
	NARC_poketch_pcount_lz_nscr = 121,
	NARC_poketch_pcount_lz_ncgr = 122,
	NARC_poketch_pcount_lz_ncer = 123,
	NARC_poketch_pcount_lz_nanr = 124,
	NARC_poketch_pcount_obj_lz_ncgr = 125
};

/* NARC_POKETCH_NAIX_ */
#endif
