#define MATTR_ZIMEN_01             0x00 //地面:
#define MATTR_E_KUSA_1             0x02 //草:前方チェックで「いあいぎり」使用可能。草エンカウントのエフェクトあり。
#define MATTR_E_KUSA_2             0x03 //長い草:前方チェックで「いあいぎり」使用可能。長い草エンカウントのエフェクトあり。自転車では通れない。
#define MATTR_E_ZIMEN_01           0x08 //地面エンカウント:通常の地面でエンカウント。主に、ダンジョンで使用。
#define MATTR_ZIMEN_02             0x0a //未使用:徒歩でのみ入れる。ここでは自転車にのれない。
#define MATTR_E_ZIMEN_02           0x0b //屋内エンカウント:通常の地面でエンカウント。分類が「cave」であっても、屋内扱いにして、戦闘画面のエフェクトをルームと同じにします。※「あなぬけのヒモ」や「あなをほる」は使えます。
#define MATTR_ZIMEN_04             0x0c //未使用:ここで戦闘になると、戦闘画面の背景が岩タイプになります。
#define MATTR_POOL_02              0x10 //池:「なみのり」を使用していない場合、前方チェックで「なみのり」使用可能。「なみのり」移動中、波紋ができる。水面に映り込みあり。
#define MATTR_WATERFALL_01         0x13 //滝:下から前方チェックで「たきのぼり」使用可能／「たきのぼり」を使わずに下から入ると、下方向に向きを変えて進入方向へ１歩戻される／上から前方チェックでメッセージ。進入すると下る。
#define MATTR_UMI_01               0x15 //海:「なみのり」を使用していない場合、前方チェックで「なみのり」使用可能。「なみのり」移動中、波紋できない。水面に映り込みなし。
#define MATTR_POOL_01              0x16 //水たまり:水たまりの上を通常移動。映りこみあり。移動すると、足下に水しぶき（ＯＢＪは、mizu1.sch）があがり、波紋もできる。
#define MATTR_ASASE_01             0x17 //浅瀬:浅瀬の上を通常移動。常に足下に水しぶき（ＯＢＪは、mizu1.sch）があり。映りこみなし。移動しても波紋はできないが、水しぶきがバシャバシャとなる。
#define MATTR_ICE_01               0x20 //氷上:真下チェックで進行方向に進み、進入不可能なトリビュートやＯＢＪにぶつかると止まる。映り込みあり。
#define MATTR_SUNA_01              0x21 //砂地:砂地に足跡が残ります（７歩まで）。足跡はＯＢＪ。
#define MATTR_IDOHUKA_01           0x30 //右方向へ移動不可:真下チェックで右方向へ移動不可能
#define MATTR_IDOHUKA_02           0x31 //左方向へ移動不可:真下チェックで左方向へ移動不可能
#define MATTR_IDOHUKA_03           0x32 //上方向へ移動不可:真下チェックで上方向へ移動不可能
#define MATTR_IDOHUKA_04           0x33 //下方向へ移動不可:真下チェックで下方向へ移動不可能
#define MATTR_IDOHUKA_05           0x34 //右・上方向へ移動不可:真下チェックで右・上方向へ移動不可能
#define MATTR_IDOHUKA_06           0x35 //左・上方向へ移動不可:真下チェックで左・上方向へ移動不可能
#define MATTR_IDOHUKA_07           0x36 //右・下方向へ移動不可:真下チェックで右・下方向へ移動不可能
#define MATTR_IDOHUKA_08           0x37 //左・下方向へ移動不可:真下チェックで左・下方向へ移動不可能
#define MATTR_JUMP_01              0x38 //右方向へジャンプ移動:十時キーを右に押すと、前方チェックで右方向にジャンプ移動。着地地点のアトリビュートチェックで、着地エフェクトを出す。着地エフェクトについては「地形効果」のJUMPを参照して下さい。
#define MATTR_JUMP_02              0x39 //左方向へジャンプ移動:十時キーを左に押すと、前方チェックで左方向にジャンプ移動。着地地点のアトリビュートチェックで、着地エフェクトを出す。
#define MATTR_JUMP_03              0x3a //未使用:十時キーを上に押すと、前方チェックで上方向にジャンプ移動。着地地点のアトリビュートチェックで、着地?フェクトを出す。
#define MATTR_JUMP_04              0x3b //下方向へジャンプ移動:十時キーを下に押すと、前方チェックで下方向にジャンプ移動。着地地点のアトリビュートチェックで、着地エフェクトを出す。
#define MATTR_IDO_01               0x40 //右方向へ強制移動:真下チェックで右方向に進み、進入不可能なトリビュートやＯＢＪにぶつかると止まる
#define MATTR_IDO_02               0x41 //左方向へ強制移動:真下チェックで左方向に進み、進入不可能なトリビュートやＯＢＪにぶつかると止まる
#define MATTR_IDO_03               0x42 //上方向へ強制移動:真下チェックで上方向に進み、進入不可能なトリビュートやＯＢＪにぶつかると止まる
#define MATTR_IDO_04               0x43 //下方向へ強制移動:真下チェックで下方向に進み、進入不可能なトリビュートやＯＢＪにぶつかると止まる
#define MATTR_IDO_05               0x44 //未使用:真下チェックで向きは変わらずに右へ１歩押し出される
#define MATTR_IDO_06               0x45 //未使用:真下チェックで向きは変わらずに左へ１歩押し出される
#define MATTR_IDO_07               0x46 //未使用:真下チェックで向きは変わらずに上へ１歩押し出される
#define MATTR_IDO_08               0x47 //未使用:真下チェックで向きは変わらずに下へ１歩押し出される
#define MATTR_IDO_09               0x48 //未使用:真下チェックで進行方向に流されます。氷上と仕様は同じだが、スピードが強制移動床と同じとなります。
#define MATTR_IDOHUKA_09           0x49 //上下方向移動不可:真下チェックで上・下方向へ移動不可能
#define MATTR_IDOHUKA_10           0x4a //左右方向移動不可:真下チェックで右・左方向へ移動不可能
#define MATTR_ROCKCLIM_01          0x4b //岩壁上下:上下チェックから秘伝技で移動可能
#define MATTR_ROCKCLIM_02          0x4c //岩壁左右:左右チェックから秘伝技で移動可能
#define MATTR_SUIRYU_01            0x50 //未使用:真下チェックで右方向に進み、進入不可能なトリビュートやＯＢＪにぶつかると止まる。強制移動中はエンカウントしない。流れの先に陸地がある場合は、陸に飛び乗る。
#define MATTR_SUIRYU_02            0x51 //未使用:真下チェックで左方向に進み、進入不可能なトリビュートやＯＢＪにぶつかると止まる。強制移動中はエンカウントしない。流れの先に陸地がある場合は、陸に飛び乗る。
#define MATTR_SUIRYU_03            0x52 //未使用:真下チェックで上方向に進み、進入不可能なトリビュートやＯＢＪにぶつかると止まる。強制移動中はエンカウントしない。流れの先に陸地がある場合は、陸に飛び乗る。
#define MATTR_SUIRYU_04            0x53 //未使用:真下チェックで下方向に進み、進入不可能なトリビュートやＯＢＪにぶつかると止まる。強制移動中はエンカウントしない。流れの先に陸地がある場合は、陸に飛び乗る。
#define MATTR_K_IDOU01             0x54 //未使用:
#define MATTR_K_IDOU02             0x55 //未使用:
#define MATTR_WATER_GYM_HEIGHT01       0x56 //水ジム高さ当たり判定:水ジム水位ヒット判定:高さが0の場合、通れる
#define MATTR_WATER_GYM_HEIGHT02       0x57 //水ジム高さ当たり判定:水ジム水位ヒット判定:高さが2の場合、通れる
#define MATTR_WATER_GYM_HEIGHT03       0x58 //水ジム高さ当たり判定:水ジム水位ヒット判定:高さが4の場合、通れる
#define MATTR_WATER_NO_IN          0x59 //拡張高さデータを取得した場合は入れない:グリッド内で拡張高さデータを取得した場合は進入ができず、通常高さデータを取得した場合は進入可能
#define MATTR_MAT_17               0x5e //階段（右向きで機能）:
#define MATTR_MAT_18               0x5f //階段（左向きで機能）:
#define MATTR_MAT_01               0x60 //未使用:真下チェックで場所移動／移動後の向きは下向きで下に１歩移動する。主に洞窟入口や階段で使用。
#define MATTR_MAT_02               0x61 //未使用:真下チェックで場所移動・移動後の向きは移動前と同じ
#define MATTR_MAT_03               0x62 //マット（右向きで機能）:十時キーを右に押すと、真下チェックで場所移動
#define MATTR_MAT_04               0x63 //マット（左向きで機能）:十時キーを左に押すと、真下チェックで場所移動
#define MATTR_MAT_05               0x64 //マット（上向きで機能）:十時キーを上に押すと、真下チェックで場所移動
#define MATTR_MAT_06               0x65 //マット（下向きで機能）:十時キーを下に押すと、真下チェックで場所移動
#define MATTR_MAT_07               0x66 //未使用:真下チェックで場所移動／落とし穴エフェクト
#define MATTR_MAT_08               0x67 //未使用:真下チェックで場所移動／ワープエフェクト
#define MATTR_MAT_09               0x68 //未使用:真下チェックで場所移動（砂煙エフェクト）／間欠泉で下から跳ね上がってきた時は、砂煙エフェクトの後に、右向きで飛び出る。そして右１つ横のセルに着地。砂煙ＯＢＪは、gym04_1.sch 
#define MATTR_MAT_10               0x69 //ドア開閉（一歩移動）:下の位置から十字キーを上に押されると場所移動／移動後の向きは移動前と同じ。ドアアニメーションあり。
#define MATTR_MAT_11               0x6a //エスカレーター（折り返す）:真下チェックで、反応。乗ったときと、降りたときで、向きが逆転する
#define MATTR_MAT_12               0x6b //エスカレーター（折り返さない）:真下チェックで、反応。乗ったときと、降りたときで、向きが同じ
#define MATTR_MAT_13               0x6c //矢印無しマット（右向きで機能）:十時キーを右に押すと、真下チェックで場所移動
#define MATTR_MAT_14               0x6d //矢印無しマット（左向きで機能）:十時キーを左に押すと、真下チェックで場所移動
#define MATTR_MAT_15               0x6e //矢印無しマット（上向きで機能）:十時キーを上に押すと、真下チェックで場所移動
#define MATTR_MAT_16               0x6f //矢印無しマット（下向きで機能）:十時キーを下に押すと、真下チェックで場所移動
#define MATTR_BRIDGE               0x70 //橋:この先橋、もしくは橋終了
#define MATTR_BRIDGE_GROUND        0x71 //橋（下は地面）:上は橋、下は地面
#define MATTR_BRIDGE_GROUND_E       0x72 //橋（下は地面エンカウント）:上は橋、下は地面エンカウント
#define MATTR_BRIDGE_WATER         0x73 //橋（下は海）:上は橋、下は海
#define MATTR_BRIDGE_SAND          0x74 //橋（下は砂）:上は橋、下は砂
#define MATTR_BRIDGE_SNOW          0x75 //橋（下は雪）:上は橋、下は一番浅い雪
#define MATTR_BRIDGEV_GROUND       0x76 //一本橋縦（下は地面）:上は一本橋、下は地面
#define MATTR_BRIDGEV_GROUND_E       0x77 //一本橋縦（下は地面エンカウント）:上は一本橋、下は地面エンカウント
#define MATTR_BRIDGEV_WATER        0x78 //一本橋縦（下は海）:上は一本橋、下は海
#define MATTR_BRIDGEV_SAND         0x79 //一本橋縦（下は砂）:上は一本橋、下は砂
#define MATTR_BRIDGEH_GROUND       0x7a //一本橋横（下は地面）:上は一本橋、下は地面
#define MATTR_BRIDGEH_GROUND_E       0x7b //一本橋横（下は地面エンカウント）:上は一本橋、下は地面エンカウント
#define MATTR_BRIDGEH_WATER        0x7c //一本橋横（下は海）:上は一本橋、下は海
#define MATTR_BRIDGEH_SAND         0x7d //一本橋横（下は砂）:上は一本橋、下は砂
#define MATTR_COUNTER_1            0x80 //カウンター:前方チェックで一歩前のＯＢＪと会話が可能
#define MATTR_PC_1                 0x83 //パソコン:
#define MATTR_KANBAN_1             0x84 //未使用:前方チェックで対応メッセージを表示
#define MATTR_MAP_1                0x85 //マップ:前方チェックで対応メッセージを表示
#define MATTR_TV_1                 0x86 //テレビ:前方チェックで対応メッセージを表示。
#define MATTR_KANBAN_PC            0x87 //未使用:前方チェックで対応メッセージを表示
#define MATTR_KANBAN_FS            0x88 //未使用:前方チェックで対応メッセージを表示
#define MATTR_KAGU_1               0x89 //未使用:前方チェックでスロットができます。
#define MATTR_KAGU_2               0x8a //未使用:前方チェックでルーレットができます。
#define MATTR_KAGU_3               0x8b //未使用:前方チェックで対応メッセージを表示
#define MATTR_KAGU_4               0x8c //未使用:前方チェックで対応メッセージを表示。合い言葉が分かっていれば、階段セルに貼り替える。
#define MATTR_PC2_1                0x8d //未使用:ドアとしての機能は持たないがエフェクト起動チェックは反応するドア
#define MATTR_PC2_2                0x8e //未使用:前方チェックで対応メッセージを表示（自宅１階にノートを配置）
#define MATTR_FS_1                 0x8f //未使用:前方チェックでアンケート画面へ転移
#define MATTR_FREEZE_1             0x90 //未使用:下の位置からチェックで「ひみつのちから」使用可能
#define MATTR_CHAMPION_1           0x91 //未使用:十時キーを上に押すと、前方チェックで、洞窟基地へ移動
#define MATTR_CHAMPION_2           0x92 //未使用:下の位置からチェックで「ひみつのちから」使用可能
#define MATTR_SNOW_01              0xa1 //浅い雪:
#define MATTR_SNOW_02              0xa2 //深い雪:
#define MATTR_SNOW_03              0xa3 //とても深い雪:
#define MATTR_SWAMP_01             0xa4 //沼:
#define MATTR_SWAMP_02             0xa5 //深い沼:
#define MATTR_SWAMPGRASS_01        0xa6 //沼草:
#define MATTR_SWAMPGRASS_02        0xa7 //深い沼草:
#define MATTR_SNOW_04              0xa8 //とても浅い雪:
#define MATTR_JITEN_01             0xd0 //未使用:
#define MATTR_JITEN_02             0xd1 //:
#define MATTR_TAKEOFF_01           0xd7 //ジャンプ台（左から）:自転車で加速して突っ込むとジャンプできる。
#define MATTR_TAKEOFF_02           0xd8 //ジャンプ台（右から）:自転車で加速して突っ込むとジャンプできる。
#define MATTR_SLOPE_01             0xd9 //流砂（上段）:自転車で4速で突っ込まないと押し戻される
#define MATTR_SLOPE_02             0xda //流砂（下段）:自転車で4速で突っ込まないと押し戻される
#define MATTR_BUMPPOST_01          0xdb //車止め:自転車で当たると自転車から降りる
#define MATTR_LITTLERACK_01        0xe0 //小さい本棚１:前方チェックで対応メッセージを表示
#define MATTR_BOOKRACK_01          0xe1 //大きな本棚１:前方チェックで対応メッセージを表示
#define MATTR_BOOKRACK_02          0xe2 //大きな本棚２:前方チェックで対応メッセージを表示
#define MATTR_POT_01               0xe3 //つぼ:前方チェックで対応メッセージを表示
#define MATTR_TRASHBOX_01          0xe4 //ゴミ箱:前方チェックで対応メッセージを表示
#define MATTR_SHOPRACK_01          0xe5 //デパート＆ショップの棚１:前方チェックで対応メッセージを表示
#define MATTR_BLUEPRINT_01         0xe6 //設計図:前方チェックで対応メッセージを表示
#define MATTR_LITTLERACK_02        0xea //小さい本棚２:前方チェックで対応メッセージを表示
#define MATTR_SHOPRACK_02          0xeb //デパート＆ショップの棚２:前方チェックで対応メッセージを表示
#define MATTR_SHOPRACK_03          0xec //デパート＆ショップの棚３:前方チェックで対応メッセージを表示
#define MATTR_NO_ATTR              0xff //アトリビュートなし:アトリビュートが取得できなかったときのリターンコード
