//==============================================================================
/**
 * @file		msg_cmsg_acting.h
 * @brief		メッセージID参照用ヘッダファイル
 *
 * このファイルはコンバータにより自動生成されています
 */
//==============================================================================
#ifndef __MSG_CMSG_ACTING_H__
#define __MSG_CMSG_ACTING_H__

#define	CAMSG_TALK_SELECT_JUDGE		(0)
#define	CAMSG_TALK_SELECT_WAZA		(1)
#define	CAMSG_TALK_SELECT_WAZA0002		(2)
#define	CAMSG_TALK_WAZA_APPEAL		(3)
#define	CAMSG_TALK_JUDGE_LOOK		(4)
#define	CAMSG_TALK_JUDGE_SUFFER		(5)
#define	CAMSG_TALK_JUDGE_SUFFER0002		(6)
#define	CAMSG_TALK_JUDGE_SUFFER0003		(7)
#define	CAMSG_TALK_JUDGE_SUFFER0004		(8)
#define	CAMSG_TALK_NO_JUDGE_SUFFER		(9)
#define	CAMSG_TALK_VOLTAGE_UP_1		(10)
#define	CAMSG_TALK_VOLTAGE_UP_2		(11)
#define	CAMSG_TALK_VOLTAGE_UP_3		(12)
#define	CAMSG_TALK_VOLTAGE_UP_4		(13)
#define	CAMSG_TALK_VOLTAGE_UP_5		(14)
#define	CAMSG_TALK_VOLTAGE_UP_6		(15)
#define	CAMSG_TALK_VOLTAGE_SUB_1		(16)
#define	CAMSG_TALK_VOLTAGE_SUB_10		(17)
#define	CAMSG_TALK_VOLTAGE_SUB_2		(18)
#define	CAMSG_TALK_VOLTAGE_SUB_3		(19)
#define	CAMSG_TALK_VOLTAGE_SUB_4		(20)
#define	CAMSG_TALK_VOLTAGE_SUB_5		(21)
#define	CAMSG_TALK_VOLTAGE_STATE_UP_2		(22)
#define	CAMSG_TALK_VOLTAGE_STATE_UP_3		(23)
#define	CAMSG_TALK_VOLTAGE_STATE_UP_4		(24)
#define	CAMSG_TALK_VOLTAGE_STATE_UP_5		(25)
#define	CAMSG_TALK_VOLTAGE_STATE_SUB_3		(26)
#define	CAMSG_TALK_VOLTAGE_STATE_SUB_2		(27)
#define	CAMSG_TALK_VOLTAGE_STATE_SUB_1		(28)
#define	CAMSG_TALK_VOLTAGE_STATE_SUB_0		(29)
#define	CAMSG_TALK_TURN_RESULT_0		(30)
#define	CAMSG_TALK_TURN_RESULT_1		(31)
#define	CAMSG_TALK_TURN_RESULT_2		(32)
#define	CAMSG_TALK_TURN_RESULT_3		(33)
#define	CAMSG_TALK_TURN_RESULT_4		(34)
#define	msg_con_act_host_01		(35)
#define	msg_con_act_host_02		(36)
#define	msg_con_act_host_03		(37)
#define	msg_con_act_host_04		(38)
#define	msg_con_act_host_05		(39)
#define	msg_con_act_host_06		(40)
#define	CAMSG_CONTYPE_STYLE		(41)
#define	CAMSG_CONTYPE_BEAUTIFUL		(42)
#define	CAMSG_CONTYPE_CUTE		(43)
#define	CAMSG_CONTYPE_CLEVER		(44)
#define	CAMSG_CONTYPE_STRONG		(45)
#define	CAMSG_CONRANK_NORMAL		(46)
#define	CAMSG_CONRANK_SUPER		(47)
#define	CAMSG_CONRANK_HYPER		(48)
#define	CAMSG_CONRANK_MASTER		(49)
#define	CAMSG_CONRANK_practice		(50)
#define	CAMSG_CONRANK_link		(51)
#define	CAMSG_CONRANK_contest		(52)
#define	CAMSG_MODORU		(53)
#define	msg_con_a_tut_01		(54)
#define	msg_con_a_tut_02		(55)
#define	msg_con_a_tut_03		(56)
#define	msg_con_a_tut_04		(57)
#define	msg_con_a_tut_05		(58)
#define	msg_con_a_tut_06		(59)
#define	msg_con_a_tut_07		(60)
#define	msg_con_a_tut_08		(61)
#define	msg_con_a_tut_09		(62)
#define	msg_con_a_tut_10		(63)
#define	msg_con_a_tut_11		(64)
#define	msg_con_a_tut_12		(65)
#define	msg_con_a_tut_13		(66)
#define	msg_con_a_tut_14		(67)
#define	msg_con_a_explain_01		(68)
#define	msg_con_a_explain_02		(69)
#define	msg_con_a_prac_apreface		(70)
#define	msg_con_a_prac_01		(71)
#define	msg_con_a_caution_01		(72)

#endif
