//==============================================================================
/**
 * @file		msg_cmsg_wazaexplain.h
 * @brief		メッセージID参照用ヘッダファイル
 *
 * このファイルはコンバータにより自動生成されています
 */
//==============================================================================
#ifndef __MSG_CMSG_WAZAEXPLAIN_H__
#define __MSG_CMSG_WAZAEXPLAIN_H__

#define	CMSG_EXPLAIN_UP_1		(0)
#define	CMSG_EXPLAIN_DOWN_1		(1)
#define	CMSG_EXPLAIN_UP_2		(2)
#define	CMSG_EXPLAIN_DOWN_2		(3)
#define	CMSG_EXPLAIN_UP_3		(4)
#define	CMSG_EXPLAIN_DOWN_3		(5)
#define	CMSG_EXPLAIN_UP_4		(6)
#define	CMSG_EXPLAIN_DOWN_4		(7)
#define	CMSG_EXPLAIN_UP_5		(8)
#define	CMSG_EXPLAIN_DOWN_5		(9)
#define	CMSG_EXPLAIN_UP_6		(10)
#define	CMSG_EXPLAIN_DOWN_6		(11)
#define	CMSG_EXPLAIN_UP_7		(12)
#define	CMSG_EXPLAIN_DOWN_7		(13)
#define	CMSG_EXPLAIN_UP_8		(14)
#define	CMSG_EXPLAIN_DOWN_8		(15)
#define	CMSG_EXPLAIN_UP_9		(16)
#define	CMSG_EXPLAIN_DOWN_9		(17)
#define	CMSG_EXPLAIN_UP_10		(18)
#define	CMSG_EXPLAIN_DOWN_10		(19)
#define	CMSG_EXPLAIN_UP_11		(20)
#define	CMSG_EXPLAIN_DOWN_11		(21)
#define	CMSG_EXPLAIN_UP_12		(22)
#define	CMSG_EXPLAIN_DOWN_12		(23)
#define	CMSG_EXPLAIN_UP_13		(24)
#define	CMSG_EXPLAIN_DOWN_13		(25)
#define	CMSG_EXPLAIN_UP_14		(26)
#define	CMSG_EXPLAIN_DOWN_14		(27)
#define	CMSG_EXPLAIN_UP_15		(28)
#define	CMSG_EXPLAIN_DOWN_15		(29)
#define	CMSG_EXPLAIN_UP_16		(30)
#define	CMSG_EXPLAIN_DOWN_16		(31)
#define	CMSG_EXPLAIN_UP_17		(32)
#define	CMSG_EXPLAIN_DOWN_17		(33)
#define	CMSG_EXPLAIN_UP_18		(34)
#define	CMSG_EXPLAIN_DOWN_18		(35)
#define	CMSG_EXPLAIN_UP_19		(36)
#define	CMSG_EXPLAIN_DOWN_19		(37)
#define	CMSG_EXPLAIN_UP_20		(38)
#define	CMSG_EXPLAIN_DOWN_20		(39)
#define	CMSG_EXPLAIN_UP_21		(40)
#define	CMSG_EXPLAIN_DOWN_21		(41)
#define	CMSG_EXPLAIN_UP_22		(42)
#define	CMSG_EXPLAIN_DOWN_22		(43)
#define	CMSG_EXPLAIN_UP_23		(44)
#define	CMSG_EXPLAIN_DOWN_23		(45)
#define	CMSG_EXPLAIN_LIST_1		(46)
#define	CMSG_EXPLAIN_LIST_2		(47)
#define	CMSG_EXPLAIN_LIST_3		(48)
#define	CMSG_EXPLAIN_LIST_4		(49)
#define	CMSG_EXPLAIN_LIST_5		(50)
#define	CMSG_EXPLAIN_LIST_6		(51)
#define	CMSG_EXPLAIN_LIST_7		(52)
#define	CMSG_EXPLAIN_LIST_8		(53)
#define	CMSG_EXPLAIN_LIST_9		(54)
#define	CMSG_EXPLAIN_LIST_10		(55)
#define	CMSG_EXPLAIN_LIST_11		(56)
#define	CMSG_EXPLAIN_LIST_12		(57)
#define	CMSG_EXPLAIN_LIST_13		(58)
#define	CMSG_EXPLAIN_LIST_14		(59)
#define	CMSG_EXPLAIN_LIST_15		(60)
#define	CMSG_EXPLAIN_LIST_16		(61)
#define	CMSG_EXPLAIN_LIST_17		(62)
#define	CMSG_EXPLAIN_LIST_18		(63)
#define	CMSG_EXPLAIN_LIST_19		(64)
#define	CMSG_EXPLAIN_LIST_20		(65)
#define	CMSG_EXPLAIN_LIST_21		(66)
#define	CMSG_EXPLAIN_LIST_22		(67)
#define	CMSG_EXPLAIN_LIST_23		(68)

#endif
