//==============================================================================
/**
 * @file		msg_debugname.h
 * @brief		メッセージID参照用ヘッダファイル
 *
 * このファイルはコンバータにより自動生成されています
 */
//==============================================================================
#ifndef __MSG_DEBUGNAME_H__
#define __MSG_DEBUGNAME_H__

#define	DEBUG_NAME_MASUDA		(0)
#define	DEBUG_NAME_SUGIMORI		(1)
#define	DEBUG_NAME_MORIMOTO		(2)
#define	DEBUG_NAME_WATANABE		(3)
#define	DEBUG_NAME_OHMORI		(4)
#define	DEBUG_NAME_UNNO		(5)
#define	DEBUG_NAME_ICHINOSE		(6)
#define	DEBUG_NAME_MATSUSHIMA		(7)
#define	DEBUG_NAME_SOGABE		(8)
#define	DEBUG_NAME_FUJIWARA		(9)
#define	DEBUG_NAME_TAMADA		(10)
#define	DEBUG_NAME_MORI		(11)
#define	DEBUG_NAME_HIRONOBU		(12)
#define	DEBUG_NAME_OOTA		(13)
#define	DEBUG_NAME_EO		(14)
#define	DEBUG_NAME_FUCHINO		(15)
#define	DEBUG_NAME_TOYAMA		(16)
#define	DEBUG_NAME_EMI		(17)
#define	DEBUG_NAME_YAGI		(18)
#define	DEBUG_NAME_OOMURA		(19)
#define	DEBUG_NAME_TOMOMICHI		(20)
#define	DEBUG_NAME_MATSUDA		(21)
#define	DEBUG_NAME_KAGAYA		(22)
#define	DEBUG_NAME_NOHARA		(23)
#define	DEBUG_NAME_TAYA		(24)
#define	DEBUG_NAME_NAHI		(25)
#define	DEBUG_NAME_IWASAWA		(26)
#define	DEBUG_NAME_GOTO		(27)
#define	DEBUG_NAME_SAITO		(28)
#define	DEBUG_NAME_TOMOYA		(29)
#define	DEBUG_NAME_OHNO		(30)
#define	DEBUG_NAME_NISHINO		(31)
#define	DEBUG_NAME_TETSUJI		(32)
#define	DEBUG_NAME_SIMOYAMADA		(33)
#define	DEBUG_NAME_TOMISAWA		(34)
#define	DEBUG_NAME_KAWACHIMARU		(35)
#define	DEBUG_NAME_SATO		(36)
#define	DEBUG_NAME_TADASHI		(37)
#define	DEBUG_NAME_NAKATSUI		(38)
#define	DEBUG_NAME_HIROKI		(39)
#define	DEBUG_NAME_MATSUMIYA		(40)
#define	DEBUG_NAME_JOHNNY		(41)
#define	DEBUG_NAME_MASAFUMI		(42)
#define	DEBUG_NAME_SAYA		(43)
#define	DEBUG_NAME_DIAMOND		(44)
#define	DEBUG_NAME_PEARL		(45)
#define	DEBUG_NAME_NGNAME		(46)
#define	DEBUG_NAME_KAEDE		(47)
#define	DEBUG_NAME_PUKA		(48)
#define	DEBUG_NAME_MASARIN		(49)
#define	DEBUG_NAME_NORIRIN		(50)
#define	DEBUG_NAME_YOSINORI		(51)
#define	DEBUG_NAME_T_1		(52)
#define	DEBUG_NAME_TAKAFUMI		(53)
#define	DEBUG_NAME_TORECHEKO		(54)
#define	DEBUG_NAME_NORIHIDE		(55)
#define	DEBUG_NAME_NORISTAR		(56)
#define	DEBUG_NAME_WWWWW		(57)

#endif
