#ifndef POKEDIAMOND_CONFIG_H
#define POKEDIAMOND_CONFIG_H

#define VERSION_SAPPHIRE    1
#define VERSION_RUBY        2
#define VERSION_EMERALD     3
#define VERSION_FIRE_RED    4
#define VERSION_LEAF_GREEN  5
#define VERSION_DIAMOND    10
#define VERSION_PEARL      11

#define LANGUAGE_JAPANESE 1
#define LANGUAGE_ENGLISH  2
#define LANGUAGE_FRENCH   3
#define LANGUAGE_ITALIAN  4
#define LANGUAGE_GERMAN   5
#define LANGUAGE_SPANISH  7
#define LANGUAGE_KOREAN   8
#define LANGUAGE_COUNT LANGUAGE_KOREAN

#ifdef DIAMOND
#define GAME_VERSION VERSION_DIAMOND
#else
#define GAME_VERSION VERSION_PEARL
#endif

#define GAME_LANGUAGE LANGUAGE_ENGLISH

#endif //POKEDIAMOND_CONFIG_H
