#ifndef POKEDIAMOND_CONFIG_H
#define POKEDIAMOND_CONFIG_H

// #define NDEBUG

#ifdef DIAMOND
#define GAME_VERSION VERSION_DIAMOND
#else
#define GAME_VERSION VERSION_PEARL
#endif

#define GAME_LANGUAGE LANGUAGE_ENGLISH

#endif //POKEDIAMOND_CONFIG_H
