#ifndef _BATTLE_ROOM_DEF_H_
#define _BATTLE_ROOM_DEF_H_

//スクリプトデータID定義 
#define	SCRID_BATTLE_ROOM_GUIDE		(9100)
#define	SCRID_BATTLE_ROOM_EXIT		(9101)
#define	SCRID_BATTLE_ROOM_FORCEEND		(9102)
#define	SCRID_BATTLE_ROOM_DATA_MAX		(3)		//最大数

#endif //_BATTLE_ROOM_DEF_H_
