#ifndef _CONNECT_DEF_H_
#define _CONNECT_DEF_H_

//スクリプトデータID定義 
#define	SCRID_CONNECT_OBJ_CHANGE		(9000)
#define	SCRID_CONNECT_COLOSSEUM		(9001)
#define	SCRID_CONNECT_COLOSSEUM_BATTLE_START		(9002)
#define	SCRID_CONNECT_UNION		(9003)
#define	SCRID_CONNECT_RECORD		(9004)
#define	SCRID_CONNECT_CONTEST		(9005)
#define	SCRID_CONNECT_COLOSSEUM_DEBUG_OYA		(9006)
#define	SCRID_CONNECT_COLOSSEUM_DEBUG_KO		(9007)
#define	SCRID_CONNECT_CONTEST_DEBUG_OYA		(9008)
#define	SCRID_CONNECT_CONTEST_DEBUG_KO		(9009)
#define	SCRID_CONNECT_WIFI_P2P_MATCH		(9010)
#define	SCRID_CONNECT_TSIGN		(9011)
#define	SCRID_CONNECT_BATTLE_RETURN		(9012)
#define	SCRID_CONNECT_UNION_RETURN		(9013)
#define	SCRID_CONNECT_RECORD_RETURN		(9014)
#define	SCRID_CONNECT_WIFI_RETURN		(9015)
#define	SCRID_CONNECT_DAME_TAMAGO_MSG		(9016)
#define	SCRID_CONNECT_DATA_MAX		(17)		//最大数

#endif //_CONNECT_DEF_H_
