#ifndef _HYOUKA_SCR_DEF_H_
#define _HYOUKA_SCR_DEF_H_

//スクリプトデータID定義 
#define	SCRID_DOCTOR_ZUKAN_HYOUKA		(9950)
#define	SCRID_PC_ZUKAN_HYOUKA		(9951)
#define	SCRID_OOKIDO_ZUKAN_HYOUKA		(9952)
#define	SCRID_HYOUKA_SCR_DATA_MAX		(3)		//最大数

#endif //_HYOUKA_SCR_DEF_H_
