#ifndef _POKESEARCHER_DEF_H_
#define _POKESEARCHER_DEF_H_

//スクリプトデータID定義 
#define	SCRID_POKE_SEARCHER		(8970)
#define	SCRID_POKE_SEARCHER_NG		(8971)
#define	SCRID_POKESEARCHER_DATA_MAX		(2)		//最大数

#endif //_POKESEARCHER_DEF_H_
