#ifndef _UNION_DEF_H_
#define _UNION_DEF_H_

//スクリプトデータID定義 
#define	SCRID_UNION_FLAG_CHANGE		(1)
#define	SCRID_UNION_INIT_CHANGE		(2)
#define	SCRID_UNION_OBJ_CHANGE		(3)
#define	SCRID_CONNECT_UNION_COMM_OBJ		(4)
#define	SCRID_CONNECT_UNION_RECEIVE_OBJ		(5)
#define	SCRID_CONNECT_UNION_DUMMY		(6)
#define	SCRID_CONNECT_UNION_TALK_OBJ		(7)
#define	SCRID_CONNECT_UNION_GUIDE		(8)
#define	SCRID_UNION_DATA_MAX		(8)		//最大数

#endif //_UNION_DEF_H_
